<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_insurance</name>
   <tag></tag>
   <elementGuidId>56b13767-0a1f-4ba0-ba63-53c1d74b4a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='2c639acf-9199-411f-b8e9-c3c2cc9f6ac8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2c639acf-9199-411f-b8e9-c3c2cc9f6ac8</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'لا يوجد للمنشأة وثائق تأمين بسبب عدم الحاجه لها' or . = 'لا يوجد للمنشأة وثائق تأمين بسبب عدم الحاجه لها')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>becfcfa3-1142-49fb-a17e-8a9c78219459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>90170254-78e7-4922-b58a-2e98bd9f8524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>368a7e96-bfaf-488d-89c7-4c60246841b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>af8ca09b-9088-404f-80c6-50d82ba3cb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected k-state-focused</value>
      <webElementGuid>c551da69-7e70-4e01-88ee-9e08eb172914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1da7e85e-f286-45b3-ba0e-57d01ed81ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a8b685e1-3bf1-424c-bba4-2077a4d1fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2c639acf-9199-411f-b8e9-c3c2cc9f6ac8</value>
      <webElementGuid>c60fc34c-a82d-4abb-a0b5-59fd8acdb974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>لا يوجد للمنشأة وثائق تأمين بسبب عدم الحاجه لها</value>
      <webElementGuid>c8d7c918-83b4-41aa-9670-b243d04b1e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2c639acf-9199-411f-b8e9-c3c2cc9f6ac8&quot;)</value>
      <webElementGuid>b5b4664b-4e45-4847-a491-2cd0fe48857b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='2c639acf-9199-411f-b8e9-c3c2cc9f6ac8']</value>
      <webElementGuid>f93101d9-b7dc-4828-8f8a-be89b92fba1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='txtInsuranceJustification_listbox']/li[2]</value>
      <webElementGuid>b81ad2cf-4c93-403a-a2a5-4c7472b987c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا يوجد للمنشأة وثائق تأمين بسبب التكلفة المادية'])[1]/following::li[1]</value>
      <webElementGuid>3c660934-2793-40ea-ac74-b4219f3a286a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حدد السبب'])[2]/following::li[2]</value>
      <webElementGuid>b1cf231d-ec78-4b7f-9bee-752e7810bec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا يوجد للمنشأة وثائق تأمين لأسباب أخرى'])[1]/preceding::li[1]</value>
      <webElementGuid>0c1f4818-6700-415e-8959-daa546329e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[9]/preceding::li[2]</value>
      <webElementGuid>77899c87-5d4a-4273-b41b-b6213233a39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div[3]/ul/li[2]</value>
      <webElementGuid>310ad1e9-2991-4964-866c-ec85c3332648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '2c639acf-9199-411f-b8e9-c3c2cc9f6ac8' and (text() = 'لا يوجد للمنشأة وثائق تأمين بسبب عدم الحاجه لها' or . = 'لا يوجد للمنشأة وثائق تأمين بسبب عدم الحاجه لها')]</value>
      <webElementGuid>66404603-bbc8-4c80-aa33-329024115c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
