<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket new reg</name>
   <tag></tag>
   <elementGuidId>159e8453-1598-4fec-8cc4-ba948a4dbe77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='NewRegistrationApproval']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewRegistrationApproval</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>20554b01-aa19-4047-977e-f830b56f9c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewRegistrationApproval</value>
      <webElementGuid>0ac02461-2e16-496b-869a-0bbf126481a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
الموافقة على الطلبات الجديدة                                                                            </value>
      <webElementGuid>dfa70cfc-7cc8-49c9-86ab-9c205343699e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewRegistrationApproval&quot;)</value>
      <webElementGuid>b41f5819-d9ca-40fa-a588-d50c088f1cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='NewRegistrationApproval']</value>
      <webElementGuid>f558ab08-eaaa-45c6-8e50-c297ddd90b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav1']/li/ul/li[2]/a/span</value>
      <webElementGuid>0478e4fa-2fd3-4249-9013-7b7150b771e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أداة تعيين الطلبات'])[1]/following::span[1]</value>
      <webElementGuid>c113eefd-5539-43a7-ba21-52625f3283c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سلتي'])[1]/following::span[2]</value>
      <webElementGuid>b36b8f83-23b6-4f0f-879b-9f5421eaedc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموافقة على طلبات التحديث'])[1]/preceding::span[1]</value>
      <webElementGuid>eebe3dae-4a7e-4358-ba91-46565bb34785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموافقة على طلبات إعادة التأهيل'])[1]/preceding::span[2]</value>
      <webElementGuid>00ade267-6048-40c6-94af-fe592a714edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الموافقة على الطلبات الجديدة']/parent::*</value>
      <webElementGuid>f43baed5-a967-4e8a-8328-8cd2fce20558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>607f4c81-65ee-48eb-bd9a-9a4bea43905e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'NewRegistrationApproval' and (text() = '
الموافقة على الطلبات الجديدة                                                                            ' or . = '
الموافقة على الطلبات الجديدة                                                                            ')]</value>
      <webElementGuid>d86dcba5-77e5-4f6b-9448-7fca12294d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
