<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select action</name>
   <tag></tag>
   <elementGuidId>9a36c8b9-c6bb-4b58-b4e4-09bcb5ea8023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='takeAction(this);'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f64d76e1-a43f-4ab9-9e79-892cf0abd96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>takeAction(this);</value>
      <webElementGuid>5bc71134-d288-4803-855a-e99254a012a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>42fe3a58-de4d-4542-b47c-e46bf700be2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إتخاذ إجراء</value>
      <webElementGuid>58a6e3c9-961c-4d2e-8759-637238797180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSupervisorInbox&quot;)/div[@class=&quot;k-grid-content k-auto-scrollable&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;wid-20-10-per&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>8aa117d9-eaca-4fba-9892-5689e5d4af89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='takeAction(this);']</value>
      <webElementGuid>63bb464f-121c-4efd-bf5f-c95a2b3fb2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdSupervisorInbox']/div[2]/table/tbody/tr/td[14]/a</value>
      <webElementGuid>ea89298b-ba87-4ffe-97c8-c6378ed6d2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إتخاذ إجراء')]</value>
      <webElementGuid>b204233b-9ff1-4a6b-9ff7-329008756dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عملية التأهيل'])[1]/following::a[1]</value>
      <webElementGuid>d70228d1-a070-44d9-8a45-fa8532026545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المراجعة من قبل مشرف التأهيل'])[1]/following::a[1]</value>
      <webElementGuid>e44054cd-3dbd-4758-9c44-f8730e65c106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::a[6]</value>
      <webElementGuid>d0e61eaf-60f0-4706-b91f-5a12f8a92257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[6]</value>
      <webElementGuid>d441d050-4998-41f3-90e7-788f16b34c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/a</value>
      <webElementGuid>328eb417-f05a-4fa0-9442-0b4d28ed9682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'إتخاذ إجراء' or . = 'إتخاذ إجراء')]</value>
      <webElementGuid>26d418f0-8547-43b5-8fdd-0ecdbd59a5cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
