<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Supervisor comment</name>
   <tag></tag>
   <elementGuidId>9410fda9-c627-420c-b687-9df9b04a0ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='PreQualificationAuditorComment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PreQualificationAuditorComment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a6af9b71-5895-49fa-82a8-4dfb239adff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b019fec9-76d8-437f-a499-afad32710f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fd1bd16e-af5f-42a5-a8c7-7b722fb48736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PreQualificationAuditorComment</value>
      <webElementGuid>1ce1fb69-472d-4136-9cc7-142ef700b520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>dc518bc5-2b00-4209-a8ff-900491429b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PreQualificationAuditorComment</value>
      <webElementGuid>2a95ea64-7d78-4763-9141-dcdc5b4ef33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الملاحظات</value>
      <webElementGuid>c425ee7c-7dc2-416a-b445-8fb8a6ea1b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4f7154b0-c007-4a6e-9df5-69732fef6bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>945cfc7a-e3b8-422a-827f-0699f6a9b2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PreQualificationAuditorComment&quot;)</value>
      <webElementGuid>e2c841dc-f543-4b62-bf17-46ae2b1c9cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='PreQualificationAuditorComment']</value>
      <webElementGuid>aca30c5f-dcdc-45d3-8b5d-ee66e09beb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subcontentfull']/div/div[3]/div[3]/div[2]/fieldset/div[2]/div/div[2]/textarea</value>
      <webElementGuid>f7d62e64-c43f-449c-b22b-9c80391a0179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div[2]/textarea</value>
      <webElementGuid>8dda288a-0791-4e44-af6e-b2de157403e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'PreQualificationAuditorComment' and @name = 'PreQualificationAuditorComment' and @placeholder = 'الملاحظات']</value>
      <webElementGuid>a55a8f41-6f53-40dc-a3df-0a0a9d82be4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
