<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>f998a996-e1c5-4883-bd72-7e7d94f5f4e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_AddInsuranceDetails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_AddInsuranceDetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15c21257-1ae7-40e4-88cc-cc680c496b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xs pull-right btnadd k-button k-button-icontext k-grid-إضافة تفاصيل التأمين</value>
      <webElementGuid>91760774-f2a6-47cd-ae9e-a3217a1500c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6280e533-590c-49c9-baa6-9251e28a0eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_AddInsuranceDetails</value>
      <webElementGuid>832240aa-1116-4608-8e24-006842638af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>btnAddInsuranceDetails()</value>
      <webElementGuid>e264174b-19ab-4540-af94-966824c2cc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إضافة تفاصيل التأمين</value>
      <webElementGuid>8255cccf-5873-4847-acdb-3edaa10b47ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_AddInsuranceDetails&quot;)</value>
      <webElementGuid>822ad716-015d-4dde-9b75-c6b85bd1d8a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_AddInsuranceDetails']</value>
      <webElementGuid>7a32eeb0-a140-461d-ac4f-96095b2f088e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='InsuranceGrid']/div/a</value>
      <webElementGuid>0547eb13-c7d1-4f82-a6c7-cdafb430a77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إضافة تفاصيل التأمين')]</value>
      <webElementGuid>d2b32faf-7132-40f1-b3a0-355bd2c270bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا يوجد للمنشأة وثائق تأمين بسبب التكلفة المادية'])[1]/following::a[1]</value>
      <webElementGuid>23d2d239-082d-457c-8c18-ed9e623bf5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مبررات'])[1]/following::a[1]</value>
      <webElementGuid>ed2d64fe-07ac-48d6-be76-12efc92f3b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[2]/preceding::a[1]</value>
      <webElementGuid>1291ea7e-9763-4235-8b52-1b3ddf28e30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الملف'])[3]/preceding::a[1]</value>
      <webElementGuid>aa560d51-2585-4bbe-b1c3-51c2bd190cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة تفاصيل التأمين']/parent::*</value>
      <webElementGuid>36910631-f303-4ad0-a7ab-d25ecea0100c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[93]</value>
      <webElementGuid>429f5050-3c82-4e3d-9add-774aadec36d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/a</value>
      <webElementGuid>4b458ebc-b01d-4a64-ad33-2064c0b84bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btn_AddInsuranceDetails' and (text() = 'إضافة تفاصيل التأمين' or . = 'إضافة تفاصيل التأمين')]</value>
      <webElementGuid>6c642ea9-c2dd-4f77-ab92-1e991170e889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
