<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__InsuranceAttachments</name>
   <tag></tag>
   <elementGuidId>3a160b1e-84a5-4ef5-ad99-a695609bfef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InsuranceAttachments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InsuranceAttachments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>361569f8-c7b5-4bca-b7d6-419aa6db1c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-styled Thumbnail</value>
      <webElementGuid>a057ee57-91ec-4711-b66a-7cb29179594a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validmask-msg</name>
      <type>Main</type>
      <value>يرجى تحميل الملف</value>
      <webElementGuid>3774b0f4-01fa-41aa-8660-739914b36894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsuranceAttachments</value>
      <webElementGuid>fa9b6f99-fb7a-438f-be53-7cfe089e4975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsuranceAttachments</value>
      <webElementGuid>6194be28-4111-44e5-85b9-ec2d6ca9c1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Browse the File</value>
      <webElementGuid>25d03164-88a3-4c5d-a4eb-9522429d7f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>b53b9d50-737d-4469-b637-2e278e3ebd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a31b48f5-f4e2-4537-9fe0-38410bfed4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>7f10acb4-84ca-4496-b7af-a1ff286617e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>b9c5e6a7-5e74-412b-b279-4314dde10e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d86a8fbb-e041-4f73-ab50-c40a0d73e7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InsuranceAttachments&quot;)</value>
      <webElementGuid>45fdbf06-58f4-4732-b843-322b2c3ee195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InsuranceAttachments']</value>
      <webElementGuid>21938529-ec23-428d-b25c-cc0e18ec1079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormInsurance']/div[4]/div/div/div/input</value>
      <webElementGuid>b01e38f0-aaa7-42f1-8f6f-d786747005b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div/div/div/input</value>
      <webElementGuid>85fb1fea-ebb2-43af-9d85-1f8afa648b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InsuranceAttachments' and @name = 'InsuranceAttachments' and @placeholder = 'Browse the File' and @type = 'file']</value>
      <webElementGuid>fa6cad90-9661-4f8b-aac4-330d851df18e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
