<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__financialAttachments</name>
   <tag></tag>
   <elementGuidId>abc52099-d433-45e4-81cd-d3328601b5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#financialAttachments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='financialAttachments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73033b23-482a-40db-864d-85f54e6ff8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-styled Thumbnail</value>
      <webElementGuid>5623a099-c48f-47d6-8863-a279ea087f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validmask-msg</name>
      <type>Main</type>
      <value>يرجى تحميل الملف</value>
      <webElementGuid>f29bc993-3c6d-480f-afcd-0f4cbef74d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>financialAttachments</value>
      <webElementGuid>bc61d0c6-36c0-4dcd-85f3-7d50f4a78b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>financialAttachments</value>
      <webElementGuid>2ee77915-2132-4fdd-b819-17749b0b4fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Browse the File</value>
      <webElementGuid>636e3d42-9275-4d78-b792-dd6591ae5cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1873cd65-0370-4117-a639-54568bd92462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>f07b92a6-9149-4ec0-9571-600b91df7a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>070a11ff-29a9-4094-886e-0f70e4de2346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financialAttachments&quot;)</value>
      <webElementGuid>1332b48e-c2c1-40c8-b0d5-73aee955c998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='financialAttachments']</value>
      <webElementGuid>a8a0e153-88b7-46f0-adf3-27ba18a98ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[8]/div[2]/div/div/input</value>
      <webElementGuid>4cb5e15f-1c67-4748-8f5b-08158209f5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/input</value>
      <webElementGuid>fec6b48d-bc3a-4e19-baef-9e6cc237b093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'financialAttachments' and @name = 'financialAttachments' and @placeholder = 'Browse the File' and @type = 'file']</value>
      <webElementGuid>eaab0839-ed67-40c0-803f-98cf6c5f109e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
