<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Equity</name>
   <tag></tag>
   <elementGuidId>09c7ad06-66be-4140-b5f1-f42531a741c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtEquity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEquity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>574d707d-6400-4f10-97d0-b7960adaf981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>747b6c05-262c-459a-ae1c-b499da06351a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35220635-d38f-4da8-967c-b46ef11913d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل القيمة المالية مطلوب</value>
      <webElementGuid>fe62c809-f735-4656-8b26-5008cfd395c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEquity</value>
      <webElementGuid>67a81a6f-a1de-43b5-b457-bc5cb8549797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7c797271-7d06-411c-a67a-88228efc21d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Equity</value>
      <webElementGuid>6f39bdd0-2631-4b22-ae52-a4c2c2632407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>القيمة المالية</value>
      <webElementGuid>9d284800-30e5-4499-9b67-343bd78e32e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>1fb2f695-0f1c-4020-a0af-8081a972cd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>القيمة المالية</value>
      <webElementGuid>814cd3f2-a696-4804-bcc1-5f58169ad53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fcb6f02-b29e-4e9f-8149-c69ff65e0796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEquity&quot;)</value>
      <webElementGuid>844a10f2-2ea8-4138-b586-8b479b2adda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEquity']</value>
      <webElementGuid>27579fd8-e36a-4728-8f31-d81b38e5b8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[6]/div[2]/input</value>
      <webElementGuid>effe2bcc-4832-414c-9598-b98bd8657793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[6]/div[2]/input</value>
      <webElementGuid>dbaf7753-a751-4755-93a6-bc81e2124c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtEquity' and @name = 'Equity' and @placeholder = 'القيمة المالية' and @title = 'القيمة المالية' and @type = 'text']</value>
      <webElementGuid>af2d9111-eb86-4e44-9e47-d3abf5b02e73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
