<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NonCurrentAssets</name>
   <tag></tag>
   <elementGuidId>11cbd109-415a-4158-b1dc-33371ca026c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNonCrntAssets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNonCrntAssets']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7100d7ab-175c-4f79-a567-a2cfb3a4990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>94b6714d-cc13-4ca6-bc5b-e8994bfcc2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>221928a0-0b5c-4366-9064-e2bb015af420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الاصول غير المتداولة مطلوب</value>
      <webElementGuid>6ed5964a-9d2e-48df-9bf3-2c673a1df918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNonCrntAssets</value>
      <webElementGuid>7b51981d-e128-4478-aeb5-e526e2692650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2d87b648-b36b-41e6-bfb8-8c93d278058b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NonCurrentAssets</value>
      <webElementGuid>e8d19009-f9e6-4228-93e3-0f6284817f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الاصول غير المتداولة</value>
      <webElementGuid>8bc57939-da5e-45aa-9961-8ee6d61ff731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b0bf6994-09d0-4e08-b7c1-acba0f78146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>الاصول غير المتداولة</value>
      <webElementGuid>6e4df3fe-c8cd-4ae4-9162-b2083fa4fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9e2eb4a-9142-46b8-9fdd-a0bd40dc7400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNonCrntAssets&quot;)</value>
      <webElementGuid>37f79b17-46b5-4a67-80e9-f08ea238b42e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNonCrntAssets']</value>
      <webElementGuid>ca98ea4d-0a66-4ee9-975a-712e73dbc54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[3]/div[2]/input</value>
      <webElementGuid>355ae4fb-ae55-41ff-81a6-a48f9254117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[3]/div[2]/input</value>
      <webElementGuid>7858508c-9562-4bc8-8070-f2509b4c2d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtNonCrntAssets' and @name = 'NonCurrentAssets' and @placeholder = 'الاصول غير المتداولة' and @title = 'الاصول غير المتداولة' and @type = 'text']</value>
      <webElementGuid>ec5aaaa7-3b2e-426d-a98a-672e543b1cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
