<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CurrentMaturityLongTermDebt</name>
   <tag></tag>
   <elementGuidId>f3637d12-4139-42c0-8491-c023aded10b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCrntMaturityAssetDebt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCrntMaturityAssetDebt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dd00f6f-2cb9-415c-bdcc-fae3e99b852a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>b80df98b-2c51-4a94-a1c4-89fa9c2391bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e16f1d40-966d-46db-b816-5413c3ac7625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الاستحقاق الحالي للديون طويلة الأجل مطلوب</value>
      <webElementGuid>89e7e643-00ab-4bb2-9845-8f4914bc7cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCrntMaturityAssetDebt</value>
      <webElementGuid>a28be61d-4edb-45c3-81d8-5d4411d5de4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2badcc08-49fc-4e1f-a5f7-eb4758f8393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CurrentMaturityLongTermDebt</value>
      <webElementGuid>9955bf1f-200c-4207-90ae-982d71ad57a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الاستحقاق الحالي للديون طويلة الأجل</value>
      <webElementGuid>7c87d728-af4a-4b4a-ad9c-4bc98273d173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>6787b5fd-cb59-4e03-b281-d4254c206ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>الاستحقاق الحالي للديون طويلة الأجل</value>
      <webElementGuid>313b6022-a51c-42e0-98de-180fc40d4fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c253eceb-433f-43ab-9101-d206f8db5239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCrntMaturityAssetDebt&quot;)</value>
      <webElementGuid>e357e02d-c61a-4248-a941-8f788ed66e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCrntMaturityAssetDebt']</value>
      <webElementGuid>6b44434b-5529-4299-9710-8e6e0ad30d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[4]/div[2]/input</value>
      <webElementGuid>5d3913df-f45f-40f3-86e9-b23ba0dd7c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[4]/div[2]/input</value>
      <webElementGuid>b109728c-8165-41f2-b3c9-78b2e7efa54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCrntMaturityAssetDebt' and @name = 'CurrentMaturityLongTermDebt' and @placeholder = 'الاستحقاق الحالي للديون طويلة الأجل' and @title = 'الاستحقاق الحالي للديون طويلة الأجل' and @type = 'text']</value>
      <webElementGuid>8ea78ab3-bd27-41a6-9183-8c7fc9ddaed2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
