<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NonCurrentLiabilities</name>
   <tag></tag>
   <elementGuidId>c465f4a0-964e-4539-88ab-bf021328b7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNonCrntLiabilities</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNonCrntLiabilities']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d8eb6cd-e5c1-4e91-afd2-44c13975e8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>9b3fa310-5114-4237-b8f5-79c63cf7fe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18ccddaf-1dc5-4c24-86cf-76b3565ab9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل المطلوبات غير متداولة مطلوب</value>
      <webElementGuid>d43980a6-9a37-4a0d-879c-6584804e3a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNonCrntLiabilities</value>
      <webElementGuid>6cb20473-9ed0-455b-b1ce-9135b100a7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>64cdc430-0b76-485f-b736-afca3b362d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NonCurrentLiabilities</value>
      <webElementGuid>ea42f6ed-e69d-4624-aa0c-f800e392aebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>المطلوبات غير متداولة</value>
      <webElementGuid>ece58ae5-c32e-4819-bca9-fffcc5b4a69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>c670b8c1-18d0-4836-96ae-00a52d74c49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>المطلوبات غير متداولة</value>
      <webElementGuid>56119561-4960-4351-92ff-72f066010501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c2a3428-2799-49ad-a58a-e688f4d9a2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNonCrntLiabilities&quot;)</value>
      <webElementGuid>7e7ec5a4-109c-455a-83c9-d7e4b5d3fc58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNonCrntLiabilities']</value>
      <webElementGuid>af099674-8140-498a-871d-8705cbc5b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[6]/div/input</value>
      <webElementGuid>b55d841f-d283-450f-b686-d603d5c6f916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[6]/div/input</value>
      <webElementGuid>575c4646-5b0b-4b17-8080-d6d0ace1d971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtNonCrntLiabilities' and @name = 'NonCurrentLiabilities' and @placeholder = 'المطلوبات غير متداولة' and @title = 'المطلوبات غير متداولة' and @type = 'text']</value>
      <webElementGuid>e467660f-a2c2-4747-a3f7-36723b283ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
