<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Revenues</name>
   <tag></tag>
   <elementGuidId>134e7371-4637-4592-a2c6-c42f4ed3c104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRevenues</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRevenues']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb5d27f8-9194-42d4-aa38-e29a1e0b6c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>cef010c3-5acf-45db-b48e-8a1a9e7292ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc2b9997-bd90-4c61-8c2b-59b6909ce8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل إجمالي الايرادات مطلوب</value>
      <webElementGuid>9cd3e2eb-da7f-44e6-b800-c84173187803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRevenues</value>
      <webElementGuid>90c35637-e320-411d-9f73-39042467d4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e3502d01-563e-4e6c-946e-e69b56978cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Revenues</value>
      <webElementGuid>d86e7777-5d21-4f1c-b2bb-5667c30e0c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>إجمالي الايرادات</value>
      <webElementGuid>5d6e02e1-b61a-4e21-b9f7-f4f874f26ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>2294467b-d4b3-4d6f-ae61-56df1a5e83f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>إجمالي الايرادات</value>
      <webElementGuid>1f917adb-5fbc-4d44-88b1-5bd13441e51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c20877ed-e993-4230-b6d7-20c650e74519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRevenues&quot;)</value>
      <webElementGuid>fd6e2121-9ed2-4f1a-a839-761ca2e5ca2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRevenues']</value>
      <webElementGuid>febb487f-c7e8-4b69-b767-69c64cb5f363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[7]/div/input</value>
      <webElementGuid>319aaea9-0e16-4b64-b9e0-3e758e758e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[7]/div/input</value>
      <webElementGuid>40f33103-4da8-453d-9115-a49b5b4551a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtRevenues' and @name = 'Revenues' and @placeholder = 'إجمالي الايرادات' and @title = 'إجمالي الايرادات' and @type = 'text']</value>
      <webElementGuid>59547ead-abb8-42ec-a9ea-293254f167dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
