<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GrossProfit</name>
   <tag></tag>
   <elementGuidId>eff61319-ee58-4198-b416-d2ea952888a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtGrossProfit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtGrossProfit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2eb820a-8f47-46bf-9a0d-b1473e1f363d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>20da32a2-90b1-4eef-a3c9-82dce0072cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbd840c4-124d-4421-b63f-a64a2b136754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل إجمالي الربح مطلوب</value>
      <webElementGuid>e8aa0130-197f-4055-84ec-f571b8b77341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtGrossProfit</value>
      <webElementGuid>5a5974cd-3cbd-4604-82e7-c8c41cbcb64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>834ee9a1-1e70-40a7-bb3b-e2c0640a638b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GrossProfit</value>
      <webElementGuid>ba76d16a-d022-45d9-bf8f-6736e767b081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>إجمالي الربح</value>
      <webElementGuid>5db354cc-aa60-4fa5-9f85-100933e17902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>9ac99839-56f9-4098-9f93-7fc91459b370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>إجمالي الربح</value>
      <webElementGuid>8782cbd9-dea4-40de-8217-19e44c7d15b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55f4ef6b-8ad0-4c59-afcc-35eae90de291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtGrossProfit&quot;)</value>
      <webElementGuid>409ccc0d-04ab-41bc-b6f6-df5374d12cb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtGrossProfit']</value>
      <webElementGuid>094feefa-f638-45d2-a1a7-572ac595c1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[7]/div[2]/input</value>
      <webElementGuid>b80f08f2-24bc-434c-87a0-9737308f0a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>b89b5765-d1e7-40ab-9eb6-f4b42ae7da2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtGrossProfit' and @name = 'GrossProfit' and @placeholder = 'إجمالي الربح' and @title = 'إجمالي الربح' and @type = 'text']</value>
      <webElementGuid>29a8764e-629e-4b88-9dbf-8df7031463e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
