<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Inventory</name>
   <tag></tag>
   <elementGuidId>f47df1ee-f73a-45e8-87e6-819ae1e54e7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtInventory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtInventory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5fc465c-d783-44ee-8309-0b1b90480802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>a8f67f95-c664-4640-8530-c709bd828fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c49c6106-15d8-4c10-bc27-93f6ea818687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل المخزون مطلوب</value>
      <webElementGuid>86de1323-7811-4bf0-9628-15ee65090060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtInventory</value>
      <webElementGuid>bc116af0-4a4d-4ac1-b14d-1fa45c24fcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0c421f6f-c297-45dc-bc73-97645a14923b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Inventory</value>
      <webElementGuid>755f42af-8b36-4d5d-a58d-4e2c34b748c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>المخزون</value>
      <webElementGuid>a98a610e-3b3a-49ac-9ef1-b7001829b4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b57c8b28-e085-4f7d-ab28-6c36097679e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>المخزون</value>
      <webElementGuid>4564a44d-fbc6-4c0b-a36e-cc3a29b6f827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d3657f7-3e14-498f-b368-efdc2f340c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtInventory&quot;)</value>
      <webElementGuid>88f34e59-6449-4f7e-9087-e30ebfe28285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtInventory']</value>
      <webElementGuid>c7330a87-1a0e-439f-bf73-a4d1b0d54b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[2]/div/input</value>
      <webElementGuid>40c4021d-b70d-42f1-a564-8bb5daa1e85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>b206630d-4bac-456b-983e-d400620ddf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtInventory' and @name = 'Inventory' and @placeholder = 'المخزون' and @title = 'المخزون' and @type = 'text']</value>
      <webElementGuid>d9454a86-ed20-433f-a548-b48cea45f951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
