<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__InsuranceCompany</name>
   <tag></tag>
   <elementGuidId>e2c6f427-c269-4784-a731-5a38ae2f336f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtInsuranceCompany</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtInsuranceCompany']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c846ebc5-f4f8-4df2-9c44-37e84dd0ab34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb0d342b-74fc-480b-a50f-6991fc650e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtInsuranceCompany</value>
      <webElementGuid>696a1c67-b088-4199-b8b1-5872ed1ccf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>910a46ec-4dfc-4617-9143-d52bcad1af48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InsuranceCompany</value>
      <webElementGuid>0d3764ff-af2c-498e-b446-8d071a7c7ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>شركة التأمين</value>
      <webElementGuid>ffcbb674-5297-4a01-b517-d70df13b8d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>412d0926-8d42-4f93-8f1a-87e4a29fab24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>شركة التأمين</value>
      <webElementGuid>837eb401-670e-46b9-9e35-defaa184b835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c39b6181-3034-4696-9447-d719b4cb7e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtInsuranceCompany&quot;)</value>
      <webElementGuid>caa466ee-b543-4dea-8723-a4e1309e7ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtInsuranceCompany']</value>
      <webElementGuid>81e8a5aa-b634-47e5-81b9-4d480971cb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormInsurance']/div/div[2]/input</value>
      <webElementGuid>ab1b1ba2-12ae-46f8-b20f-cdf5c012de8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>9993a82a-5429-484e-8d7d-592f0236f842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtInsuranceCompany' and @name = 'InsuranceCompany' and @placeholder = 'شركة التأمين' and @title = 'شركة التأمين' and @type = 'text']</value>
      <webElementGuid>0cbd4714-b6f2-484a-b87a-6fdb20f57584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
