<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Recievables</name>
   <tag></tag>
   <elementGuidId>d89d7fe3-232e-4bcb-8c5d-a4a70c826d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRecievables</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRecievables']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e03fb96e-df6e-4252-88b3-26d217dd0abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>305ba659-1f65-444e-8f85-e60ba3c5bfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e98f9a2f-6941-427b-a033-6a9c04943461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل ذمم مدينة مطلوب</value>
      <webElementGuid>e3988ad3-da2f-4261-9784-90136ddc4d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRecievables</value>
      <webElementGuid>b1df6489-1eeb-4f29-8acb-37a9da12f0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>944831d7-cf22-412d-92fe-022fdada5534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Recievables</value>
      <webElementGuid>ccbb3ac6-6c45-4158-b570-b0df8f90b71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ذمم مدينة</value>
      <webElementGuid>86023367-b00d-4ec4-a2ad-c2348e31df4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b0aae628-464f-4eb8-ab96-a8eca1883501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ذمم مدينة</value>
      <webElementGuid>3a71e81e-d29e-41fd-9e69-3bed8189ddec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02a816f1-3c25-48d4-9c5c-f6a1e5e10951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRecievables&quot;)</value>
      <webElementGuid>c17799d9-3ade-4888-a990-408446db199f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRecievables']</value>
      <webElementGuid>8de92be9-7f6b-4167-9c77-0c9eaf53f212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[2]/div[2]/input</value>
      <webElementGuid>48b3a3e9-90b2-4b5a-8359-f1a231057a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[2]/div[2]/input</value>
      <webElementGuid>c5d033d9-03e4-4a45-8304-05dec92190f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtRecievables' and @name = 'Recievables' and @placeholder = 'ذمم مدينة' and @title = 'ذمم مدينة' and @type = 'text']</value>
      <webElementGuid>6b652273-9c46-47f6-9e0e-98117e3517d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
