<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NetIncome</name>
   <tag></tag>
   <elementGuidId>2a93bfc2-7479-46c1-8413-1b4cfe190159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNetincome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNetincome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84593f6f-2308-496f-83af-b60db641ec83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>a4a2ac2b-4c64-4264-aab5-fa9ab9962618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0687b18d-315a-404e-ab71-76964650e1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل صافي الخسارة مطلوب</value>
      <webElementGuid>5596836e-3121-43db-8bb1-b858e11dde89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNetincome</value>
      <webElementGuid>95836738-b001-461a-8c34-f39950d36569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0ffae273-74ad-403a-ad73-fb7db0d2cc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NetIncome</value>
      <webElementGuid>e9f5f7c8-0a40-43fe-a8fb-04877d4b0e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>صافي الخسارة</value>
      <webElementGuid>fa438029-3294-4293-8c95-a4935d05c11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>dba29486-8552-4ba0-a333-a37109914897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>صافي الخسارة</value>
      <webElementGuid>f3421a37-3aec-4f9e-8e19-2afe4bf504ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f8d3816-fc06-4fa2-a64d-1bc1d340b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNetincome&quot;)</value>
      <webElementGuid>07c6fe6d-9467-4cec-ab91-cc1482780de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNetincome']</value>
      <webElementGuid>94532146-441c-4c63-ae00-25aa95bf501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[8]/div/input</value>
      <webElementGuid>78b0cbf7-c369-4a75-a898-53abeeb841c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>ddbaeb23-bb4d-4b15-ba3d-402e403c84bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtNetincome' and @name = 'NetIncome' and @placeholder = 'صافي الخسارة' and @title = 'صافي الخسارة' and @type = 'text']</value>
      <webElementGuid>6c858a3b-b652-4595-b6ac-78e182968fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
