<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_</name>
   <tag></tag>
   <elementGuidId>733158e0-ab26-4e61-8dfb-ef09d48342ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k-animation-container > #InsuranceTypes-list > div.k-list-scroller > #InsuranceTypes_listbox > li.k-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='InsuranceTypes_listbox']/li)[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a7cd6933-bde8-4fb1-b8c5-43861ab103d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>60d46447-5c1e-4ca9-84a5-710a718e016c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cc32aae7-3557-4a1e-b059-4012f8771d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>edea766c-c779-44a4-a59d-4da51cd052c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>d5770469-d969-4d84-819c-d91da96ab561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa4f665c-3bf8-4e26-8eb6-d7846859e7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2413ba9-1c4b-42ed-8d2e-e6e9049ca64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>كل المخاطر</value>
      <webElementGuid>e30ae094-8fd2-4fd4-93d2-d3890fdfbd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainBody&quot;)/div[@class=&quot;k-animation-container&quot;]/div[@id=&quot;InsuranceTypes-list&quot;]/div[@class=&quot;k-list-scroller&quot;]/ul[@id=&quot;InsuranceTypes_listbox&quot;]/li[@class=&quot;k-item&quot;]</value>
      <webElementGuid>154d444d-bd6c-4821-a6dd-060e084fbc34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='InsuranceTypes_listbox']/li)[17]</value>
      <webElementGuid>8c728769-9bfd-4257-8496-0f1232a7c2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--اختر نوع التأمين--'])[3]/following::li[1]</value>
      <webElementGuid>b1aeb97f-e2d7-4afa-9610-e21eafb3fb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      <webElementGuid>eec2b07a-9705-47e6-a769-7fc69eea2a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إصابات جسدية'])[2]/preceding::li[1]</value>
      <webElementGuid>1c2a5bec-19eb-47d8-9b67-910c093788e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عقد'])[2]/preceding::li[2]</value>
      <webElementGuid>dd1460dc-747d-4ec0-9fa0-b511e0027af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[114]/div/div[3]/ul/li</value>
      <webElementGuid>f5b73f5e-da78-4e03-9866-8f588318f86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'كل المخاطر' or . = 'كل المخاطر')]</value>
      <webElementGuid>1d4861a9-d995-439d-b6b0-228e20f4413b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
