<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save11</name>
   <tag></tag>
   <elementGuidId>987b6f1a-015d-4d9e-9c7d-94858012cb5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSend_Finance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSend_Finance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94ca800b-79de-4c82-86c0-78de6e35c31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f56c0fe-f077-4a77-b6bf-30289f06bb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>9fbf6f45-f847-4748-8fbc-d997e314f8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSend_Finance</value>
      <webElementGuid>8d42b1c1-eabf-4c07-9441-675b03da16b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>7b5d17b2-5c26-4cf7-b88b-14efa2ff0153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSend_Finance&quot;)</value>
      <webElementGuid>d3a7471c-a9ac-46c2-b1e6-4d50f811bbb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSend_Finance']</value>
      <webElementGuid>ff7df4a0-66ae-47ed-a0f2-7254ac41c5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TechnicalTab']/div/div/div[3]/input[2]</value>
      <webElementGuid>c3539eb0-01f7-46d8-84cf-4d4702bba53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div[3]/input[2]</value>
      <webElementGuid>8f317b3a-9902-43c3-941f-cc83c0609f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSend_Finance']</value>
      <webElementGuid>53c20213-c390-4037-a8c2-b705061d80c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
