<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save mony</name>
   <tag></tag>
   <elementGuidId>40d525a9-cdc6-4e80-a583-8590e4f0631e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnTechnicalSave_Popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnTechnicalSave_Popup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7ce7bd0-b921-41cd-ab44-2c098949b7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c27a7a92-93c2-4ad3-a371-430bf91aaf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnTechnicalSave_Popup</value>
      <webElementGuid>5c0d1ebf-cde3-475a-91a4-d78daf0bc1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnapprove</value>
      <webElementGuid>0d17fc6b-e5b7-4e6c-9833-b04c6c74fa88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حفظ</value>
      <webElementGuid>1b0c5e94-e2d7-4d84-b7ae-553f5c749a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnTechnicalSave_Popup&quot;)</value>
      <webElementGuid>1c89abed-c36d-4f41-aa4e-f69b5d3e1c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnTechnicalSave_Popup']</value>
      <webElementGuid>dfc6721f-6750-4ba2-9c84-4e45666aa322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[10]/button</value>
      <webElementGuid>27d5fa96-3a6c-4549-8d09-f8d0bf07c535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر ملف ...'])[5]/following::button[1]</value>
      <webElementGuid>c1f29c45-d641-4600-8ffe-5631de63e569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نسخة رسمية من القوائم المالية'])[1]/following::button[1]</value>
      <webElementGuid>3ceee214-28a9-4980-a67f-f1f395c5589a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اقفال'])[1]/preceding::button[1]</value>
      <webElementGuid>05deca1e-f3d8-46e3-86c1-3b96f31bc39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::button[6]</value>
      <webElementGuid>98405a90-42c7-48f7-837a-72c7249b1224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button</value>
      <webElementGuid>dc4d44b5-5f74-4b24-8068-16a93e4b079d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnTechnicalSave_Popup' and (text() = 'حفظ' or . = 'حفظ')]</value>
      <webElementGuid>c1023018-657a-42e5-8b1e-d086460de9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
