<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-    -_k-select</name>
   <tag></tag>
   <elementGuidId>9d4ef412-2309-4fe5-a7b2-f16a67776045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-focused.k-state-hover > span.k-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='FormFinancial']/div/div/div[2]/span/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d25d467a-0463-4ef6-8563-aa5b95314eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0df6201f-b876-4d18-85fa-ee0a6abb50dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>26704bf4-3f5d-4e94-bcdc-cace74538a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dfc126d8-41da-40d5-9878-2f7fbcf28d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormFinancial&quot;)/div[@class=&quot;panel-body no-padding-top&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-md-6 col-lg-6&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused k-state-hover&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>57eb1b27-a490-4b16-84da-b11bddbb950f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div/div[2]/span/span/span[2]</value>
      <webElementGuid>6b97ab26-99a9-435c-b065-acf43cf088b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- اختر نوع العملة -'])[1]/following::span[1]</value>
      <webElementGuid>e9502acf-9089-4b99-bffc-b1409c26187d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عملة'])[1]/following::span[4]</value>
      <webElementGuid>ca4f4f92-ae31-42a7-a1d1-b6e4e8edd6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحقل عملة مطلوب'])[1]/preceding::span[2]</value>
      <webElementGuid>88cc96b4-706c-464a-87e9-2def342b272c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المخزون'])[2]/preceding::span[4]</value>
      <webElementGuid>ea183ed6-4328-4ea7-803d-90b8f6310afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div/div[2]/span/span/span[2]</value>
      <webElementGuid>a0692401-b7cb-48f5-81be-13c870e28454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
