<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_20</name>
   <tag></tag>
   <elementGuidId>60348490-82a0-42f3-b496-f96c293fb972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-today.k-weekend.k-state-hover > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='88048fdf-e9b3-46ed-bf8f-a355ba9f52a9']/table/tbody/tr[4]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43479cc6-cb69-4439-9458-9276f6f984ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9567af32-cf6f-472c-aa46-23aeacb8bd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>3aaf9149-b229-4678-9685-db0a712550cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d8a6cd20-5553-468d-9a26-4408c538d6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2022/10/20</value>
      <webElementGuid>1fa3ee4e-cc1d-47eb-baef-ba6ce4956e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sunday, November 20, 2022</value>
      <webElementGuid>48fbee24-aafa-4353-aefa-59f7eab2926e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f24da8c3-ead4-4fec-8111-54b473caa501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;88048fdf-e9b3-46ed-bf8f-a355ba9f52a9&quot;)/table[@class=&quot;k-content k-month&quot;]/tbody[1]/tr[4]/td[@class=&quot;k-today k-weekend k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>eb49f6be-3391-496d-a760-5ed3dc2b4308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='88048fdf-e9b3-46ed-bf8f-a355ba9f52a9']/table/tbody/tr[4]/td/a</value>
      <webElementGuid>0788cb7d-f4e9-45c7-8901-d281a3f73054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'20')])[14]</value>
      <webElementGuid>abde1207-725f-446c-bea6-b4df517d5604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[5]/following::a[22]</value>
      <webElementGuid>785ee587-149e-4ba7-9e86-7b4a7f750ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[5]/following::a[22]</value>
      <webElementGuid>f91e4a82-0d41-4d8b-8af9-3598d45fbb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[242]</value>
      <webElementGuid>d0023a1a-0455-43e1-bdfd-c291d33b3e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[118]/div/div/table/tbody/tr[4]/td/a</value>
      <webElementGuid>23bafd5d-087d-4bed-9cec-041c0671067a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Sunday, November 20, 2022' and (text() = '20' or . = '20')]</value>
      <webElementGuid>f6c656ac-5b4b-439d-b983-ef905974abf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
