<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4</name>
   <tag></tag>
   <elementGuidId>40bd8a05-e22e-4ae0-b42b-06c86eb9c791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-other-month.k-weekend.k-state-hover > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1bf9d8e8-48e4-4a8d-81b9-270f57765b2e']/table/tbody/tr[6]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>349422a7-ca63-4734-8315-4ea81e7a72e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bba93061-8087-4089-9e03-27c936b46503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>f1c62327-ac3c-4cb1-8da0-4d05fa8f838e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b3a5a561-3db4-4cf7-81b1-1c34fdd74dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2022/11/4</value>
      <webElementGuid>5320310d-acbf-4f8a-976e-3a2305920162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sunday, December 04, 2022</value>
      <webElementGuid>b4d0e777-f601-436f-80f3-415534a731e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6cfde379-b2f8-48b6-85e7-07c4b71d8773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1bf9d8e8-48e4-4a8d-81b9-270f57765b2e&quot;)/table[@class=&quot;k-content k-month&quot;]/tbody[1]/tr[6]/td[@class=&quot;k-other-month k-weekend k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>5fdcce31-de59-41e8-98e6-455e23b0bfe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1bf9d8e8-48e4-4a8d-81b9-270f57765b2e']/table/tbody/tr[6]/td/a</value>
      <webElementGuid>e3608f4b-e328-4068-a8af-69bf6c063f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'4')])[23]</value>
      <webElementGuid>b238a980-2ea6-416f-bb6e-c68ca3ed2ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[6]/following::a[36]</value>
      <webElementGuid>b3eeea88-83e8-44f0-8fa7-f68ea9ea5c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[6]/following::a[36]</value>
      <webElementGuid>8facc5a3-350a-4478-9ade-75828cdf7c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[302]</value>
      <webElementGuid>66afa4bc-8b86-4510-ab39-932531b496be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[119]/div/div/table/tbody/tr[6]/td/a</value>
      <webElementGuid>15711c40-919e-44a9-926c-bff43b1d0a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Sunday, December 04, 2022' and (text() = '4' or . = '4')]</value>
      <webElementGuid>cdd1674e-24de-4117-ab55-45480743e3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
