<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fdUpload-149</name>
   <tag></tag>
   <elementGuidId>4b6279f7-fb97-4ded-8d55-19e4dedff488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fdUpload-149</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fdUpload-149']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61273ed8-466c-471c-aa6d-04df6890a6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fdUpload-149</value>
      <webElementGuid>b1ec80a3-9e3c-452e-918d-39c86c80eb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fdUpload-149</value>
      <webElementGuid>bbebafbc-bfbd-44ba-92d3-4d4c2c26c576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>cdaaab4e-b11e-424f-883b-9a766144c9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>28e62b69-2c19-4efa-bd1d-44315f412135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>e248c9e2-84c5-4bf3-b843-e909fc3d2b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dd0800ef-7536-4c44-8337-5fe4b5543330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdUpload-149&quot;)</value>
      <webElementGuid>0c499cd5-bd76-4010-8489-9a34825ea492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fdUpload-149']</value>
      <webElementGuid>ff57c084-c3cd-444e-a4dd-a03de5f0448c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_149']/div/div/input</value>
      <webElementGuid>c407851c-8cb5-4817-a71f-c2b670c00e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/input</value>
      <webElementGuid>af5911ab-8717-400f-b0e5-4ddc85ff1106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fdUpload-149' and @name = 'fdUpload-149' and @type = 'file']</value>
      <webElementGuid>56f5adde-5432-4f5e-a470-30b4bcf5d01c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
