<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fdUpload-157</name>
   <tag></tag>
   <elementGuidId>b14b322f-c8fb-4a27-856a-c2762727c09c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fdUpload-157</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fdUpload-157']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b99c35a8-c1eb-4493-a6e3-bd9f2e2ad6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fdUpload-157</value>
      <webElementGuid>2f13b258-3877-491f-a10f-ce0b1cc1d126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fdUpload-157</value>
      <webElementGuid>f4e14d38-8187-441e-8a3b-970660d69166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>169e6706-ddf7-4ce3-b153-47482366d5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>f7d8b2c3-aac6-4735-b093-ba03f722412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>ab8ff960-03df-4a8c-8f75-9c8835d2329e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2f1e4f0a-f593-4bd7-9b08-ef5c31949980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdUpload-157&quot;)</value>
      <webElementGuid>527947fd-296a-4722-83d5-6c76999b4bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fdUpload-157']</value>
      <webElementGuid>24ce4876-e446-4561-9c1e-4cf7f31192ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_157']/div/div/input</value>
      <webElementGuid>8a0cad3e-9665-42f7-bb25-2425f6a01921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/div/div/input</value>
      <webElementGuid>7319434b-bdc2-4e56-8cb4-ab7522e6ccf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fdUpload-157' and @name = 'fdUpload-157' and @type = 'file']</value>
      <webElementGuid>c35d22cd-a58d-4ef2-a9cd-07d00d87a69c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
