<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(QMS)_childitem.AnswerAr</name>
   <tag></tag>
   <elementGuidId>8fc0c360-0b9f-4ad9-a206-268be97158a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb0f2e55-9c26-4ce0-8e8b-0f950cdd1516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>097e02c9-a29e-4ae5-84c5-7779675606f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAnswer</value>
      <webElementGuid>76120aa6-cad8-4031-8311-497872c13d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>childitem.AnswerAr</value>
      <webElementGuid>28036dcc-f2dc-4f6b-9401-f1ca04bc3404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e753123-ce88-42e0-a447-cb334b187cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdControls_151&quot;)/input[@id=&quot;txtAnswer&quot;]</value>
      <webElementGuid>a3b14fe1-68f8-4bbe-b50b-a7ffa8f5d7e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAnswer']</value>
      <webElementGuid>f08ecb5d-e8f8-4380-a5f7-36e7f287b46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_151']/input</value>
      <webElementGuid>dea74321-5086-48ef-b6f4-d510abd96a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>25d2fbf1-5bcd-4db7-bdf5-01fd2768c586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtAnswer' and @name = 'childitem.AnswerAr' and @type = 'text']</value>
      <webElementGuid>f408e734-df09-44f4-a9d5-bf578c37b4ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
