<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fdUpload-159</name>
   <tag></tag>
   <elementGuidId>9a44c80c-9546-4b25-89ee-f5c6c8af3435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fdUpload-159</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fdUpload-159']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ff5573c-6df6-47f8-ac91-74ef4970efa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fdUpload-159</value>
      <webElementGuid>6b99e4b7-55f9-41e8-b459-80c01850a1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fdUpload-159</value>
      <webElementGuid>c191d056-52d8-4fd3-8a93-e20f1f7e4a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7299c859-0d7e-4a10-9446-a3fb38833955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>dab5f9c1-3b7a-4af9-a094-5f0f5ae69756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>f21d7ddb-db44-4d5e-9d6b-22eaab6bb78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>426e5110-4ca7-4ab8-a649-8711ae5a9944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdUpload-159&quot;)</value>
      <webElementGuid>8ddc79e2-074f-40ea-8f20-e5bf7b13b01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fdUpload-159']</value>
      <webElementGuid>4dca0f70-0c91-4926-87d6-be4a665636ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_159']/div/div/input</value>
      <webElementGuid>ceffdacc-411c-4cd2-b4ef-9df0c1edabfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/input</value>
      <webElementGuid>5c7f1edc-2dec-4f0a-bb0c-7da04182d3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fdUpload-159' and @name = 'fdUpload-159' and @type = 'file']</value>
      <webElementGuid>936ad97d-6a4d-40e4-83d8-06b2a192845b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
