<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_scroll</name>
   <tag></tag>
   <elementGuidId>cbbbd75c-3408-4f5b-8eed-ba8a6a0e83d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.col-sm-8.col-lg-8.col-sm-6.col-xs-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='QuestionnaireTbl']/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>16ff928d-b04f-4024-b577-79d7e8d99d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>Questions</value>
      <webElementGuid>e51b9059-d769-4fc5-bbe4-02b644388f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-8 col-lg-8 col-sm-6 col-xs-6</value>
      <webElementGuid>e9c40a23-0707-4066-8b8c-e14906546d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>سؤال</value>
      <webElementGuid>6be56336-ebf7-4fba-b01c-d08bbb4d64ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuestionnaireTbl&quot;)/thead[1]/tr[1]/th[@class=&quot;col-sm-8 col-lg-8 col-sm-6 col-xs-6&quot;]</value>
      <webElementGuid>92425b26-d122-4d19-a845-63a47a9541c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='QuestionnaireTbl']/thead/tr/th</value>
      <webElementGuid>67b5fc09-f6a7-40da-9919-c2bacee82ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نظام الإدارة البيئية'])[1]/following::th[1]</value>
      <webElementGuid>e2454c99-d063-4db5-bda3-532befb63cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نظام ادارة الجودة'])[1]/following::th[1]</value>
      <webElementGuid>95f55876-8687-4a5c-9032-240b9e2b3b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الرد'])[1]/preceding::th[1]</value>
      <webElementGuid>bb17be9b-3748-44c5-95d0-53f1122b4b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هل لدى منشأتك أنظمة إدارة الجودة (QMS)؟'])[1]/preceding::th[2]</value>
      <webElementGuid>47b672f5-4af2-4828-8549-e0ae32dfd3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='سؤال']/parent::*</value>
      <webElementGuid>40b5abc3-ec3d-4405-9680-35b7978018e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div/div/table/thead/tr/th</value>
      <webElementGuid>73a36973-aded-454f-98fe-1c8fdc3ee029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'سؤال' or . = 'سؤال')]</value>
      <webElementGuid>4f43e1aa-0cd6-46ed-a4ff-802edec502ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
