<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assign</name>
   <tag></tag>
   <elementGuidId>38a281cf-cf33-4b8d-b785-d0c014e289a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='AssignMe'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>055d8ddd-02bf-4068-81eb-d2b9b706a9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AssignMe</value>
      <webElementGuid>9cdc43d9-191b-41d8-a2ec-c66b4c42f727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>js_AsignMeprofile(1204);</value>
      <webElementGuid>9e357f66-0565-42af-8724-dfc74e342b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>40729e4d-3ab8-41f0-ba03-643fc18305d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تعيين لي</value>
      <webElementGuid>be93ce20-3f50-4154-b7a8-681f63bff25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdPreQualificationAuditorNewRegPending&quot;)/div[@class=&quot;k-grid-content k-auto-scrollable&quot;]/table[@class=&quot;k-selectable&quot;]/tbody[1]/tr[@class=&quot;k-alt&quot;]/td[14]/a[@id=&quot;AssignMe&quot;]</value>
      <webElementGuid>9e6f9904-c3cb-4b7c-8cba-84a90e7501b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='AssignMe'])[2]</value>
      <webElementGuid>de363c5e-aa9b-48ea-945a-6f3774cd9ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdPreQualificationAuditorNewRegPending']/div[3]/table/tbody/tr[2]/td[14]/a</value>
      <webElementGuid>03b4b7f3-86d5-42cb-85cb-4e04dc073651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'تعيين لي')])[2]</value>
      <webElementGuid>e14c0d02-e131-446c-8b28-49e9dc82f601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='غيرمعتمد'])[2]/following::a[1]</value>
      <webElementGuid>9128a9c6-09da-4cb9-bf26-83a55da36ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحديث التصنيف'])[1]/following::a[1]</value>
      <webElementGuid>828e3687-04cb-4f52-8627-5fc83141ae74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ورشة أسرار الخشب للنجارة'])[3]/preceding::a[1]</value>
      <webElementGuid>ec49e462-8fab-4a5f-a2e5-1ea32ab6c838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='وكيل, مورد'])[1]/preceding::a[1]</value>
      <webElementGuid>3f33fffd-b4b5-4cb6-93fb-3ec6b94c91ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[14]/a</value>
      <webElementGuid>a797f12e-98c7-45f8-8208-e8457b53df22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AssignMe' and (text() = 'تعيين لي' or . = 'تعيين لي')]</value>
      <webElementGuid>09548704-83c2-471b-b79e-37242d354df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
