<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attach area</name>
   <tag></tag>
   <elementGuidId>b06f4008-c30c-4539-a750-b4936517aa48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='smeattachment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#smeattachment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4dec2147-62ab-40c9-b2e3-35b7d2941708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>smeattachment</value>
      <webElementGuid>6ee4b548-25d1-42fb-85a3-6511f788880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>مراجعة المرفقات</value>
      <webElementGuid>d7a08421-bc1f-4aac-b673-982cca1673e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smeattachment&quot;)</value>
      <webElementGuid>db900fd7-c824-4161-b4a9-85a186e25913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='smeattachment']</value>
      <webElementGuid>5d21067b-b91e-4b72-9739-3e12f743d191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu']/li/a</value>
      <webElementGuid>b463c5de-ff48-4a14-85eb-eeda2b681a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'مراجعة المرفقات')]</value>
      <webElementGuid>8cda03ff-0b90-4c18-86de-651fd79f0a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عرض الصفحة الشخصية'])[1]/following::a[1]</value>
      <webElementGuid>d38b6744-e778-43be-8a10-66a9a35710d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الزيارة الميدانية'])[1]/following::a[1]</value>
      <webElementGuid>dfb7acc5-b21f-4706-bad1-8576df4c3bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مراجعة نتائج الاستبيان'])[1]/preceding::a[1]</value>
      <webElementGuid>2b23cfbe-eab6-4e68-bddd-fd3d6f6e232f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نتائج الزيارة الميدانية'])[1]/preceding::a[2]</value>
      <webElementGuid>2dd18de8-9524-4a3d-a777-bc9052ca3ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='مراجعة المرفقات']/parent::*</value>
      <webElementGuid>94fb58fc-812a-40d5-bd91-05ffc9cf1e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/ul/li/a</value>
      <webElementGuid>e1fb2b5a-0e6c-44a4-b2eb-d1ec663fe3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'smeattachment' and (text() = 'مراجعة المرفقات' or . = 'مراجعة المرفقات')]</value>
      <webElementGuid>38c08e71-2258-4465-a18b-d8849969c1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
