<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Auditor comment</name>
   <tag></tag>
   <elementGuidId>83a8a182-66ee-4aa1-be4f-65e5d291fbcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='PreQualificationAuditorComment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PreQualificationAuditorComment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3f2670fa-3e5d-4454-ae52-996cbe0c1c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef2c014c-926f-428b-ba3e-827a16d5cfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>36e947f4-a677-42df-87c6-d6a80f780f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PreQualificationAuditorComment</value>
      <webElementGuid>231e100a-2f87-44ba-a6e4-317ffb2489c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>78f9810c-86f4-42a2-9b38-c5d2ef083456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PreQualificationAuditorComment</value>
      <webElementGuid>76b8dc36-dfda-486d-a771-2c8dc2d74d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الملاحظات</value>
      <webElementGuid>87af2675-b89d-427a-adfe-451c871037cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4aaa79ce-0df2-4d66-91a7-e90655800448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3bf8aea3-3e9e-4bf7-96f0-4836e34f89e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PreQualificationAuditorComment&quot;)</value>
      <webElementGuid>26e986e0-d467-4ae3-bd87-483cb6073962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='PreQualificationAuditorComment']</value>
      <webElementGuid>380eb4db-c5d3-4162-80b7-6533fe94caa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGrid']/div[3]/div[2]/fieldset/div[2]/div[2]/div[2]/textarea</value>
      <webElementGuid>831dde92-c9e7-40a6-92af-c0c7675e31c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>10dfd4a0-1a4d-44f5-ac2a-fe972b4c1962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'PreQualificationAuditorComment' and @name = 'PreQualificationAuditorComment' and @placeholder = 'الملاحظات']</value>
      <webElementGuid>f3190dbb-88ba-4716-89f6-a871eef7b259</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
