<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>basket new register</name>
   <tag></tag>
   <elementGuidId>2f728517-609d-4358-8592-e4bccd4a45f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spn_NewRegistrationRequests</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='NewRegistrationRequests']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d73170c-39c5-475d-aa76-c6e3b9e8044c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spn_NewRegistrationRequests</value>
      <webElementGuid>db42a2b3-d289-4b55-9768-372c7c9021e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
طلبات التسجيل الجديدة													</value>
      <webElementGuid>6f17a998-599d-43a6-a513-674ce7207693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spn_NewRegistrationRequests&quot;)</value>
      <webElementGuid>876dfe73-3284-4294-a18a-0bd3c04e71a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spn_NewRegistrationRequests']</value>
      <webElementGuid>29db4e0f-756e-461e-b166-4b96ab925a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='nav1']/li/ul/li[2]/a/span)[4]</value>
      <webElementGuid>53749c36-6f7e-42ff-8de5-6f49948d7d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات لم يتم تعيينها'])[2]/following::span[1]</value>
      <webElementGuid>53b15e10-0de1-4732-be8e-5b109dff1108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سلتي'])[2]/following::span[2]</value>
      <webElementGuid>c6840633-5bd7-41bc-91d8-b85bb580b325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات تحديث الملفات'])[2]/preceding::span[1]</value>
      <webElementGuid>565f4ec7-ffd9-466e-9cd6-529c95f1e7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات إعادة التأهيل'])[2]/preceding::span[2]</value>
      <webElementGuid>16f1405c-0ecf-449c-b3d1-c761499a147f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/ul[3]/li/ul/li[2]/a/span</value>
      <webElementGuid>ec921391-265d-417a-b7f2-ff595f30fc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spn_NewRegistrationRequests' and (text() = '
طلبات التسجيل الجديدة													' or . = '
طلبات التسجيل الجديدة													')]</value>
      <webElementGuid>2ccbc117-b0fe-4411-8800-02f32b0fd4ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
