<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_no visit</name>
   <tag></tag>
   <elementGuidId>fe56820b-6d51-4e27-92da-9153cb41f595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SearchCriteriaDiv']/div/div[2]/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e9864e5c-3b98-4acb-87d5-911d2551e687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding10-radio</value>
      <webElementGuid>1dabc5b7-08bd-41c4-9caf-0aef498388d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rdbtn_SitevstNo</value>
      <webElementGuid>03243e20-ed21-43c3-a17e-69b3fa9246f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>لا</value>
      <webElementGuid>2a7112e1-3a6d-4e72-b69b-79794644ac3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModalBody&quot;)/div[@class=&quot;panel panel-flat&quot;]/div[@class=&quot;panel-body&quot;]/fieldset[1]/div[@id=&quot;SearchCriteriaDiv&quot;]/div[@class=&quot;row paddingdiv&quot;]/div[@class=&quot;col-md-4 radio-toolbar&quot;]/label[@class=&quot;padding10-radio&quot;]</value>
      <webElementGuid>c4fca490-c43f-4a0c-912d-493abf5eaa69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchCriteriaDiv']/div/div[2]/label[2]</value>
      <webElementGuid>de11c13c-e8b0-4d63-8385-bf58fd2e6957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نعم'])[1]/following::label[1]</value>
      <webElementGuid>adc95d0c-84a0-4017-a229-5d374174ce1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلب الزيارة الميدانية الزامي , هل تريد اعفاء الزيارة الميدانية ؟'])[1]/following::label[2]</value>
      <webElementGuid>e4f66ba8-a309-4f90-a534-d7a56e12bef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التبرير'])[1]/preceding::label[1]</value>
      <webElementGuid>cca41dd5-fdde-4c51-bc89-bff48b86fc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إرسال'])[2]/preceding::label[2]</value>
      <webElementGuid>7f7e7b68-c577-4017-be23-789839c5db95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='لا']/parent::*</value>
      <webElementGuid>4177f018-876a-4982-b5b9-222eee99bb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>57079ba8-6dae-434e-8ca8-d051cefd715f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'لا' or . = 'لا')]</value>
      <webElementGuid>8bc6a310-c4c8-45e4-9c05-045fd898362f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
