<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reject comment</name>
   <tag></tag>
   <elementGuidId>6975c059-2bcc-486e-891e-22dd4adfe7d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtComments-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtComments-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>37474cfb-2e9c-45ff-91f1-3fca43f99ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtComments-16</value>
      <webElementGuid>a5ee2aa0-9e90-451a-8c17-6804c299a2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cmnts</value>
      <webElementGuid>737a3eb6-1406-4114-9a1b-59dd60fb356d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d211d7a2-077f-47ad-b345-2266a0edb49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الرجاء إدخال التبرير</value>
      <webElementGuid>4b709d4f-e604-460f-b42d-536973e8a839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>60c41c2a-e4e1-4fc3-9589-7edb3aa1ca60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>69ba1a83-b23c-425e-94bb-0d5b2097cabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtComments-16&quot;)</value>
      <webElementGuid>d9794f51-e6c3-484c-b5fc-bcbe2e6c4a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtComments-16']</value>
      <webElementGuid>ba1c23af-18d0-49ad-bcfa-8218beaa7473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdSMEAttachment']/table/tbody/tr[5]/td[6]/textarea</value>
      <webElementGuid>1d3f47b5-ae78-49bb-83fa-84e1ae104d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/textarea</value>
      <webElementGuid>d60c543a-e0b9-4f38-bdc4-6aaaff7f790d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtComments-16' and @name = '16' and @placeholder = 'الرجاء إدخال التبرير']</value>
      <webElementGuid>394a5469-9ebf-477d-9917-7157854bc6cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
