<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select basket</name>
   <tag></tag>
   <elementGuidId>e79d06c4-584a-4d98-a649-c009a35faaf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spn_MyBasket']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spn_MyBasket</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9faefc6d-d5d9-447c-8f20-9608331014e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spn_MyBasket</value>
      <webElementGuid>84eed264-7ea7-43b4-8a28-1552eb350e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
سلتي									</value>
      <webElementGuid>5e794e23-4ccc-4668-b852-47ea53480112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spn_MyBasket&quot;)</value>
      <webElementGuid>2ff1a03a-4100-4a4d-845a-4e3f6e84e7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spn_MyBasket']</value>
      <webElementGuid>d734a30c-35a6-42de-9742-dc7cc4f73bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav1']/li/span/span</value>
      <webElementGuid>4d2c2175-bb4a-4ff1-a5be-07b830d1e8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الصفحة الرئيسية'])[3]/following::span[2]</value>
      <webElementGuid>518c66e0-8a7b-4bec-a94a-cb0a6aec59d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مدقق التأهيل المسبق'])[2]/following::span[3]</value>
      <webElementGuid>b6eb4217-8a69-4959-8500-d7a6040b8a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات لم يتم تعيينها'])[2]/preceding::span[1]</value>
      <webElementGuid>10643c13-fb3d-4ab2-b8dd-3d8b3dccc487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات التسجيل الجديدة'])[2]/preceding::span[2]</value>
      <webElementGuid>fde1f281-ec30-42c6-baa2-a52555474109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>02d6473f-bbb4-46a7-804c-3e918837c64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spn_MyBasket' and (text() = '
سلتي									' or . = '
سلتي									')]</value>
      <webElementGuid>ef3d0d36-8f87-44e6-b823-13eda7a7a42d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
