<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select action</name>
   <tag></tag>
   <elementGuidId>0168b11f-0abd-4b2d-ae63-d3a03d8fc177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divGrid']/div[3]/div[2]/fieldset/div[2]/div/div[2]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd5b9c6e-602e-4122-969d-26fb9580c5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>cae0d2cc-4cd5-4a01-93d2-6299078e7766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>c17fafa8-bf1d-4b6e-95a9-57afd88c31cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تحديد</value>
      <webElementGuid>cb4b762a-ac79-44ba-baf5-94489dc56b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuestionDiv&quot;)/div[@id=&quot;divGrid&quot;]/div[@class=&quot;panel panel-flat no-padding-h&quot;]/div[@class=&quot;panel-body&quot;]/fieldset[1]/div[@class=&quot;bg-box-shadow mar-top-32&quot;]/div[@class=&quot;row paddingdiv&quot;]/div[@class=&quot;col-md-4&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-input&quot;]</value>
      <webElementGuid>f38b0ea5-ea43-41af-817c-d2ec96c7c206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGrid']/div[3]/div[2]/fieldset/div[2]/div/div[2]/span/span/span</value>
      <webElementGuid>2c6e8b23-2bd5-4f60-b9d6-6761853377e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الإجراء'])[1]/following::span[3]</value>
      <webElementGuid>3f299c5e-d1f6-4a48-bbc9-37031c20d0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشركات الصغيرة والمتوسطة'])[1]/following::span[11]</value>
      <webElementGuid>137d6491-8a75-497c-a9cb-55407c1478c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الملاحظات'])[3]/preceding::span[3]</value>
      <webElementGuid>0dc44cf7-a225-4450-850d-2de31b99cb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إرسال'])[1]/preceding::span[4]</value>
      <webElementGuid>7c24ba7d-7642-4ff1-b880-4cddedd17f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تحديد']/parent::*</value>
      <webElementGuid>279758db-fb94-434e-bdb0-49d7d1688bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>9cbadb8c-c85f-48ff-baa4-3647d056f44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'تحديد' or . = 'تحديد')]</value>
      <webElementGuid>53ecc6a3-5c47-4034-9cf0-d039ae6d765e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
