<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send to Supervisor</name>
   <tag></tag>
   <elementGuidId>e721d32e-260f-4390-8b01-cc93b304545e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='Add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btnarrright</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b7b2cc0-a7d9-4510-b5d8-c818fdf4948a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>160b6351-d0a5-49c5-ac6a-7e381356a1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>afff6180-22ea-46b1-a01e-5046452ae5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>00f82dab-a879-4006-8cd0-0b8760c842cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: SavePreQualificationAuditApprovalData();</value>
      <webElementGuid>830f98eb-4155-4205-810f-860b57647614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> إرسال</value>
      <webElementGuid>372dc334-c915-45e7-9887-8a06973854a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divAuditorControl&quot;)/button[@class=&quot;btn btn-primary btnarrright&quot;]</value>
      <webElementGuid>0aaa356a-9681-4b16-82d4-90af32d45dd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='Add']</value>
      <webElementGuid>e8674b2e-ee7e-45ff-a7d9-1084f83c7052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAuditorControl']/button</value>
      <webElementGuid>d12e13a2-e573-4d05-9395-5104743fd3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الملاحظات'])[3]/following::button[1]</value>
      <webElementGuid>3ac271ca-c50a-41ad-8d23-e7ccaab88913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحديد'])[1]/following::button[1]</value>
      <webElementGuid>a5b0ed3f-4e44-4557-93de-a03a58f173a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إلغاء'])[1]/preceding::button[1]</value>
      <webElementGuid>a33c737d-3cf6-4140-85e3-da314bd9581e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::button[8]</value>
      <webElementGuid>0597869e-4f9a-4094-b181-f3de1dc764b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إرسال']/parent::*</value>
      <webElementGuid>5e2f7983-7029-4a2b-969f-e91713034ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>71b27d73-dc15-4070-bb6a-16b26333869e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' إرسال' or . = ' إرسال')]</value>
      <webElementGuid>eb4b0c80-68be-4c66-a378-0527b5cb30eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
