<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit visit</name>
   <tag></tag>
   <elementGuidId>25e7176f-ede5-4c74-8212-e3a32aae745f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='Add'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SearchCriteriaDiv > div.modal-footer > button.btn.btn-primary.btnarrright</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f3286fd-130c-4cef-a256-4b3f124f722f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddb1e0c3-5da6-4032-af2c-abae85d13e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>2efc0d92-48ff-4226-a60b-9585d60de4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>c633dbd6-5dd1-47bc-aa4b-9df903535b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: JsSaveSiteVisit();</value>
      <webElementGuid>ff659e6f-98b9-47c5-ad4a-541ad9dc834e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إرسال</value>
      <webElementGuid>9ec27231-a827-4a21-ad2e-4ae432c4ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModalBody&quot;)/div[@class=&quot;panel panel-flat&quot;]/div[@class=&quot;panel-body&quot;]/fieldset[1]/div[@id=&quot;SearchCriteriaDiv&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-primary btnarrright&quot;]</value>
      <webElementGuid>87a20556-f09d-4408-9b70-e9a64dd4e12c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='Add'])[2]</value>
      <webElementGuid>7f3829ca-11fb-4684-9f39-d2579911ba59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchCriteriaDiv']/div[3]/button</value>
      <webElementGuid>c69413d4-7167-4f91-b41b-def453b0d928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التبرير'])[1]/following::button[1]</value>
      <webElementGuid>acb8e395-8214-40f6-854b-a411b21379fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا'])[1]/following::button[1]</value>
      <webElementGuid>3ec1f862-942a-4a6a-b097-41784fd582db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::button[5]</value>
      <webElementGuid>88ae2cdb-715f-462a-a6bb-cb9eec2b59a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[6]</value>
      <webElementGuid>aa64eaaf-fad8-467b-8322-f653944cf2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/button</value>
      <webElementGuid>24dcb0a9-ddff-4d1d-a029-62c0a793e4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'إرسال' or . = 'إرسال')]</value>
      <webElementGuid>3bfd3b8e-5f3a-4676-bb78-bb2c615d9d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
