<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add mony</name>
   <tag></tag>
   <elementGuidId>380ffc9e-95cf-4468-b398-c302ce3ccf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_AddFinanceDetails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_AddFinanceDetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0c8369e-75d6-4635-a41e-e53e7f28b3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xs pull-right btnadd k-button k-button-icontext k-grid-إضافة تفاصيل التمويل</value>
      <webElementGuid>9e396077-a734-4f9a-9ce6-08306692840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>df8cadf8-adf3-4968-8636-b088f367ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_AddFinanceDetails</value>
      <webElementGuid>f35dc3ae-73a7-4832-9598-1023fa47a45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>btnAddFinancialDetails()</value>
      <webElementGuid>2a1c3c85-a6e7-4f10-b1d5-eb74f07e4189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إضافة تفاصيل التمويل</value>
      <webElementGuid>e24e58ae-ff28-4298-a792-6cdb48272d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_AddFinanceDetails&quot;)</value>
      <webElementGuid>bfd928f3-cbf0-47e5-908a-fc68085ac73b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_AddFinanceDetails']</value>
      <webElementGuid>4e3fc377-a12a-44a8-957d-79cbf83de0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TechnicalGrid']/div/a</value>
      <webElementGuid>6afdbabf-c979-4118-9d8c-c786f826c762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إضافة تفاصيل التمويل')]</value>
      <webElementGuid>eff6ba35-5b02-4dc7-9174-d6629f85ddcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حدد السبب'])[1]/following::a[1]</value>
      <webElementGuid>05bedc20-ae14-47a8-94ca-a70886e963c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السبب'])[1]/following::a[1]</value>
      <webElementGuid>06770294-bc9e-46b2-b240-f76b0b7d6d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::a[1]</value>
      <webElementGuid>66b294df-b919-4049-9240-fe78576a37ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الملف'])[2]/preceding::a[1]</value>
      <webElementGuid>a4e72d83-01b3-4aac-bfd0-70da33e77f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة تفاصيل التمويل']/parent::*</value>
      <webElementGuid>0c949066-ba8f-4b3b-9b46-b34c4a3cf21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[92]</value>
      <webElementGuid>5ae36c65-073d-495f-8612-19f524a00574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div/a</value>
      <webElementGuid>0dd95bd0-42b7-44d0-b0f9-ab2255c54cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btn_AddFinanceDetails' and (text() = 'إضافة تفاصيل التمويل' or . = 'إضافة تفاصيل التمويل')]</value>
      <webElementGuid>bbe14394-b569-4ce9-9fc7-90f077eae934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
