<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_</name>
   <tag></tag>
   <elementGuidId>0024083b-5898-4602-93ca-e30e641110bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>*[@id=&quot;grdSMEClassificationAgentActivity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>*[@id=&quot;grdSMEClassificationAgentActivity&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'grdSMEClassificationAgentActivity_active_cell' and (text() = '​' or . = '​')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>5420155c-8c79-402d-9293-cf5eff77d516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-header</value>
      <webElementGuid>32e3535d-8ebb-4b27-8728-f2c1818b29b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>22d6b70d-67be-4475-b012-545da6363ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fecaeb70-a6c3-478f-932d-8f8391d3a514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdSMEClassificationAgentActivity_active_cell</value>
      <webElementGuid>124ad0e1-271d-4647-9d2a-05ed8d941499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>f45e08e3-92a4-4b28-8aa8-92cd5ab0f792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)</value>
      <webElementGuid>93a325b6-9be7-46d6-9b90-99b8d0aa1dc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']</value>
      <webElementGuid>aa6b788f-962b-4735-9193-6d602d1e59fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdSMEClassificationAgentActivity']/div/div/table/thead/tr/th</value>
      <webElementGuid>dfbf3118-536f-4946-a939-5847fc965307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ابحث باسم النشاط أو كود النشاط'])[2]/following::th[1]</value>
      <webElementGuid>31fc0060-dbd8-4383-a672-0b3d6090976e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[2]/following::th[1]</value>
      <webElementGuid>d7e316a6-f403-477f-ae8a-c78573501ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SME Activity ID'])[2]/preceding::th[1]</value>
      <webElementGuid>b2330320-1fa1-4453-9877-8d3959944a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/table/thead/tr/th</value>
      <webElementGuid>3af3a6f1-b878-4bd2-bc08-9b5a43c5b7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'grdSMEClassificationAgentActivity_active_cell' and (text() = '​' or . = '​')]</value>
      <webElementGuid>5b50fb9c-754d-4cd3-ad5c-1fb1dd9348a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
