<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add wakel</name>
   <tag></tag>
   <elementGuidId>7a15f31a-f593-4b76-8865-0041a2a55624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnCollapse2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCollapse2 > span.glyphicon.glyphicon-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>57445589-e962-4e35-978d-6f39f4e3fb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-plus</value>
      <webElementGuid>88416358-a71c-456d-9eb8-67d3b1da4b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCollapse2&quot;)/span[@class=&quot;glyphicon glyphicon-plus&quot;]</value>
      <webElementGuid>86efbfa4-7a4b-40b6-908a-7be6e31cc461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnCollapse2']/span</value>
      <webElementGuid>58a7868d-9075-4e36-8d98-88cce8aa6e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h5/div/span</value>
      <webElementGuid>232dfdb2-13b6-46b4-ab79-ea6f97a9c7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
