<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add nashat</name>
   <tag></tag>
   <elementGuidId>b80d6d36-ec2c-4703-8d7b-506a00e3c240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPlusClassifications']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnPlusClassifications</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65c37835-21e8-4139-9c7e-0a9b843a3b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61cdd172-edb0-49fa-9584-29f5ccbd22c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPlusClassifications</value>
      <webElementGuid>ad7e4828-946c-4459-97a4-0cd2c15ac184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnPlusClassifications</value>
      <webElementGuid>ec7a278f-7055-4115-b47f-e320e83eac45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleClassificationsMultiSelect()</value>
      <webElementGuid>eb1bd4ba-012e-4798-a533-03eef52fc6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPlusClassifications&quot;)</value>
      <webElementGuid>c2e4ffff-3d3c-44e9-93b1-9d1c447e68f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPlusClassifications']</value>
      <webElementGuid>bbef2d3e-89da-437b-b831-39734cb74279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvClassification']/div[2]/button</value>
      <webElementGuid>a92afd6d-2772-4d23-8c3b-b344f9c48563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- اختر --'])[1]/following::button[1]</value>
      <webElementGuid>beda3a53-5f48-44d6-97b4-1854081fca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تصنيف المنشآة'])[1]/following::button[1]</value>
      <webElementGuid>0cfe5bca-147e-4b0b-80e3-a1b8e8c90249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[1]/preceding::button[1]</value>
      <webElementGuid>a6b7e3a7-509d-4172-9945-a404e948de98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>72d896b5-ee22-4b05-9afa-7ca0fe5db125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPlusClassifications']</value>
      <webElementGuid>ffe17358-80ab-4413-ad11-7bca5ee2d8a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
