<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add contact</name>
   <tag></tag>
   <elementGuidId>9a0bc6a4-193d-4f48-b6a7-28cbdc1790aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_AddContactInformation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_AddContactInformation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87fabb47-5af7-46a9-ab19-3f074aaf219c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_AddContactInformation</value>
      <webElementGuid>dde4c15f-15f3-418d-9e1a-4fa4571f09c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b4477f6-7e3f-4c6d-b620-50fe246cda4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddContactInformation()</value>
      <webElementGuid>951e2f36-4dab-4c58-a426-1b589b21d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xs pull-right btnadd</value>
      <webElementGuid>ccf91321-c3e9-432f-a8ca-5d11b8325741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    إضافة معلومات الاتصال
                                </value>
      <webElementGuid>8007a271-e61f-434a-b3a4-c0d919a36e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_AddContactInformation&quot;)</value>
      <webElementGuid>d6ba00cb-3892-4649-ad11-ac8fdb3c193e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_AddContactInformation']</value>
      <webElementGuid>d8ac1323-3fb6-4567-9f11-1019b8c2a16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactInfoDiv']/div/div[3]/div/button</value>
      <webElementGuid>5652e6bb-8870-4e22-9fbb-c2e0a88c3b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='البريد الالكتروني للمنشآة'])[1]/following::button[1]</value>
      <webElementGuid>15f6bf19-8ec9-4315-b31a-e1a4874ca87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموقع الالكتروني للمنشأة'])[1]/following::button[1]</value>
      <webElementGuid>9ef1c66d-c45b-424a-a4b4-32e8ffe6058e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Information ID'])[1]/preceding::button[1]</value>
      <webElementGuid>d0178a7d-0b0f-4774-9018-e04e20e13577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نوع الاتصال'])[1]/preceding::button[1]</value>
      <webElementGuid>7cd607f0-516c-4033-b74f-3abf4adc119f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة معلومات الاتصال']/parent::*</value>
      <webElementGuid>3b71920f-e946-4a24-9900-0cc74844f05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[3]/div/button</value>
      <webElementGuid>08fbfdc6-1b12-4d43-8788-28eed2e0ce80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_AddContactInformation' and @type = 'button' and (text() = '
                                    إضافة معلومات الاتصال
                                ' or . = '
                                    إضافة معلومات الاتصال
                                ')]</value>
      <webElementGuid>b74a104a-7ccc-449d-b472-44cbd126725b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
