<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attach active cell</name>
   <tag></tag>
   <elementGuidId>340aa639-271a-41be-bb61-bc93f13a26da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AttachmentDetailsgrid_active_cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='AttachmentDetailsgrid_active_cell']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'AttachmentDetailsgrid_active_cell']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e778fb24-72f9-4ad3-a3c3-04b7048011ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-state-focused</value>
      <webElementGuid>0854cd89-be63-4552-8c9f-2b4b9a8d4601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>16194620-c459-40d3-8570-5573380ccb77</value>
      <webElementGuid>35716464-a555-42aa-b787-6e992eb439b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>a14cbbfb-335e-46ad-8c2c-a50d4c5e66a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AttachmentDetailsgrid_active_cell</value>
      <webElementGuid>c3737714-3b42-476f-af09-736a9a2819a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)</value>
      <webElementGuid>f286eb71-9f46-4a54-8def-e4fb3fafb10c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']</value>
      <webElementGuid>d59a1153-daca-4d1f-b619-243a7e0ff9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AttachmentDetailsgrid']/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>7c1d2792-0ebb-4fc6-a850-c02a0b3b6460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شهادة اثبات وكالة'])[1]/following::td[3]</value>
      <webElementGuid>58873349-6b3a-4325-9145-bea9e4d96ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::td[5]</value>
      <webElementGuid>15c4be8d-661b-4cc0-8e89-a1e68913672e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select files...'])[1]/preceding::td[1]</value>
      <webElementGuid>8d882de6-5f6f-4d65-a84b-eb728db564cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شهادة من الهيئة الملكية للجبيل وينبع'])[1]/preceding::td[10]</value>
      <webElementGuid>70c8c0c0-24ca-45a3-8ec0-d5e6c3d12285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>cf91b971-2e12-4b54-bd0e-b3dc90a30e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'AttachmentDetailsgrid_active_cell']</value>
      <webElementGuid>b50de1e9-8ceb-48d2-851f-f514f7386e19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
