<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country code</name>
   <tag></tag>
   <elementGuidId>f6541c0b-37b5-4713-90a7-dc0eecc07898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-hover.k-state-focused > span.k-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='AddContactInformationForm']/div/div[8]/div/span/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36732b97-70da-4cdb-8149-c66a4ded6c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2e323f4a-d254-45b8-b95e-6b04df2bf26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>07c2a5ae-2d3c-4a69-b642-4b3fa166c4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67a60881-d5ae-4d2b-ab85-540d8e2e9619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddContactInformationForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-md-6 col-lg-6 fl-right pad-rt-15&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>08aed5d2-bce0-4d25-a152-45338f074581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c843a94-f899-4dcc-9c49-1b0ce7d38b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>81e13833-1d60-438a-815e-e6e111ee85dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>b0823a95-16c9-45ed-b677-8b1c71bd2065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3413716a-e8ac-4401-895e-01785c1ff350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddContactInformationForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-md-6 col-lg-6 fl-right pad-rt-15&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>ff4ba398-06a5-4971-ad59-41ca2573f464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddContactInformationForm']/div/div[8]/div/span/span/span[2]</value>
      <webElementGuid>7139bece-4ddc-4751-8523-1348ae1c683f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز الدولة'])[5]/following::span[1]</value>
      <webElementGuid>d209c76d-5635-48b2-a36b-732283055781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز الدولة'])[4]/following::span[4]</value>
      <webElementGuid>85d72a85-5d26-41f5-b08c-9bc24fb7ef0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحقل رمز الدولة مطلوب'])[1]/preceding::span[2]</value>
      <webElementGuid>ba085dc8-5802-4f86-be55-295d777e5444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الجوال'])[3]/preceding::span[5]</value>
      <webElementGuid>f9e16d5d-bf5d-4c82-9c5c-31ffc01c58da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span/span/span[2]</value>
      <webElementGuid>50c423a6-5323-47c4-8a35-9d4bfe562dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
