<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LocalContentScore</name>
   <tag></tag>
   <elementGuidId>d5395cd1-a467-4ebe-b77d-e22f09141e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLocalContentScore</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txtLocalContentScore' and @name = 'LocalContentScore' and @placeholder = 'درجة المحتوى المحلي' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLocalContentScore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ba56321-faa4-4801-af4b-8d006573b137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number k-valid</value>
      <webElementGuid>5680c23f-8e9f-4127-93af-55fd48b6ea4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLocalContentScore</value>
      <webElementGuid>df484d33-0603-4ac8-ae26-7104406c8ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2bb690e6-6f05-4f05-9bfd-f61a7dfdb4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocalContentScore</value>
      <webElementGuid>f1a3a9bd-cae9-46f5-b64a-0402ab4e697d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>LocalContentScoreChangeEvent();</value>
      <webElementGuid>8e140af4-8dfd-4ffe-a969-9030f41a3423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>درجة المحتوى المحلي</value>
      <webElementGuid>885ca6f2-686a-4dc0-8010-e1ed73c8c58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f36b9aff-c038-41cd-9251-05f9ce0bb213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLocalContentScore&quot;)</value>
      <webElementGuid>7d86baae-9270-429e-9ab0-35859da040ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLocalContentScore']</value>
      <webElementGuid>a3ca5f5e-9d57-4e76-aeab-922139a6b1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLocalContentScore']/div/input</value>
      <webElementGuid>d18aeaf7-47d1-4860-adb0-7bdf272473dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div[2]/div/input</value>
      <webElementGuid>9b81d40e-a560-48b8-97af-2587cddc5fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLocalContentScore' and @name = 'LocalContentScore' and @placeholder = 'درجة المحتوى المحلي' and @type = 'text']</value>
      <webElementGuid>5e20a629-e261-4a87-88aa-3b06bdd36f32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
