<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_ZAKAT_Save</name>
   <tag></tag>
   <elementGuidId>ae979eb2-e67b-43ac-91ec-a054666d5cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_ZAKAT_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_ZAKAT_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b27b5e35-5267-4673-82d1-e16129f7a2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10034b8a-e58d-4f02-a319-2b4d92b77160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>85a1fe0c-124d-4ec8-a979-9250e1010764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_ZAKAT_Save</value>
      <webElementGuid>ada39fa6-1656-4b6b-b0cd-baa8b3a33fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>5b89ef57-dbe2-4c9e-9964-ec908185ee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_ZAKAT_Save&quot;)</value>
      <webElementGuid>5698d117-8f58-4d4c-a8f2-b817dc7ccdc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_ZAKAT_Save']</value>
      <webElementGuid>d4fb9542-3f31-49a9-8739-7db54f52da99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_ZAKAT_form']/div[3]/div/input[2]</value>
      <webElementGuid>3f61573a-fce8-451d-90a4-def1d39f687b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[3]/div/input[2]</value>
      <webElementGuid>702aece6-3bab-44e1-a7d9-53f61a141e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_ZAKAT_Save']</value>
      <webElementGuid>92257d2a-5ce2-4ed8-b9c5-00c1e2e1f9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
