<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AgentNameEn</name>
   <tag></tag>
   <elementGuidId>b944a88b-fdea-40d1-be6a-ce2ca8b174e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAgentNameEn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtAgentNameEn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84908192-9d3e-4047-ba12-d790c0126043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ecd0acf8-8ff3-4f1c-b6a7-30eaf9d262c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be2bf9a7-e773-45b4-9419-1a5421c1aba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم الوكيل عربى  مطلوب</value>
      <webElementGuid>9343541b-bc2b-4473-bea9-04f85ca3dbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAgentNameEn</value>
      <webElementGuid>af145351-242f-4cce-bb1c-4acd11e0219f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>11819b69-a3e7-49bc-85cc-9308836577f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AgentNameEn</value>
      <webElementGuid>4dd3f538-b799-4387-8691-dca766171d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9 ]+$</value>
      <webElementGuid>9f637e24-ea7a-4f37-a394-1ce562753b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الوكيل عربى </value>
      <webElementGuid>34f8b8da-a430-42c5-9224-b03bf251ce69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc1990c1-5e8a-46c5-853c-708bb0fa3fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAgentNameEn&quot;)</value>
      <webElementGuid>39cf3a76-ffe3-4fad-b602-627a089a88d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAgentNameEn']</value>
      <webElementGuid>9b8dc33e-051d-4b43-b2eb-7dd4b2925309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddAgentForm']/div/div/div[2]/input</value>
      <webElementGuid>71609683-908d-4285-a5fb-d3d4f215d789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div/div[2]/input</value>
      <webElementGuid>72e34976-b861-45ac-8078-58320f342209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtAgentNameEn' and @name = 'AgentNameEn' and @placeholder = 'اسم الوكيل عربى ' and @type = 'text']</value>
      <webElementGuid>11d6de10-229e-4f57-a870-f7560084c8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
