<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CompanyHierarchy_ParentCompanyName</name>
   <tag></tag>
   <elementGuidId>29b7aa11-7743-4c46-88f6-3bb3ea50f2ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCompanyHierarchy_ParentCompanyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCompanyHierarchy_ParentCompanyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adf71b77-af6e-4577-b818-bdb60d0689ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0ca5ce42-7b38-459c-9ef8-a5d574c108ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCompanyHierarchy_ParentCompanyName</value>
      <webElementGuid>005d60d3-2bed-4107-ac87-4f4a49ad4ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1fd5aa8d-c958-4f46-a302-c89fb87765f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyHierarchy_ParentCompanyName</value>
      <webElementGuid>bc1f6062-b6ce-4a12-973e-9ffa192df90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الشركة الام</value>
      <webElementGuid>49551cf3-537a-478b-8b13-7ca26446d3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d5b584f4-ffcd-4b5e-8812-0901a2229be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8a709dd-2ced-42b9-b870-fea117a9002d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCompanyHierarchy_ParentCompanyName&quot;)</value>
      <webElementGuid>f40563f7-ac82-4aa2-888d-30fef4038aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCompanyHierarchy_ParentCompanyName']</value>
      <webElementGuid>d64d9fef-5cec-4235-bbf3-7070b9f9de5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCompanyHierarchyDetails']/div/div/div/input</value>
      <webElementGuid>3b73ccf0-516e-4880-a4af-6f66f52c76b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>fa149445-29d3-43b3-8f48-162c235a6936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCompanyHierarchy_ParentCompanyName' and @name = 'CompanyHierarchy_ParentCompanyName' and @placeholder = 'اسم الشركة الام' and @type = 'text']</value>
      <webElementGuid>263ba2f7-0c6e-4359-8863-cedc86501586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
