<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_SAGIA_Save</name>
   <tag></tag>
   <elementGuidId>86cd6001-2971-4a48-8d1b-bc993e2ad030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_SAGIA_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_SAGIA_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>711e280a-9e63-4521-b085-fbfe1d9d7635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f12f29f4-19c9-4074-9c3f-122a7648f889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>1fe54a98-fb35-4cc9-9371-e8734784d933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_SAGIA_Save</value>
      <webElementGuid>14291d50-6596-4628-a91e-ee5ccf2d893c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>bf9d20be-6a2d-4a73-9559-b3804cbfef3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_SAGIA_Save&quot;)</value>
      <webElementGuid>9e1c82ac-509e-4c05-a04c-ddc063c2f3cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_SAGIA_Save']</value>
      <webElementGuid>bc064874-f0df-43fc-98ad-c983b6682dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_SAGIA_form']/div[3]/div/input[2]</value>
      <webElementGuid>49006e81-9a9d-4248-b289-624814116f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/form/div[3]/div/input[2]</value>
      <webElementGuid>c2242307-50d4-4711-824b-b23563cc9e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_SAGIA_Save']</value>
      <webElementGuid>a26b811b-e28e-4326-9dfc-fdec96b974c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
