<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ContactInformationName</name>
   <tag></tag>
   <elementGuidId>99f18f88-2b91-49e0-97ac-ab4aa8e8329d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtContactInformationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtContactInformationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94cc67a0-9958-4b46-b2b9-58727b835f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca71ff6b-c0c7-4ad9-8d52-475a8a823cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a0cbc2c-1426-4dbc-a2a4-00ec0f904249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص إنجليزي صحيح</value>
      <webElementGuid>b87bf322-8d54-4f21-a370-ca6c5becb9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9 ]+$</value>
      <webElementGuid>d1c1b8aa-7cbc-49f6-bbfe-93ae0be418be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم باللغة الإنجليزية مطلوب</value>
      <webElementGuid>b4412ea9-d8b9-480b-8085-24b5f58e90cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtContactInformationName</value>
      <webElementGuid>84335f68-30af-4933-b48c-e317b5ec6d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>4e645327-985e-4893-855b-bb0a4f22286a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactInformationName</value>
      <webElementGuid>e5eac504-2916-4e55-b507-73490ba7b78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم باللغة الإنجليزية</value>
      <webElementGuid>bfd3e7b4-9cf5-4007-b6f8-2c5694086012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3caa5d39-10c9-48b9-80c9-3bb7185cc8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtContactInformationName&quot;)</value>
      <webElementGuid>38ae4f94-6397-4765-8f83-d3b3367d9a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtContactInformationName']</value>
      <webElementGuid>7f5e2e11-5b11-4de7-ad70-3019933336f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddContactInformationForm']/div/div/div/input</value>
      <webElementGuid>eb4b6a78-66f2-4ffe-a4c9-4cbbba32a737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div/div/input</value>
      <webElementGuid>00e36c55-167b-4604-8880-333a639697ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtContactInformationName' and @name = 'ContactInformationName' and @placeholder = 'اسم باللغة الإنجليزية' and @type = 'text']</value>
      <webElementGuid>6ec56144-0fdb-4847-8e8c-80614c99cde2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
