<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__expdatepicker</name>
   <tag></tag>
   <elementGuidId>22b36594-6310-43f6-bf33-526eb7b97a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-picker-wrap.k-state-default.k-state-focused > input[name=&quot;expdatepicker&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='k-state-selected']//input[@name='expdatepicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fd1e641-0603-42a1-911a-2f63008d280a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97b5b15c-102e-417b-b5a2-8138c8cb797f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expdatepicker k-input</value>
      <webElementGuid>160e0b6c-b222-4198-919a-0342fdcd96f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>javascript:return false;</value>
      <webElementGuid>0a961fe1-3a4f-4036-89a0-8f4c607444fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expdatepicker</value>
      <webElementGuid>dff0d180-d7a8-4559-b8b0-9d56f1db75b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>8ebd2055-6a92-4f43-b588-14fc459804fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>fecffdcc-d38c-4a95-b812-ce19de8d4219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b3ef9088-9d63-4f47-8e9c-726b44e1d4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1bca3dd-8365-4e33-8bc8-ee86a3bf618f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/span[@class=&quot;k-widget k-datepicker k-header expdatepicker&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-focused&quot;]/input[@class=&quot;expdatepicker k-input&quot;]</value>
      <webElementGuid>059ea4d0-6a91-463d-b593-aaadd609c049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='expdatepicker'])[2]</value>
      <webElementGuid>78b9d439-01ea-4810-9958-1ee66f40772a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']/div/span/span/input</value>
      <webElementGuid>f5db8d1c-b3cf-49b7-8787-27dd1238f05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/span/span/input</value>
      <webElementGuid>6b08caa7-9065-40fe-9520-b0886e7547a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'expdatepicker']</value>
      <webElementGuid>8a93f3e8-7b96-4fc1-863e-842a2c0b84b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
