<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ManagementDetails</name>
   <tag></tag>
   <elementGuidId>c870753b-4365-4f49-aea0-510fa041f0fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chkManagementDetails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chkManagementDetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14bbcc2b-1311-4ff7-ae95-da2e49059220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>70ad361d-d6ff-46d8-9bf1-ac46d7397825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ManagementDetails</value>
      <webElementGuid>abd68509-7b12-4b12-90df-ca877f925a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkManagementDetails</value>
      <webElementGuid>86491f20-60d6-417e-944c-1dcdcd542058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chkManagementDetails</value>
      <webElementGuid>6a49b7ad-4a3e-4f37-942b-63643d0ae063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkboxkManagementDetailsChange(this);</value>
      <webElementGuid>abd47789-e829-4f2c-9506-e8c020677e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chkManagementDetails&quot;)</value>
      <webElementGuid>377177ee-17bf-4b24-874f-04b62a3cd504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chkManagementDetails']</value>
      <webElementGuid>c858cad7-5080-471e-b0e3-426cb1006285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetails']/div/div/div/div[4]/div[2]/input</value>
      <webElementGuid>8cea0aef-9956-4682-9d3d-b3819bd4b075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]/div[2]/input</value>
      <webElementGuid>529bbd4f-b0a3-455e-bec8-3c70b44a74c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'ManagementDetails' and @id = 'chkManagementDetails']</value>
      <webElementGuid>067de917-089d-4e58-b280-f4975b38f38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
