<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_CompanySize_Save</name>
   <tag></tag>
   <elementGuidId>dd7a1a28-5aa9-42d6-89d2-38b523e4f669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_CompanySize_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_CompanySize_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abc4807e-ce71-4235-8709-573d8968af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21c99d5f-2fee-4649-9347-1c0fbc21cdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>d159273a-72b6-4dc7-8f6f-363165aef2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_CompanySize_Save</value>
      <webElementGuid>3d1e20a9-e642-41ef-aec4-8b1a329ed29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>c07613f7-ca8f-4b5a-96b2-a698565e88c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_CompanySize_Save&quot;)</value>
      <webElementGuid>cc3116c4-60af-410c-aaec-4a9522b22118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_CompanySize_Save']</value>
      <webElementGuid>30688f01-2bcc-4f15-91aa-c4066bc0edb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_CompanySize_form']/div[3]/div/input[2]</value>
      <webElementGuid>501e54da-8596-427c-8745-1931f4d35a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/form/div[3]/div/input[2]</value>
      <webElementGuid>b6b4703e-b4b2-4db4-9bd7-b7253ef4a144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_CompanySize_Save']</value>
      <webElementGuid>208fd100-b9e1-4da1-ae33-9386b1f9a30c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
