<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ContactInformationNameAr</name>
   <tag></tag>
   <elementGuidId>f5e229c9-2dc4-4764-8a56-c7f98e89966a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtContactInformationNameAr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtContactInformationNameAr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52ee1b50-0d64-4f38-886b-afe8d5bd2bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b49bc60b-3763-483a-9d87-db071e2b592b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5dad29e7-8615-4819-8aa1-074968926aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص عربي صحيح</value>
      <webElementGuid>ea4b8fb9-bb06-4e26-9597-57de12fc6061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[\u0621-\u064A 0-9]+$</value>
      <webElementGuid>7001ded8-36db-4acd-809b-de1e8926f1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم باللغة العربية مطلوب</value>
      <webElementGuid>e1844e6b-26d4-4d9a-8a6b-b1819eefa7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtContactInformationNameAr</value>
      <webElementGuid>97db46bf-b85e-4ebc-8bd6-6f0997c34f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2e7a98e3-bc7d-46fe-b111-5ec5682964f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactInformationNameAr</value>
      <webElementGuid>8ddf8210-ceff-4aba-8ac5-7c6af106259d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم باللغة العربية</value>
      <webElementGuid>199f2fbb-636d-4022-a5ff-22d99cf05a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e21e8ba8-7bd1-447e-83e6-bbc475e05e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtContactInformationNameAr&quot;)</value>
      <webElementGuid>1148dfa8-d44c-4dab-b270-2c99c2804e90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtContactInformationNameAr']</value>
      <webElementGuid>e9d79924-1c94-425a-8580-5bb952816a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddContactInformationForm']/div/div/div[2]/input</value>
      <webElementGuid>82f40742-955c-4242-b24c-b5312ff2d3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div/div[2]/input</value>
      <webElementGuid>65dcae8f-3722-4d23-a0da-61e89f6a5339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtContactInformationNameAr' and @name = 'ContactInformationNameAr' and @placeholder = 'اسم باللغة العربية' and @type = 'text']</value>
      <webElementGuid>bd724429-9dee-49d0-b32b-f658ecbd64bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
