<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AgentNameAr</name>
   <tag></tag>
   <elementGuidId>ac1ecd87-cdbf-4dea-9f24-127e0ead54ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAgentNameAr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtAgentNameAr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>401df01b-54f4-4699-8230-89560ef547db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16e02fa7-255a-448d-8830-f005c46e5129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9abe368a-dbfc-458d-9b3f-c8b7df3e823d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم الوكيل عربى  مطلوب</value>
      <webElementGuid>d8b60931-75f6-44d8-8ab4-5ad655d9dc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAgentNameAr</value>
      <webElementGuid>7989562b-0d81-49e3-9983-f73fc7216bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7918054e-08a0-45e7-b918-ea08fe6530d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AgentNameAr</value>
      <webElementGuid>46469615-a1ef-45f5-945a-6337500437be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\u0621-\u064A 0-9]+$</value>
      <webElementGuid>b49dc07d-4f84-4edb-83e8-3504215da2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الوكيل عربى </value>
      <webElementGuid>c9549da6-d5b1-431b-af1a-6a684f6c1dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec400d58-4446-44cc-8684-9634c383ca95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAgentNameAr&quot;)</value>
      <webElementGuid>525eda61-993b-486f-b2fb-ebc5f58fda43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAgentNameAr']</value>
      <webElementGuid>665b1276-19f4-48a4-b1b8-ed0f33e78ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddAgentForm']/div/div/div/input</value>
      <webElementGuid>1cbb4306-5616-4977-91bf-30ae11a5e9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div/div/input</value>
      <webElementGuid>7b3bf4a5-3988-48d6-87ff-7ba639cc7a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtAgentNameAr' and @name = 'AgentNameAr' and @placeholder = 'اسم الوكيل عربى ' and @type = 'text']</value>
      <webElementGuid>d09b7d82-9903-47d5-b74b-8cf41f0e3921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
