<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ContactInformationJobTitleAr</name>
   <tag></tag>
   <elementGuidId>81443384-76f6-4ed6-a0c7-0b9aaef2b8c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtContactInformationJobTitleAr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtContactInformationJobTitleAr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e57ac22b-fdb6-46ee-902a-b216b7ca0599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control k-valid</value>
      <webElementGuid>2eea3c5a-1977-4ac8-ba62-eed95f64941a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b4b950e-c2d9-4aec-a187-a1faeefa8d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص عربي صحيح</value>
      <webElementGuid>c1538bd1-64ea-4fd3-9d32-92722d296251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[\u0621-\u064A 0-9]+$</value>
      <webElementGuid>4aaf21da-cbab-42b9-80a2-b646f470ba4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل المسمى الوظيفي باللغة العربية مطلوب</value>
      <webElementGuid>5d4ddd0f-9f03-4b79-b57d-e1265f288782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtContactInformationJobTitleAr</value>
      <webElementGuid>a75e5f30-1ce7-4874-9679-2c9adf5e713d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b0a05fbb-248d-4fe0-9e95-4740505100cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactInformationJobTitleAr</value>
      <webElementGuid>50b12241-b6c8-48a5-bba5-30aa81280896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>المسمى الوظيفي باللغة العربية</value>
      <webElementGuid>ccba7d2c-ea42-4b5c-913a-0c58d434713a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6112d168-eae0-45e6-97c3-c835bc398bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtContactInformationJobTitleAr&quot;)</value>
      <webElementGuid>d7951e57-05ae-4123-9107-fabeac82c016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtContactInformationJobTitleAr']</value>
      <webElementGuid>dc0d283b-ac84-4f4f-8119-1d69f6b687f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddContactInformationForm']/div/div[3]/div[2]/input</value>
      <webElementGuid>880dd733-281c-495a-936d-6a0d6dd677ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div[3]/div[2]/input</value>
      <webElementGuid>be79d78a-e422-4db2-9787-6eb203638b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtContactInformationJobTitleAr' and @name = 'ContactInformationJobTitleAr' and @placeholder = 'المسمى الوظيفي باللغة العربية' and @type = 'text']</value>
      <webElementGuid>5c387062-4de9-463b-a160-864169e482e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
