<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CompanyMainEmailAddress</name>
   <tag></tag>
   <elementGuidId>afb4feec-a13b-4694-97d3-fa95e21d299b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCompanyMainEmailAddress</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txtCompanyMainEmailAddress' and @name = 'CompanyMainEmailAddress' and @placeholder = 'البريد الالكتروني للمنشآة' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCompanyMainEmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90ad384b-259e-4014-aab1-57634dc1bf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>601ea5a6-0ea6-4d5d-b3df-591797e1ce21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5925b91-8ff1-45b4-9ee0-3a95e397c033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>من فضلك أدخل بريد أليكترونى صحيح</value>
      <webElementGuid>40eb7954-152b-404d-8f8b-f33308cf31df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z]{2,17})$</value>
      <webElementGuid>9568af56-5b1a-444b-b05e-2eb1e0a22620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCompanyMainEmailAddress</value>
      <webElementGuid>5f4afe4e-82b7-416d-b74f-55979bcd9b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e1f2b33f-b838-49d2-9cee-d2c39199d42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyMainEmailAddress</value>
      <webElementGuid>055cd8e7-f2c7-4849-b4c3-8765551a9e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>البريد الالكتروني للمنشآة</value>
      <webElementGuid>cd87a545-dd35-4c77-9259-b32695a4d3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b393a565-d662-4609-86fd-468d9220fa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5387622a-502f-4774-88ff-67c96efbad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCompanyMainEmailAddress&quot;)</value>
      <webElementGuid>ecccf03f-246a-4799-a2a0-dc11a636fdfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCompanyMainEmailAddress']</value>
      <webElementGuid>872e135a-8a14-4126-9086-ebb8ee7399bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactInfoDiv']/div/div[2]/div[2]/input</value>
      <webElementGuid>af8a2333-b5d0-4746-aba8-d907b9f10b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/input</value>
      <webElementGuid>ed17810a-1563-43c3-b1a6-34bfc5654e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCompanyMainEmailAddress' and @name = 'CompanyMainEmailAddress' and @placeholder = 'البريد الالكتروني للمنشآة' and @type = 'text']</value>
      <webElementGuid>7804b0d0-51d4-405d-911c-e81ef1101b2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
