<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OwnershipDetailsEmail</name>
   <tag></tag>
   <elementGuidId>fa0c3079-0482-471b-b358-5246211570ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnershipDetailsEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnershipDetailsEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6200a7f9-e8d1-4934-bc10-5fae8b105ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f2315289-90da-4ab8-a0f4-ae39a7ec5406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ad4f279-e563-451b-ac8f-453d820fbb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Email must be a string with a maximum length of 255.</value>
      <webElementGuid>175d5825-4579-427a-9cf2-d5814a3d9558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>8b1381e5-9bd3-4c64-9243-b10f155ff2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>من فضلك أدخل بريد أليكترونى صحيح</value>
      <webElementGuid>952bc456-5d7a-4ccd-8b24-f7beed616acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z]{2,17})$</value>
      <webElementGuid>3142d66c-3bea-4841-9e26-8cd407a19b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل البريد الالكتروني مطلوب</value>
      <webElementGuid>0532d06e-ff85-4661-bada-31223329a488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnershipDetailsEmail</value>
      <webElementGuid>aeeb12cf-4282-4be9-8dc5-ae821f328672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a229eaea-bbde-4700-9f3e-7adf3b31dfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OwnershipDetailsEmail</value>
      <webElementGuid>2e8656fb-4a0c-4061-adf0-305699b14e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>البريد الالكتروني</value>
      <webElementGuid>13a64aa4-8e0d-4af6-ae37-5e5fa2252eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9abbcd97-c425-4694-bcb4-3c7aa59adae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnershipDetailsEmail&quot;)</value>
      <webElementGuid>4785ea80-8546-4547-8a5a-ed14ce7aec82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnershipDetailsEmail']</value>
      <webElementGuid>f739a4b4-90fb-443c-a4fa-d5526cfe850e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetailsDiv']/div/div[2]/div/input</value>
      <webElementGuid>413440af-b1cd-4534-98ae-007f66c4b4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/input</value>
      <webElementGuid>97a86b29-0c5d-4389-93cb-b81935970fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnershipDetailsEmail' and @name = 'OwnershipDetailsEmail' and @placeholder = 'البريد الالكتروني' and @type = 'text']</value>
      <webElementGuid>bfbda15b-33d9-4572-a99c-426328401c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
