<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ContactInformationJobTitle</name>
   <tag></tag>
   <elementGuidId>87ead837-8241-45a6-ba3e-f0fa6e345420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtContactInformationJobTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtContactInformationJobTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5202c9be-e461-400a-b337-3fba9d843e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control k-valid</value>
      <webElementGuid>ba5e0c8a-2516-4af0-bf59-a2e671c0e089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f952e1f-b6b8-4e2f-9905-e3b7c69c4b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص إنجليزي صحيح</value>
      <webElementGuid>58847fbd-e691-48b0-bdd2-fe416a19da5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9 ]+$</value>
      <webElementGuid>1e30f122-8dd4-4960-af61-65714ae6a969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل المسمى الوظيفي باللغة الإنجليزية مطلوب</value>
      <webElementGuid>321f3c42-6d58-45d1-801e-c4429f117e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtContactInformationJobTitle</value>
      <webElementGuid>9c7007e7-0fb7-4655-a7a5-629a3a410752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ec42154f-788d-45c0-bb97-eabb80b8ecb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactInformationJobTitle</value>
      <webElementGuid>61d687bd-152f-49f4-aef9-899c333736e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>المسمى الوظيفي باللغة الإنجليزية</value>
      <webElementGuid>d0d1c419-ee44-4a1f-ab6f-dbf739e1da89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffe5eb06-e02a-4995-9862-10f2a861270e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtContactInformationJobTitle&quot;)</value>
      <webElementGuid>971f351e-631d-45f8-8dc4-88b450891da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtContactInformationJobTitle']</value>
      <webElementGuid>8d003576-af06-4f98-b60a-5405b1424fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddContactInformationForm']/div/div[3]/div/input</value>
      <webElementGuid>23026fac-d30b-4a8c-b76f-4c29e9bb09ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div[3]/div/input</value>
      <webElementGuid>bef2bdd3-b512-4119-87fa-3d43fc0b4e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtContactInformationJobTitle' and @name = 'ContactInformationJobTitle' and @placeholder = 'المسمى الوظيفي باللغة الإنجليزية' and @type = 'text']</value>
      <webElementGuid>85751c38-32f5-470f-b51d-5c14852a167f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
