<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnSubmit_Insurance</name>
   <tag></tag>
   <elementGuidId>2404123b-2a96-4175-bf94-27461afca2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSubmit_Insurance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSubmit_Insurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc7dcb91-3e04-4bd3-9b7e-cc793aa96d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b26024a4-5a14-4c0c-8be6-691658d24b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>9b35e314-51a5-432d-b9bb-b545bfab3867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSubmit_Insurance</value>
      <webElementGuid>058c86f1-b3e5-42d1-a553-105ad50b8668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>1ba90b0d-0b9d-4769-891a-cac0010ee46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSubmit_Insurance&quot;)</value>
      <webElementGuid>2964ffa4-d9c6-4198-a571-9fe2916c2d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSubmit_Insurance']</value>
      <webElementGuid>567dacdc-c8ef-46be-918d-f18fc5519d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='InsuranceTab']/div/div/div[3]/input[2]</value>
      <webElementGuid>3cf56529-d34f-4735-8740-605fc077b375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div[3]/input[2]</value>
      <webElementGuid>2083a17d-455b-4efd-903c-62c24b5f787a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSubmit_Insurance']</value>
      <webElementGuid>e7182048-e6b8-43d4-a702-ee21abdf9dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
