<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Website</name>
   <tag></tag>
   <elementGuidId>68bbfdfd-6e00-4e99-b77c-aa54377228c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtWebsite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtWebsite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1625a552-5c21-4241-b32a-40895b26bf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d65faf7-3e56-43b7-b7ec-407761be7531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34dab679-55e1-4b8c-b3c8-dc62e1f1b85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>يرجى إدخال عنوان URL صحيح</value>
      <webElementGuid>0eb358f7-09da-4357-a990-413672235047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&amp;'\(\)\*\+,;=.]+$</value>
      <webElementGuid>7d8646fc-1d55-42bc-b863-bd2088b6ec7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtWebsite</value>
      <webElementGuid>2e7fc06d-3737-4a09-a3ee-b2fa893a4019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7a1ad1f5-801c-490e-b0ae-2c1b189367ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>89e83a15-d493-48d4-89f0-7de67e5d1105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الموقع الالكتروني للمنشأة</value>
      <webElementGuid>5bb91bb9-c165-4b66-88b7-3faec8171db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c84c764-cba9-457c-aa35-9694ea59ab5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c503d9f1-b855-46e6-bb08-b64648d97695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtWebsite&quot;)</value>
      <webElementGuid>24a2b2f9-6286-4512-8f81-829a0a1c317e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtWebsite']</value>
      <webElementGuid>5d4e6d5a-371a-44f2-a8f2-5f6cbdf2d961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactInfoDiv']/div/div[2]/div/input</value>
      <webElementGuid>d1c6a810-5620-4bc3-b765-2fbe46893983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/div/div/div[2]/div/input</value>
      <webElementGuid>dca0d868-8e3a-490a-a8c3-a4c5542919e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtWebsite' and @name = 'Website' and @placeholder = 'الموقع الالكتروني للمنشأة' and @type = 'text']</value>
      <webElementGuid>60e22a5d-9832-4312-859e-ab00087f7a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
