<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtfilterAgent</name>
   <tag></tag>
   <elementGuidId>94663816-a432-40d2-92a0-84b5dedb887d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtfilterAgent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtfilterAgent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58852577-0af0-4304-921b-89779eca42fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfilterAgent</value>
      <webElementGuid>ac170ee7-0fcf-4773-9745-f4222298cea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner k-input k-textbox k-input-solid k-input-md k-rounded-md</value>
      <webElementGuid>4c3e4b4b-f209-4baa-8a81-42e7fd9e6b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfilterAgent&quot;)</value>
      <webElementGuid>8382909f-32bd-46b1-915b-55a161014f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtfilterAgent']</value>
      <webElementGuid>528745e0-93a0-4e32-975b-3dedf127faa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAgent']/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>ac1a1680-8f25-4b33-90a1-3a1290d9c88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>857125d4-290f-4b8e-a7a2-c1484ca49bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtfilterAgent']</value>
      <webElementGuid>1e9bac90-8941-4e0c-896d-3b0c042efeba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
