<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__District</name>
   <tag></tag>
   <elementGuidId>e3bf1ca6-d593-4a91-b49b-1437892577c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDistrict</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDistrict']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36879fbc-a3e2-4f84-aac1-112bedc55691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control k-invalid</value>
      <webElementGuid>4d6263e0-fe21-4865-9c0b-f71a6037d39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d3d3159-c956-4aae-94dc-763adaff05ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص إنجليزي صحيح</value>
      <webElementGuid>5ab03aea-d073-42b4-9c8e-7643a6141319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9 ]+$</value>
      <webElementGuid>04ef6c7f-a791-4b10-95c2-e2da473f5120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الحي باللغة الإنجليزية مطلوب</value>
      <webElementGuid>596c0009-1bdd-4550-bb6c-31052ee1b534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDistrict</value>
      <webElementGuid>11274ca3-af20-4155-ab9a-079314521bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7dd8fd10-4e25-459e-aa57-aa1073d86178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>District</value>
      <webElementGuid>8bffa474-193e-4c92-9895-cd54793caf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الحي باللغة الإنجليزية</value>
      <webElementGuid>ea1cd850-db31-4cbc-aea2-9be5fd8dfc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c6bab4f-fc5b-4b65-bd2e-de1a54fcab49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Oraifi Industrial Dist.</value>
      <webElementGuid>d90e0410-84cc-4315-9ea1-79cdfe922890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d68fc2b-4d7a-40b6-8a81-d5d62b7868e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDistrict&quot;)</value>
      <webElementGuid>07bba3de-4781-4c67-b431-0db356fff260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDistrict']</value>
      <webElementGuid>f7ac6d4b-9e0e-4db6-b5ff-797deeb39f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header2Div']/div[3]/div/input</value>
      <webElementGuid>2f986914-5dec-4324-b026-6f2adb301608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div[3]/div/input</value>
      <webElementGuid>ba18bc91-55ea-4c41-bb4e-f3ce7c554d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtDistrict' and @name = 'District' and @placeholder = 'الحي باللغة الإنجليزية' and @type = 'text']</value>
      <webElementGuid>0fd41d59-dc8a-4a1c-9a6b-134c9a612980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
