<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OwnershipDetailsName</name>
   <tag></tag>
   <elementGuidId>15998068-1fbc-4e37-a3a9-efe38b348a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnershipDetailsName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnershipDetailsName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9806df6-8e3c-4497-93fa-1f0aeceb66e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d15d1b2-4caf-4cd7-bcac-6a370730b222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>496411cc-cb73-4766-952e-b5044473a29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الاسم مطلوب</value>
      <webElementGuid>6ddded1d-d89c-4dc7-903a-324786f0b9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnershipDetailsName</value>
      <webElementGuid>86a212da-5b6d-4d0f-80be-e65530e2efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d4c25aed-5bd7-486d-8cba-14c7fba2d4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OwnershipDetailsName</value>
      <webElementGuid>6f74e9e6-01c8-4ced-a630-bce9760f054d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الاسم</value>
      <webElementGuid>a6930473-338b-47d0-9d36-77f35f7fa0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3bb489c-594f-4974-babe-0cffa5eecc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnershipDetailsName&quot;)</value>
      <webElementGuid>0a66a918-97f7-4d42-8aa3-9a3b1e766f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnershipDetailsName']</value>
      <webElementGuid>3d5ed7cc-968a-4ba6-b9da-f54fa5e4d4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetailsDiv']/div/div/div/input</value>
      <webElementGuid>c186f568-de5c-4481-bf36-11dd00755c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>e762e0f7-ac4f-457a-8cb6-797f3e544487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnershipDetailsName' and @name = 'OwnershipDetailsName' and @placeholder = 'الاسم' and @type = 'text']</value>
      <webElementGuid>45ea127a-6d5e-428c-94e8-6e0dae983010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
