<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ContactInformationEmail</name>
   <tag></tag>
   <elementGuidId>8f43e7e2-21f9-41ff-905f-4ad7f81f9dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtContactInformationEmail</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txtContactInformationEmail' and @name = 'ContactInformationEmail' and @placeholder = 'البريد الإلكتروني' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtContactInformationEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a09aeb5f-00f5-467b-90f7-62a3e94c75e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9089b6e4-3be8-4c38-b8e9-b509acc98941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6496841-605b-450d-a042-d913eebc2d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Email must be a string with a maximum length of 255.</value>
      <webElementGuid>c0ebda56-4bc2-44e3-80f8-28272142a2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>749ca6ac-5ddf-427b-a367-2318c6ea071f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>من فضلك أدخل بريد أليكترونى صحيح</value>
      <webElementGuid>eecb3d91-e9ab-4981-ad19-30eb203d04aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z]{2,17})$</value>
      <webElementGuid>75730cca-f286-40e1-810c-dfdc1aea9cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل البريد الإلكتروني مطلوب</value>
      <webElementGuid>fc013497-e19f-4108-aa31-2f243681b1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtContactInformationEmail</value>
      <webElementGuid>2391d596-d1e9-48e5-afd0-14c548d4ab05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8bd73b55-aa4c-4b34-aa5d-1faad177e944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactInformationEmail</value>
      <webElementGuid>b8a208b6-10bb-4424-84ba-829154c97320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>البريد الإلكتروني</value>
      <webElementGuid>290a0073-d512-4c99-8700-3f548c0a267e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57d0d829-667b-415d-8ba6-c634064e6fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtContactInformationEmail&quot;)</value>
      <webElementGuid>973fa9cc-5840-4bad-8eba-2b5be4bf0d6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtContactInformationEmail']</value>
      <webElementGuid>97175f0e-571e-434f-bf1f-bf33316cbc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddContactInformationForm']/div/div[5]/div[2]/input</value>
      <webElementGuid>ccbd83bc-8450-40e4-8ea1-4b5d28ee97ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div[5]/div[2]/input</value>
      <webElementGuid>4bee7009-f52e-4d48-89ae-4c7a26393d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtContactInformationEmail' and @name = 'ContactInformationEmail' and @placeholder = 'البريد الإلكتروني' and @type = 'text']</value>
      <webElementGuid>38e3fd23-7072-49de-a82c-04517aead9a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
