<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OwnershipDetailsPhone</name>
   <tag></tag>
   <elementGuidId>eeba11db-6773-48d3-8b25-2aa12f630c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnershipDetailsPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnershipDetailsPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15ac887a-6fdb-4e56-886f-ea3a0275c5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control phoneNumber</value>
      <webElementGuid>198a1334-39a9-4049-85d7-2edab8ec9049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ede1dd9-f2c8-4b57-96ea-f25ff0b1839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل رقم الهاتف مطلوب</value>
      <webElementGuid>f9c9406e-db1e-4880-becb-53ecddd82d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnershipDetailsPhone</value>
      <webElementGuid>eb318c6f-0411-47ba-8466-b4f07805719a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>477dba50-098b-46b4-80c1-f1eac121ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OwnershipDetailsPhone</value>
      <webElementGuid>8734b965-1163-4f83-b353-767502fc6bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم الهاتف</value>
      <webElementGuid>7b4d591f-0758-45e2-a190-589d21337663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49fd2f90-147f-43c1-adb7-7075984a176d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnershipDetailsPhone&quot;)</value>
      <webElementGuid>b8ef87c8-3265-49ac-adf8-5e9fd0bf00f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnershipDetailsPhone']</value>
      <webElementGuid>d6bbcdb2-8735-4776-aa6e-0ee04f05964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetailsDiv']/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>007c7685-5f2a-4475-abeb-e066f24d075f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>248dfc72-d9e8-43a2-8857-79e61b3847fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnershipDetailsPhone' and @name = 'OwnershipDetailsPhone' and @placeholder = 'رقم الهاتف' and @type = 'text']</value>
      <webElementGuid>9cbe6bfe-5dbb-4d9d-a5c2-e9e7b1a8e9cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
