<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ValueofCover</name>
   <tag></tag>
   <elementGuidId>09b5ada5-c62b-4555-ab92-b0577d756f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtValueofCover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtValueofCover']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dfcf09f-0ea6-45dc-b416-4f49a8ec61ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>a337c637-b9fe-47cf-acca-131f30301086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValueofCover</value>
      <webElementGuid>48fdab85-f310-401d-a1aa-3c6bbfcb0170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>eeb67cf1-8b6f-4624-ba1f-b9d176ce21a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValueofCover</value>
      <webElementGuid>fe68670c-f756-4586-88ac-38fdb38ff51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>قيمة التغطية</value>
      <webElementGuid>609add49-dcfb-4f80-ab24-f42fb2518abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>7f4248e7-681b-4428-bd85-a7fa08c10129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>قيمة التغطية</value>
      <webElementGuid>46a536c6-65ce-45a1-9240-30fa638a3547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62af5e25-052c-47d1-9940-80c2cfb2007b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValueofCover&quot;)</value>
      <webElementGuid>0e2f7a18-4590-4be4-a99f-0ed9eb654242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtValueofCover']</value>
      <webElementGuid>263a14c3-befa-467e-8f09-e402014377b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormInsurance']/div[3]/div[2]/input</value>
      <webElementGuid>25e61ab7-d605-4e5f-b72e-a8913a4e715f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div[2]/input</value>
      <webElementGuid>b1d4e452-6c89-4d2c-8846-73c238f53951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtValueofCover' and @name = 'ValueofCover' and @placeholder = 'قيمة التغطية' and @title = 'قيمة التغطية' and @type = 'text']</value>
      <webElementGuid>a56a1c2c-195b-4bae-92f0-31f12c00db5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
