<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OwnershipDetailsPosition</name>
   <tag></tag>
   <elementGuidId>c9e09656-03b1-4828-b6cf-064a7434d9eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnershipDetailsPosition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnershipDetailsPosition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dfdf4c9-8984-4b8a-8022-8d0f786b6367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1598233a-5cd3-4ffd-93e7-a9cdc15a15ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c65a4f62-9541-49ad-a5a4-08cc4ee8e42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل المسمى الوظيفي مطلوب</value>
      <webElementGuid>7aeeec6f-2ca2-4dca-89f2-e473b1d99198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnershipDetailsPosition</value>
      <webElementGuid>498f3209-d443-4a1b-b678-e1af798fe571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0cff2496-3ca6-4f1e-bdc0-6a39279fbf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OwnershipDetailsPosition</value>
      <webElementGuid>0bd98301-48df-4cbb-ab04-721b64ed517f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>المسمى الوظيفي</value>
      <webElementGuid>c90742ff-cc60-4188-bd82-8d8ba82b6288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f838544-eb17-4cb6-a6b1-2d6f741cfac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnershipDetailsPosition&quot;)</value>
      <webElementGuid>76e6ffce-522a-4376-88d4-4be2fa3d8638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnershipDetailsPosition']</value>
      <webElementGuid>b6afa843-a645-4c16-b7e2-5b914e13593e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetailsDiv']/div/div/div[2]/input</value>
      <webElementGuid>8e9e164c-9166-4536-8052-ef5d198b7cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/input</value>
      <webElementGuid>29d1cfeb-e33e-47dc-ae06-83ae33649e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnershipDetailsPosition' and @name = 'OwnershipDetailsPosition' and @placeholder = 'المسمى الوظيفي' and @type = 'text']</value>
      <webElementGuid>39a202f3-2344-414e-8274-32c55ab2c599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
