<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__file</name>
   <tag></tag>
   <elementGuidId>cca9d726-e082-4e4b-a27c-419154fbf93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k-button.k-upload-button.k-state-focused > input[name=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='file']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/div[@class=&quot;k-widget k-upload k-header k-upload-sync k-upload-empty&quot;]/div[@class=&quot;k-button k-upload-button k-state-focused&quot;]/input[@class=&quot;fdUpload&quot;][count(. | //*[@type = 'file' and @name = 'file']) = count(//*[@type = 'file' and @name = 'file'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4e71611-07d1-4d2d-8d55-11ebe68681a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>15982fd7-09f5-4bbe-9cdd-383b1dc6e5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fdUpload</value>
      <webElementGuid>2021dd68-2224-4bcd-9715-6c0851e740ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1614ed14-5db7-4f0c-89d7-5de961b9f179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>f9528717-ad14-4251-961a-d247efd7fcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>8ca949fe-cf07-42de-b9bd-480020aa1eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1aac479d-4964-4420-a8ae-40b88355c559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/div[@class=&quot;k-widget k-upload k-header k-upload-sync k-upload-empty&quot;]/div[@class=&quot;k-button k-upload-button k-state-focused&quot;]/input[@class=&quot;fdUpload&quot;]</value>
      <webElementGuid>aa170608-9601-4e82-856d-3ae57ba065fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='file'])[2]</value>
      <webElementGuid>70bb11c4-b795-4bba-bf8c-78f223617935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']/div/div/div/input</value>
      <webElementGuid>febda3ed-a591-4f5b-89f6-065efed8f0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/div/div/div/input</value>
      <webElementGuid>35271a68-aa78-41c7-851f-70205e9eadd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'file']</value>
      <webElementGuid>a5bdc411-997f-41cc-991a-7261ef6e5d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
