<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ (1)</name>
   <tag></tag>
   <elementGuidId>8d61ccf8-7a92-4b93-9233-6d3a7f74820e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdSMEClassificationAgentActivity_active_cell > label.k-checkbox-label.k-no-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)/label[@class=&quot;k-checkbox-label k-no-text&quot;][count(. | //label[@class = 'k-checkbox-label k-no-text']) = count(//label[@class = 'k-checkbox-label k-no-text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d7d0d8ed-937b-43c7-8c4a-df82bcc4541f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox-label k-no-text</value>
      <webElementGuid>3862b3ac-2a15-48dc-af98-03a96c4f76f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>grdSMEClassificationAgentActivity8c7c3751-27d1-4fc8-90b0-a7c4fd5d6200</value>
      <webElementGuid>8f2c84b4-857e-45b8-901d-5a517f5185fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>3dd57550-9d14-4642-95be-efce820332c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)/label[@class=&quot;k-checkbox-label k-no-text&quot;]</value>
      <webElementGuid>a852bb23-a427-41f2-9a2d-ffebdb2c2692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']/label</value>
      <webElementGuid>fb0bb76b-10e0-4181-8df7-d46a8ba94224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ابحث باسم النشاط أو كود النشاط'])[2]/following::label[1]</value>
      <webElementGuid>e54bdbe4-ac2b-4d32-ad63-544344127435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[2]/following::label[2]</value>
      <webElementGuid>e55f76b9-7f82-4a61-bad2-8680ebecfa2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SME Activity ID'])[2]/preceding::label[1]</value>
      <webElementGuid>8f2c60ec-0b50-4776-839a-ef831d21c2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز النشاط'])[2]/preceding::label[1]</value>
      <webElementGuid>0b580672-a853-4e3f-ba13-69dcb41f1aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/table/thead/tr/th/label</value>
      <webElementGuid>9a11dc5b-183f-4749-ae80-d357d632ec12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '​' or . = '​')]</value>
      <webElementGuid>b4f6ad06-d827-4453-8d97-1149cec515a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
