<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>cabf27f4-ab8d-4828-8d1e-054212f90ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CompanyDetails_Header4Div']/div/div/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fcdc4e96-827c-4fc2-b8f6-6831100c65fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rdIsForeignInvestorComapnyNo</value>
      <webElementGuid>5e6733f8-80bf-4c14-84e6-5d2317acdc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding10-radio</value>
      <webElementGuid>30ab6b36-7d0d-43e0-b524-f9985ecd0b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>لا</value>
      <webElementGuid>5cfb1a43-850d-4e58-bf00-49c5517d9f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyDetails_Header4Div&quot;)/div[@class=&quot;row col-sm-12 col-lg-12 col-md-12 col-xs-12 form-group&quot;]/div[@class=&quot;col-md-8 col-lg-8 col-sm-12 col-xs-12 fl-right&quot;]/div[@class=&quot;col-sm-12 col-lg-12 col-md-12 col-xs-12 radio-toolbar&quot;]/label[@class=&quot;padding10-radio&quot;]</value>
      <webElementGuid>3504e4b3-f7a6-40c5-9e29-39562a15a314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header4Div']/div/div/div[2]/label[2]</value>
      <webElementGuid>11d06738-66a9-4bf4-a12e-5413df41b9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نعم فعلا'])[1]/following::label[1]</value>
      <webElementGuid>31babf37-602b-4a71-a365-5cb64f47f2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هل يوجد مستثمرين اجانب بالمنشأة؟'])[1]/following::label[2]</value>
      <webElementGuid>77d53f0d-e544-4fd2-b196-365c9df4fac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='يرجى اختيار المستثمرين الأجانب في الشركة'])[1]/preceding::label[1]</value>
      <webElementGuid>0df74646-1f19-49e1-99fc-07422613c171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم رخصة وزارة الاستثمار/ هيئة المدن والمناطق الاقتصادية الخاصة'])[1]/preceding::label[1]</value>
      <webElementGuid>6e4793c2-4cb6-4558-acfb-daae4374ed98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='لا']/parent::*</value>
      <webElementGuid>694d909c-73df-4e31-99ed-3546670fae80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>394673f0-048d-4cc9-abfa-0510ec5b357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'لا' or . = 'لا')]</value>
      <webElementGuid>fd3d1c6d-9334-40e8-ad53-13d1a80260f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
