<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_</name>
   <tag></tag>
   <elementGuidId>ab25ac01-a0dc-4fe4-a8d9-5a43e57140bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactType_listbox > li.k-item</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'ضابط الاتصال الرئيسي' or . = 'ضابط الاتصال الرئيسي')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ContactType_listbox']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9410e7bb-9fff-4c59-b6a1-db11df867016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4e7e8cd-f25b-4ebe-966f-41adc5a9a02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>63e66fe1-eec6-4105-b152-fd736dd2f745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>995c7d7b-88f3-4e7e-8cc1-daad9e04de7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>eaee6e81-a6cd-4671-b1fe-2398c5f7ae6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5b4dd51-5329-42d6-a0dd-33e0c9dde226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8ba4a92-e321-4a76-97e6-29b9a336efe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ضابط الاتصال الرئيسي</value>
      <webElementGuid>706cbb8b-50aa-4f5f-a2a9-50e494982c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactType_listbox&quot;)/li[@class=&quot;k-item&quot;]</value>
      <webElementGuid>2ccbfe1d-8c7e-4d23-a649-5ce10b1b6269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c1177065-9ec1-4842-8d73-df3a937b7cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2299eba2-dae7-4ed9-a8f6-76ca788e2f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bd4c6ce6-2614-4da4-acbf-2d48ce05f739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>26375e76-fee3-432c-82d1-9b5351d0fbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected k-state-focused k-state-hover</value>
      <webElementGuid>e98ebe8a-ec8f-4cbd-b75b-9c0b8022c843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5ae5fc4-3b29-43ab-ad44-bfe5b90f5e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>126c2c5d-34d0-422b-a93b-c0beda859374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5aff5279-f048-4432-9412-731dcb9061b4</value>
      <webElementGuid>6fac898a-79b9-4b59-9020-d2199e986979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ضابط الاتصال الرئيسي</value>
      <webElementGuid>b81f0f05-2f54-4a33-8b14-94c2c3f02e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5aff5279-f048-4432-9412-731dcb9061b4&quot;)</value>
      <webElementGuid>ebe3a341-c3cf-412f-a89e-6a5b030ec9ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ContactType_listbox']/li</value>
      <webElementGuid>6737f7b8-195b-434f-a8a5-09a845c75de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--اختر نوع الاتصال--'])[2]/following::li[1]</value>
      <webElementGuid>a712257e-0c55-469c-83c3-bdde28e9abd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[9]/following::li[1]</value>
      <webElementGuid>5ec6a759-5f56-4a68-b33b-71ca00499c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='آخر'])[1]/preceding::li[1]</value>
      <webElementGuid>fa1e4668-595e-40f4-97c0-461c325deb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[10]/preceding::li[2]</value>
      <webElementGuid>bd26b98d-82fc-4ba0-94da-0bc82ecc0c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ضابط الاتصال الرئيسي']/parent::*</value>
      <webElementGuid>1a35e6a0-49d1-4d5b-be64-7986c41f76f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/ul/li</value>
      <webElementGuid>dad6c3af-0541-44ef-934d-aba6a15980f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ضابط الاتصال الرئيسي' or . = 'ضابط الاتصال الرئيسي')]</value>
      <webElementGuid>226af1d9-0270-48ff-93fb-18be6867fd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='5aff5279-f048-4432-9412-731dcb9061b4']</value>
      <webElementGuid>5b67666b-f1ba-497d-b487-c47aa5098c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='ContactType_listbox']/li)[9]</value>
      <webElementGuid>182cf4a7-827f-418c-83b7-00607e731c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--اختر نوع الاتصال--'])[5]/following::li[1]</value>
      <webElementGuid>45adb6a2-ef60-478d-99b0-0bb9e07b4952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[25]/following::li[1]</value>
      <webElementGuid>5da854f1-cbc5-4e41-a17c-c955e435cda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='آخر'])[5]/preceding::li[1]</value>
      <webElementGuid>e03222d3-14ba-4258-a7a1-1cbf5afd0f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[26]/preceding::li[2]</value>
      <webElementGuid>ddeb09bf-570d-4fa5-b42d-64d58bd716ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[38]/div/div[3]/ul/li</value>
      <webElementGuid>11a43948-c789-45f9-9650-b660ed4f6249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '5aff5279-f048-4432-9412-731dcb9061b4' and (text() = 'ضابط الاتصال الرئيسي' or . = 'ضابط الاتصال الرئيسي')]</value>
      <webElementGuid>0771c6ba-7774-41b4-aaf5-8048923ad592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
