<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>next3</name>
   <tag></tag>
   <elementGuidId>40d63fe4-4a60-4a48-944e-b6a3ef083cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_CommercialInformation_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_CommercialInformation_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23b6a3a6-a484-4b4e-a842-bc6152650b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5a8da5c-2fd1-4924-b17b-ea55c14acabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>a46c0c8c-9689-40e6-99ee-a16b239d2fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_CommercialInformation_Save</value>
      <webElementGuid>836b8784-c743-45c7-9570-54e8a273c402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>9ae80657-4a97-4e0b-8d85-7c23946225a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_CommercialInformation_Save&quot;)</value>
      <webElementGuid>3f894a3b-81cf-4bcf-9b5c-e9817e875040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_CommercialInformation_Save']</value>
      <webElementGuid>cff15dfb-b3d4-4070-9e3f-145293d49109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_CommercialInformation_form']/div[3]/div/input[2]</value>
      <webElementGuid>2602f0e3-c5c8-4ee8-991f-2653778d424c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/form/div[3]/div/input[2]</value>
      <webElementGuid>2a9797c1-7ce5-4540-a967-e5a09296f3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_CommercialInformation_Save']</value>
      <webElementGuid>8e01e444-982a-4551-a865-e9c959417152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
