<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save8</name>
   <tag></tag>
   <elementGuidId>09810785-140a-4e8f-a56f-ed5865b44547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_OwneshipDetails_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_OwneshipDetails_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>484bd854-383c-41a3-9ce7-7846a6d90088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e605c974-1175-47bd-9075-dfc212d71388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>fc08ac10-e512-4074-bc08-513806ecf620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_OwneshipDetails_Save</value>
      <webElementGuid>01b34070-c296-4659-9f5d-fe343241bc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>79411c41-cf7c-4a0c-b20c-ef3c7e2ebfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_OwneshipDetails_Save&quot;)</value>
      <webElementGuid>a2f64b48-25c5-4c13-b678-89ab90f5b01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_OwneshipDetails_Save']</value>
      <webElementGuid>023d7eeb-7765-41a5-9938-15323bcd4b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetails']/div/div/div/div[7]/div/input[2]</value>
      <webElementGuid>56974fbd-d5d3-4d62-80f2-09f7b26a38b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input[2]</value>
      <webElementGuid>59f35fa6-2e73-4020-9ef4-8937ce6e5bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_OwneshipDetails_Save']</value>
      <webElementGuid>4d649e83-0a52-4d93-ae87-28822dc8336c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
