<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save7</name>
   <tag></tag>
   <elementGuidId>a4dd3520-9e51-4856-bb0b-a31abb45e556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_ContactInfo_Save</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @id = 'btn_ContactInfo_Save']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_ContactInfo_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>925eba89-d7e8-4e5b-9a49-b468787642f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>568b42f4-365d-44ad-a546-30fa01646334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>57fc5462-1bdd-4a1f-b3ca-9b940a3b092a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_ContactInfo_Save</value>
      <webElementGuid>b5bfbdd8-326b-46bc-97b3-cc325c8c7ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>c61ce318-81de-47af-82f5-be39600fa76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_ContactInfo_Save&quot;)</value>
      <webElementGuid>27207944-0094-45a4-b1d7-18e44e475285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_ContactInfo_Save']</value>
      <webElementGuid>2f4f6478-f4ba-47bf-a0b7-e5b16399a93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveContactInfo_form']/div[3]/input[2]</value>
      <webElementGuid>5911a8df-7522-43b2-b4d5-ca70081b9870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input[2]</value>
      <webElementGuid>70e363d3-850e-4449-b1db-bbf4a9d5010c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btn_ContactInfo_Save']</value>
      <webElementGuid>84a8aeb9-16f8-4eaa-a3fc-329269508cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
