<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save10</name>
   <tag></tag>
   <elementGuidId>cd200436-4af0-49ca-8073-730ababd06b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_Atatchment_Save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Atatchment_Save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd030380-73c5-43eb-958a-58d6cbac594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd46c882-19a1-48ae-8690-daef6414f630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>dad2892f-2b05-410a-b5da-fedd29d1bc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Atatchment_Save</value>
      <webElementGuid>78048002-5b3e-4e61-98f9-bffbd01297de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>fc5ac5c8-3936-4f45-a347-28b30115200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Atatchment_Save&quot;)</value>
      <webElementGuid>ecdd515a-99ea-4bd5-874f-fb28c8230c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_Atatchment_Save']</value>
      <webElementGuid>a3018a70-a923-4bea-9323-2908626acc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AttachmentTab']/div[2]/div/div/div[3]/input[2]</value>
      <webElementGuid>e6483c31-6351-4e95-9d69-781ba180b5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input[2]</value>
      <webElementGuid>5b9e9d14-831a-4070-9878-835eae7d3ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_Atatchment_Save']</value>
      <webElementGuid>f2217a73-c70f-4256-b363-c21a9ac4e357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
