<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save9</name>
   <tag></tag>
   <elementGuidId>e4434e8f-7041-41e9-bb0b-1fb129bf1e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_CompanyHierarchy_Save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_CompanyHierarchy_Save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2b277e6-c5d3-4ad5-b277-d5ebce993615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b982e650-45ff-41d5-9c31-ee6aac4f6dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>961b9467-26a6-49ad-8fee-a2db9b14ae4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_CompanyHierarchy_Save</value>
      <webElementGuid>ba334461-e2db-4522-96fc-65e2411e94bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CompanyHierarchy_Save();</value>
      <webElementGuid>357f097d-b796-4e21-b34a-2d823a1b7745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>23945aa3-2c30-4e92-b2ea-7364fb26552d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_CompanyHierarchy_Save&quot;)</value>
      <webElementGuid>6bc9fcca-1888-462f-8be9-685d52ab812d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_CompanyHierarchy_Save']</value>
      <webElementGuid>cb01d279-f0a3-4442-ab2e-128191ccaea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyHierarchy']/div/div/div/div[3]/div/div/input[3]</value>
      <webElementGuid>22e422bd-35a1-4c06-8d55-a1d1330e7047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/input[3]</value>
      <webElementGuid>1c0ec443-6825-4e6b-abac-81ab149151d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_CompanyHierarchy_Save']</value>
      <webElementGuid>dea4d19e-f6ae-4337-bb3d-d3c36d36a276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
