<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select4</name>
   <tag></tag>
   <elementGuidId>7a677530-cdd7-4338-9d75-796ed917f9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CompanyHierarchyDiv']/div/div[2]/div/div/span[2]/span/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-focused > span.k-select > span.k-icon.k-i-arrow-60-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8fd8cbbe-457d-40f2-b696-1e73cb381a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>ff2596e0-cfc5-4225-92e3-88532dfc424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyHierarchyDiv&quot;)/div[@class=&quot;bg-box-shadow&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 col-lg-12 form-group&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12 fl-right pad-right-0 pad-left-0 pad-left-mob-0 pad-right-mob-0&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>96d09649-fb1b-48a7-9951-befe757a508f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyHierarchyDiv']/div/div[2]/div/div/span[2]/span/span[2]/span</value>
      <webElementGuid>2aafa031-b62d-4452-ad78-b23672c2a0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]/span/span[2]/span</value>
      <webElementGuid>91a39d27-b3e0-4e04-94ed-f05322692e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
