<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_</name>
   <tag></tag>
   <elementGuidId>f38fc1eb-9c45-41f3-aafd-5c01d83f2b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grdSMEClassificationAgentActivity_active_cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>625a7d41-730f-43c2-9d09-124435ed23e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-header k-state-focused</value>
      <webElementGuid>652f646a-ac82-434b-a228-55b5abee7541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>ff7b7c6f-41be-4e94-84fe-0a5115cee116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a0dbd5f-bfcb-4f52-8368-e468b24a2d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdSMEClassificationAgentActivity_active_cell</value>
      <webElementGuid>fb2ec4f9-64ed-4899-8165-1f156605b030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>a0661bc7-3924-43ea-804d-12c4fb74e1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)</value>
      <webElementGuid>7fa10b99-3fc0-4b05-a7ae-8a80619f5ea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']</value>
      <webElementGuid>ade645b8-e15d-4cbe-97fe-e110a973f45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdSMEClassificationAgentActivity']/div/div/table/thead/tr/th</value>
      <webElementGuid>4f5437fd-f423-48ab-ae19-4a13c1ee5480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ابحث باسم النشاط أو كود النشاط'])[2]/following::th[1]</value>
      <webElementGuid>450efe70-26f0-4136-91fd-ec4280653b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[2]/following::th[1]</value>
      <webElementGuid>05d8149a-f982-4c9a-a677-7131e42b03cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SME Activity ID'])[2]/preceding::th[1]</value>
      <webElementGuid>f9a194ff-2c88-4133-8d22-987362132486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/table/thead/tr/th</value>
      <webElementGuid>357bb907-1fd4-43c4-845b-5301790bf513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'grdSMEClassificationAgentActivity_active_cell' and (text() = '​' or . = '​')]</value>
      <webElementGuid>f9fcae2b-c82f-4888-8354-b5344f85145b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
