<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wakel</name>
   <tag></tag>
   <elementGuidId>8a615a6e-e290-4781-a49e-35f7852b23a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a6f516f9-e126-4f6a-a4bf-74bf9e2b26ba</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='a6f516f9-e126-4f6a-a4bf-74bf9e2b26ba']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'وكيل' or . = 'وكيل')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c0e1562d-f453-493c-a259-8d84416cbd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0776cc9a-c98c-4852-b1a1-621eba2979a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cff4baef-04f1-497d-b937-5d0409018c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6d0dddd7-70a8-439e-a663-ee022e5f75cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-hover</value>
      <webElementGuid>c0e56307-5326-491c-adfd-f90ccca4960d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b13a9334-edd4-4f3b-9c72-9f73ff6899a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d99fc083-42b4-4290-bb9e-5ce7246f3bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a6f516f9-e126-4f6a-a4bf-74bf9e2b26ba</value>
      <webElementGuid>2a2a46ee-705f-42e7-8fa0-2cd908c34b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>وكيل</value>
      <webElementGuid>70f2a090-ae58-43f2-95d9-b50b4c76418e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a6f516f9-e126-4f6a-a4bf-74bf9e2b26ba&quot;)</value>
      <webElementGuid>7e6be499-2128-41ed-b6e7-7b0e1af569f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='a6f516f9-e126-4f6a-a4bf-74bf9e2b26ba']</value>
      <webElementGuid>e7331de1-0ea6-4d6b-ae91-b0ecbe05ed8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ddlSMEClassifications_listbox']/li[2]</value>
      <webElementGuid>3457c4d1-71c0-40af-886f-57c5cfaacd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مصنع'])[2]/following::li[1]</value>
      <webElementGuid>2b174c15-5f74-4508-8bee-c3d568cf8831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[6]/following::li[2]</value>
      <webElementGuid>43c30ad6-d3e7-4a60-b604-8c3ed2a17403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='موزع'])[2]/preceding::li[1]</value>
      <webElementGuid>e385b2a8-9891-4263-8346-7ecaf9722deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مورد'])[2]/preceding::li[2]</value>
      <webElementGuid>c3480bbd-d85c-4a21-bcb9-487e4c4425eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div[2]/ul/li[2]</value>
      <webElementGuid>52df42c7-ed8a-4186-acd6-95f1c8a095d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'a6f516f9-e126-4f6a-a4bf-74bf9e2b26ba' and (text() = 'وكيل' or . = 'وكيل')]</value>
      <webElementGuid>267f6b9d-8643-412a-a10c-59a2afabd7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
