<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_10</name>
   <tag></tag>
   <elementGuidId>b934b405-341c-4b2b-ab1e-4a1b8c5b5123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='154c82ee-07eb-41a8-a79a-fc27dfd8e70a']/table/tbody/tr[6]/td[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.k-other-month.k-weekend.k-state-hover > a.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39a19199-93c6-4c50-a0fe-2c6392cc7c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>944b07a8-a126-4664-8ce0-8fed2520ebf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>92386710-a4cd-4330-bdde-773d7416544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2beb4970-b049-44a7-9d96-e898b84ebcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2022/11/10</value>
      <webElementGuid>44533a1a-50b3-4261-8537-5c0866e4699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Saturday, December 10, 2022</value>
      <webElementGuid>6cdd7b25-7cbb-479d-8811-a7dc88a6ed97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>853e9656-fc4e-4a8c-9371-74c31af11993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;154c82ee-07eb-41a8-a79a-fc27dfd8e70a&quot;)/table[@class=&quot;k-content k-month&quot;]/tbody[1]/tr[6]/td[@class=&quot;k-other-month k-weekend k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>f7a719a7-6b92-4309-ad77-fde154db2b76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='154c82ee-07eb-41a8-a79a-fc27dfd8e70a']/table/tbody/tr[6]/td[7]/a</value>
      <webElementGuid>b27f9d47-0a7d-473b-8e3b-bbeb98dcc5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'10')])[14]</value>
      <webElementGuid>6a9bb95a-a33e-4b79-bd4d-466b4e928aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[5]/following::a[42]</value>
      <webElementGuid>ae36e4cf-d19d-414f-87de-41de2fafe5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[5]/following::a[42]</value>
      <webElementGuid>d6698af6-92c7-4a9c-a2a2-7f8c46389bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- اختر نوع العملة -'])[7]/preceding::a[2]</value>
      <webElementGuid>5f648a2d-5f38-4b58-9dcd-0dfacac99661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[6]/preceding::a[2]</value>
      <webElementGuid>07c72f36-646e-4ffe-b7d0-de1ddcf23b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[302]</value>
      <webElementGuid>fc75725e-530d-4e5d-8338-d080b126a984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[116]/div/div/table/tbody/tr[6]/td[7]/a</value>
      <webElementGuid>2db5f1b9-592b-4381-96f8-80e5837951fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Saturday, December 10, 2022' and (text() = '10' or . = '10')]</value>
      <webElementGuid>7ef3e5e3-5b42-4aee-aad0-f04406be1add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
