<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Recievables</name>
   <tag></tag>
   <elementGuidId>d5317e18-e0d1-443f-b2ae-5e7d85b5e6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRecievables</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRecievables']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>049da946-bead-4e13-875a-cf24f2e1a2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>9bbc2fc8-12c8-4b31-b646-3631677c5c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd32e90e-bcf2-4ddb-ad55-f6b530cbefcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل ذمم مدينة مطلوب</value>
      <webElementGuid>cfc0c4ed-55e8-4865-a0a5-c7ac9ee240dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRecievables</value>
      <webElementGuid>ffd3de8a-03a8-425e-9b51-b387e90a1dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1c92600a-4f7a-4f07-b4da-6abbd8736b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Recievables</value>
      <webElementGuid>847a93f6-4afa-4911-a65d-f4aaa023e858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ذمم مدينة</value>
      <webElementGuid>286c08e8-3457-4b9c-a044-cfd159a097d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b65d3f75-0bf0-49e8-936b-16f563a254bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ذمم مدينة</value>
      <webElementGuid>45df4859-d56e-45e9-8560-89a08cc2b529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcb4519a-3566-4f95-9d4b-744dfe197e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRecievables&quot;)</value>
      <webElementGuid>3bcd7ba9-d7fc-473a-bb64-38c728068c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRecievables']</value>
      <webElementGuid>1b029285-8d89-462c-a2eb-fed3d93b9f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[2]/div[2]/input</value>
      <webElementGuid>6b01ce26-796b-43fa-8562-426cb39f03c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[2]/div[2]/input</value>
      <webElementGuid>2c97306e-ef53-4e6f-af19-be3b59fc3af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtRecievables' and @name = 'Recievables' and @placeholder = 'ذمم مدينة' and @title = 'ذمم مدينة' and @type = 'text']</value>
      <webElementGuid>9d1ef766-baae-4d4b-be8e-cacbab2032d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
