<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LongTermDebt</name>
   <tag></tag>
   <elementGuidId>018f50ff-3624-4aa6-b3f6-c4c5ef826f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLongTermDebt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLongTermDebt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7982afff-3dff-4cbc-a26d-54e82dac0cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>c606210b-7c3f-4029-8010-e971f28986ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08943f5d-aab5-43df-84ad-14121725c314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الديون طويلة الأجل مطلوب</value>
      <webElementGuid>e84f5f0f-0765-47b7-85a2-6c84fda9bb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLongTermDebt</value>
      <webElementGuid>a9fe47cb-b415-4b41-8393-08d70c4a9613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>12c9e235-6940-4767-8966-c8de15bffdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LongTermDebt</value>
      <webElementGuid>97d44de4-b0e9-405e-bf8e-6f48519fb59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الديون طويلة الأجل</value>
      <webElementGuid>8e4f7cb8-53d2-4209-975a-db50c94d42d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ed8192ce-1bc5-4a29-b479-ad982146e66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>الديون طويلة الأجل</value>
      <webElementGuid>ad54626f-1e9a-421c-b47a-da0cd136e89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a52fe8ec-14c1-4c8f-9963-c2892a760c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLongTermDebt&quot;)</value>
      <webElementGuid>58274f63-8a28-46dd-bf2b-945697e6738a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLongTermDebt']</value>
      <webElementGuid>ad3013ff-49ba-4ac5-ab47-086612893595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[5]/div[2]/input</value>
      <webElementGuid>e448e987-43b7-4cd4-8e86-27dc366eb2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[5]/div[2]/input</value>
      <webElementGuid>acb76876-fb31-44b8-843f-9fd9212637b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLongTermDebt' and @name = 'LongTermDebt' and @placeholder = 'الديون طويلة الأجل' and @title = 'الديون طويلة الأجل' and @type = 'text']</value>
      <webElementGuid>572de0f3-b8f0-460a-9121-442b68413fd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
