<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CurrentLiabilities</name>
   <tag></tag>
   <elementGuidId>c7e65b15-b0c8-467f-92f0-2a7379663112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCrntLiabilities']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCrntLiabilities</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54b401ee-bbb9-423a-ac18-2eb2a23d9df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>95f5d9f3-6372-4be0-b207-2390a92a300e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>059a83af-ef65-4c9b-b4d9-1adc30b769e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل المطلوبات المتداولة مطلوب</value>
      <webElementGuid>e5ad0035-b6da-4484-b80d-ce0d90829485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCrntLiabilities</value>
      <webElementGuid>b5b12d40-cd58-4963-b6c5-f4461ba44cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8bbb547e-cc95-4448-91dd-bba953315679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CurrentLiabilities</value>
      <webElementGuid>2304f368-5b1b-4752-83bc-82a3172e618b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>المطلوبات المتداولة</value>
      <webElementGuid>ebb71619-ce8f-4f30-be2a-9e304447dfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>edeef94b-3fa7-41c3-9f5a-ba734f8f7ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>المطلوبات المتداولة</value>
      <webElementGuid>168ca31d-99f9-4b6f-9f05-1b724fda2cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6315e0df-f561-4708-83bc-07ad9b6e1dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCrntLiabilities&quot;)</value>
      <webElementGuid>8bf6fa75-00d5-4246-a15e-4729d1cc9f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCrntLiabilities']</value>
      <webElementGuid>4cc0a969-4abd-4984-b679-14e3de69f97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[5]/div/input</value>
      <webElementGuid>713c917f-f43e-4cb8-b5f3-32c4e9371220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[5]/div/input</value>
      <webElementGuid>1dc8891c-23b5-475f-9765-bb8db0efca1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCrntLiabilities' and @name = 'CurrentLiabilities' and @placeholder = 'المطلوبات المتداولة' and @title = 'المطلوبات المتداولة' and @type = 'text']</value>
      <webElementGuid>af76f5f2-96a1-44c3-85e9-1e0d278fc315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
