<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ShortTermDebt</name>
   <tag></tag>
   <elementGuidId>b78c9ddc-7369-4b20-b2f3-03c6e869981e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtShortDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtShortDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0f8aecf-1d93-4860-ad7f-a1ed84edcb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>d26ff2de-6af0-4e9c-98d7-fe12f15166d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a47087f-bae9-4b4e-a97b-394070224bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الدين قصير الامد مطلوب</value>
      <webElementGuid>11839d36-35b9-476c-9ba2-f7325873b3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtShortDate</value>
      <webElementGuid>f7f98725-90f0-465c-990a-a281d904168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>de71e1e8-371f-4208-8d35-f1b64eb7522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShortTermDebt</value>
      <webElementGuid>829e7136-662a-491c-a8be-bc7637fa4ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الدين قصير الامد</value>
      <webElementGuid>4ebd88a2-52b9-47ac-afd1-55b9c3ec152e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>9f9abb26-c25d-43e7-b77a-eb5733fc5f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>الدين قصير الامد</value>
      <webElementGuid>ce184bb5-67cd-4598-835b-1b8a1ed737e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9d69cf8-64fa-4497-849f-1045d41946af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtShortDate&quot;)</value>
      <webElementGuid>49d35575-0a12-4e52-80d0-cc0689226042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtShortDate']</value>
      <webElementGuid>f452f92c-3046-4ee6-b16e-0f78298ba254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[4]/div/input</value>
      <webElementGuid>0ee015fb-86d3-473c-baa4-ad8aa36a1355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[4]/div/input</value>
      <webElementGuid>54ffd811-c904-4742-938d-011c936aafa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtShortDate' and @name = 'ShortTermDebt' and @placeholder = 'الدين قصير الامد' and @title = 'الدين قصير الامد' and @type = 'text']</value>
      <webElementGuid>ae6dc25b-7285-4127-bfdf-3fd0d912d06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
