<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CurrentAssets</name>
   <tag></tag>
   <elementGuidId>a4dc94e3-db37-42cd-afbc-ad710fa15396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCrntAsset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCrntAsset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aca628a6-9ff2-4c79-a648-6d132fc36adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number currency</value>
      <webElementGuid>57362fdd-d57d-45c6-b793-42d02d57da88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d8bfa91-c378-4eaf-b7f4-233bd22901d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الاصول المتداولة مطلوب</value>
      <webElementGuid>43693f1e-7ea7-48d3-9153-3d2fc1a959f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCrntAsset</value>
      <webElementGuid>a9157bda-a064-427e-95f9-91c416a35aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>21fbd0cb-8766-46ad-8532-bd7fb4ab6727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CurrentAssets</value>
      <webElementGuid>e4a0d9fa-a195-4eed-afb3-7d0d305394e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الاصول المتداولة</value>
      <webElementGuid>046ae3da-a7dc-4461-8748-ca2db7dca0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a5e0aa3e-c5a7-4398-b04e-8ffa198389f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>الاصول المتداولة</value>
      <webElementGuid>d78134de-4195-4119-8808-d480a6bd6933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcfc9b07-4591-4ccd-ae55-c4e059d87763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCrntAsset&quot;)</value>
      <webElementGuid>92b856b0-c3ad-4770-bdd3-1ffe28a91c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCrntAsset']</value>
      <webElementGuid>70b57d92-38c4-441f-9d60-3a641d7135d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormFinancial']/div/div[3]/div/input</value>
      <webElementGuid>c436006c-fe97-4276-9118-0a70c0fe57d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/form/div/div[3]/div/input</value>
      <webElementGuid>ebdeaf3d-8099-4657-b08c-587bcd2907eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCrntAsset' and @name = 'CurrentAssets' and @placeholder = 'الاصول المتداولة' and @title = 'الاصول المتداولة' and @type = 'text']</value>
      <webElementGuid>392923f6-74b0-48e6-9598-a1fb557b5730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
