<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_2022</name>
   <tag></tag>
   <elementGuidId>774ac543-d809-4acf-b923-7db8789fb8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-item.k-state-hover</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '2022' or . = '2022')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='txtStrtYrDt_listbox']/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0c3d4214-6b73-43cc-9c69-69af033a58c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0df399ea-890f-4b6c-982b-dc5cd9e76596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6482be75-7e46-429c-9c98-9c389de6ea88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>559889de-3fa3-4362-b6d4-4fa07c17d9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-hover</value>
      <webElementGuid>7589b01a-f925-4190-bb7e-f232acadf60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f4a718d-975f-4000-a26d-1cd587bb13aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>55f13191-63fe-4dad-bbd1-8746046fd9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>ff02d02f-8bf7-4b2d-966d-a2ae448a87f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtStrtYrDt_listbox&quot;)/li[@class=&quot;k-item k-state-hover&quot;]</value>
      <webElementGuid>dc05f008-2276-46aa-ae03-f83f8175b43c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='txtStrtYrDt_listbox']/li[4]</value>
      <webElementGuid>4b8c92c5-c183-4f82-8a3d-cb3d460e373d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختيار سنة القوائم المالية'])[2]/following::li[4]</value>
      <webElementGuid>05a78412-c847-421e-b812-fcad6f0e1f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[4]</value>
      <webElementGuid>904f8f64-eb06-4878-8486-6f53345fb1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[10]/preceding::li[1]</value>
      <webElementGuid>2bcd40c1-b102-4807-955a-805eed2fc2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- اختر نوع العملة -'])[2]/preceding::li[1]</value>
      <webElementGuid>404e860a-4959-48ba-9bc2-e2bc785a77ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022']/parent::*</value>
      <webElementGuid>ea205a41-6cd7-4b7d-bb94-207736d45508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[46]/div/div[3]/ul/li[4]</value>
      <webElementGuid>2cb27e73-1f6d-4176-a42b-3dea9e667929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '2022' or . = '2022')]</value>
      <webElementGuid>2d145227-3be4-4c4a-9178-e7f9d6e69ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
