<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete contact</name>
   <tag></tag>
   <elementGuidId>b9b0f9dc-3acf-4cc1-aef8-7f2a4eaadeac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-bin.grdDelIcon.grdCursorStyle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'حذف السجل']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick='DeleteContactInformationRecord(this);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>785830c4-cf43-454e-a43f-832e5004d08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bin grdDelIcon grdCursorStyle</value>
      <webElementGuid>3bcce5fa-c89c-43f2-8285-be650de725bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>حذف السجل</value>
      <webElementGuid>33453f13-6b5e-4609-88c3-1da414172b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DeleteContactInformationRecord(this);</value>
      <webElementGuid>862b7559-2c2b-4b21-9e50-0aeac0cf73a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactInfoGrid&quot;)/div[@class=&quot;k-grid-content k-auto-scrollable&quot;]/table[1]/tbody[1]/tr[1]/td[18]/i[@class=&quot;icon-bin grdDelIcon grdCursorStyle&quot;]</value>
      <webElementGuid>7f5fb304-8a1e-437d-8efd-81f9a9f3a1e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='DeleteContactInformationRecord(this);']</value>
      <webElementGuid>1dc3e96d-886d-477a-9dd3-75795d915733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactInfoGrid']/div[2]/table/tbody/tr/td[18]/i</value>
      <webElementGuid>00ab849a-317e-4301-95b3-7165ca441811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[18]/i</value>
      <webElementGuid>9b0b32dc-0079-44ff-b0a8-994bf8801e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'حذف السجل']</value>
      <webElementGuid>99938cff-d73d-40d5-b420-e2ae7d8a5b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
