<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delet attch</name>
   <tag></tag>
   <elementGuidId>937bc1a8-b359-4a17-ac57-dd550aae1c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='BtnDelete1021']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnDelete1021</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1de6af02-cbfa-4966-a410-088cccc6e7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bin grdDelIcon grdCursorStyle</value>
      <webElementGuid>28511586-02d7-4d37-ac00-db54ab7bcdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>حذف</value>
      <webElementGuid>bb318749-dd2c-4b12-915a-a665f6ed76c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnDelete1021</value>
      <webElementGuid>3e9dbfb5-8b21-4f51-8949-49faab288ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Deletefile(this);</value>
      <webElementGuid>2d740858-1894-4117-8a92-c344ef3ade89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnDelete1021&quot;)</value>
      <webElementGuid>c33dda3a-bb09-44db-b932-447dc94a0bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='BtnDelete1021']</value>
      <webElementGuid>8cddd25e-1d06-4ca3-9375-6db7c7b7f283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']/div[2]/i</value>
      <webElementGuid>4bf99fc1-973c-4820-9b1d-878723f2de6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div[2]/i</value>
      <webElementGuid>92731f1a-1259-4a7b-a0b0-7e0f0e9b4686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'حذف' and @id = 'BtnDelete1021']</value>
      <webElementGuid>5c6ddda7-7e14-429b-a097-8cf954f8db9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
