<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_ZAKAT_Prev5</name>
   <tag></tag>
   <elementGuidId>de651484-7cb5-4373-b870-25167342f70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_ZAKAT_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_ZAKAT_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c828aec8-b690-47f6-b21e-bbc42024b48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d58d58fc-1aa6-4cb8-a711-2f73838e32a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>4d4ea5b4-288d-4937-b7f7-bdfccb873688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_ZAKAT_Prev</value>
      <webElementGuid>2ef43262-7eb6-4a75-8d11-eb97b2759ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>3aae1bd6-5d0b-4732-a72a-36b31760f03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_ZAKAT_Prev&quot;)</value>
      <webElementGuid>f1270846-6697-4831-a710-6a2e84e5c1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_ZAKAT_Prev']</value>
      <webElementGuid>69587aec-7e76-4029-b640-b7c3af76d2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_ZAKAT_form']/div[3]/div/input</value>
      <webElementGuid>9965b83e-79bf-4f1d-af0f-5211e502a24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[3]/div/input</value>
      <webElementGuid>cc8e0eb3-ea1d-49fe-bb7c-6fba257cb314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_ZAKAT_Prev']</value>
      <webElementGuid>75cbea12-f6b1-497b-ba10-dbd9e72ecfa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
