<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select files_btn_Attachment_Prev</name>
   <tag></tag>
   <elementGuidId>7b158262-cce5-4a9f-b95d-0ba1b6b91503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_Attachment_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Attachment_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cbcfdcc-8daa-4517-8404-5fd523b7db56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0351ac8-a7fc-4b8b-bd22-2429ef873dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>ec2d8554-75eb-41e2-823a-056e7ab37ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Attachment_Prev</value>
      <webElementGuid>a11b304c-321b-44bc-a268-ea5aad655305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>b768dbc9-668c-4da9-9e30-4db1ec8a127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Attachment_Prev&quot;)</value>
      <webElementGuid>dd8dc51e-e3b3-44dd-a1b7-a1aeb472a54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_Attachment_Prev']</value>
      <webElementGuid>828360bd-8276-4422-a9db-277f978ad82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AttachmentTab']/div[2]/div/div/div[3]/input</value>
      <webElementGuid>15643772-acfe-4f67-bfcd-2fd2823eecb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>2765e707-46fb-4cd5-b763-a83b1a10c8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_Attachment_Prev']</value>
      <webElementGuid>00c986ba-efc5-4c15-8db2-628f6058bf99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
