<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_ContactInfo_Prev3</name>
   <tag></tag>
   <elementGuidId>a32e52c2-d041-4556-90fc-453c87244512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_ContactInfo_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_ContactInfo_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9093a0c-5e55-4e1c-8637-6c689773880f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23205146-6d86-4a44-86eb-09cbd55e9fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>bdad9020-745a-42e6-b2b6-117835adefc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_ContactInfo_Prev</value>
      <webElementGuid>d326cd55-e7bf-4b00-bb5a-134a207dc269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>6b87a833-712e-4799-a9b3-1b0d5a61796f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_ContactInfo_Prev&quot;)</value>
      <webElementGuid>eaf70504-3a2b-41e0-a9b3-62625eb71190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_ContactInfo_Prev']</value>
      <webElementGuid>ec4fbece-bfa3-4ede-bbd8-7d1b763d3141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveContactInfo_form']/div[3]/input</value>
      <webElementGuid>951a7ad5-99d9-40c7-97d2-4cbf744151dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>c3f1dc20-dee6-42af-ba0f-7ac8763864e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_ContactInfo_Prev']</value>
      <webElementGuid>181e0c95-4541-4742-9643-e0e6eda30a07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
