<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_CompanySize_Prev4</name>
   <tag></tag>
   <elementGuidId>44c1feda-d4e9-4ca9-9a17-f91ded1222d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_CompanySize_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_CompanySize_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>219f8ed8-b889-4f3d-a332-91f92ea13339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>832ce926-6194-45a3-9634-c58ccfa79a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>46f78f4e-f49c-41ef-b9c9-1c40d1ebb409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_CompanySize_Prev</value>
      <webElementGuid>50fe1e41-ef88-424b-90d6-b447fb2f2ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>1f3cb25a-8bd0-41a9-a572-bda208a45e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_CompanySize_Prev&quot;)</value>
      <webElementGuid>9e2a0bfa-1145-442c-82ac-da315d5e41f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_CompanySize_Prev']</value>
      <webElementGuid>693c728c-468a-495a-a461-f02d462338e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_CompanySize_form']/div[3]/div/input</value>
      <webElementGuid>1b670090-54c2-47ad-988d-9456875191d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/form/div[3]/div/input</value>
      <webElementGuid>dae8b997-eec2-409c-8469-1deb9889478c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_CompanySize_Prev']</value>
      <webElementGuid>612a836c-ae6c-4846-9662-9ca8bcf76dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
