<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_SAGIA_Prev6</name>
   <tag></tag>
   <elementGuidId>7dfc46aa-6951-448e-8d8f-79a38fd84ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_SAGIA_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_SAGIA_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a6fc488-4325-4041-90dc-847746130535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f81d7f2a-be41-46af-872f-e4eaba517bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>8d6c71b3-d13e-4f5b-b7c5-b410fa0848a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_SAGIA_Prev</value>
      <webElementGuid>e2df3588-945b-4cee-8a0a-f12abe10f54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>3eafb616-b82a-4417-bcdd-983b22482072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_SAGIA_Prev&quot;)</value>
      <webElementGuid>5b92a61c-0770-4619-85e2-4b4b980ed544</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_SAGIA_Prev']</value>
      <webElementGuid>4c4ebea6-f0c4-4429-9681-7ca3fe3836c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_SAGIA_form']/div[3]/div/input</value>
      <webElementGuid>f80b90b3-d6e4-4d77-b185-c95737475f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/form/div[3]/div/input</value>
      <webElementGuid>602a5d3e-48e7-41c9-b7f6-5e4b68226c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_SAGIA_Prev']</value>
      <webElementGuid>c7458e40-8b6a-4108-898c-46ec13d860f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
