<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_CommercialInformation_Prev7</name>
   <tag></tag>
   <elementGuidId>59fc02a0-903c-4068-b0de-163efe0e15b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_CommercialInformation_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_CommercialInformation_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da445911-4412-435f-8128-30ffe5842758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92d715af-083b-4a90-b7aa-250b31803f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>ae89e86a-071e-4def-92fa-97e9b3497853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_CommercialInformation_Prev</value>
      <webElementGuid>9d4730a2-728b-4a4b-884f-292b3ef36a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>c6f9a781-95f6-4536-a9b0-dac540ec6463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_CommercialInformation_Prev&quot;)</value>
      <webElementGuid>f2906f3a-89de-48cb-95bf-e37b09783892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_CommercialInformation_Prev']</value>
      <webElementGuid>5fc25f6d-6968-4529-b007-580c561b5062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_CommercialInformation_form']/div[3]/div/input</value>
      <webElementGuid>f7522dac-7b84-402e-8159-e059090af51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/form/div[3]/div/input</value>
      <webElementGuid>2497eae4-e1f5-4acb-9f91-9ddef72bd683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_CommercialInformation_Prev']</value>
      <webElementGuid>ca8058f1-20de-4077-b242-bdf49089d1d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
