<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_OwneshipDetails_Prev2</name>
   <tag></tag>
   <elementGuidId>905a33e5-8b81-4d17-a977-4dc495649db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_OwneshipDetails_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_OwneshipDetails_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74aa8e8e-64ab-41df-9fe3-d0891dab717b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a51dc04f-4443-40ec-a6e1-0d4ae79c64ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>ea34b6e0-cf0e-4906-af11-23aceeecc9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_OwneshipDetails_Prev</value>
      <webElementGuid>22d4a3df-85d3-41ec-84d0-89b82cd869f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>b11f170b-0b9f-4e25-8b08-bb1d2c5f061a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_OwneshipDetails_Prev&quot;)</value>
      <webElementGuid>99cdaa12-7418-48cf-9b9b-2c0e247da06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_OwneshipDetails_Prev']</value>
      <webElementGuid>64749511-8fcc-4d09-b895-7b4acb2ab9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipDetails']/div/div/div/div[7]/div/input</value>
      <webElementGuid>66125e66-af83-4569-8e11-574055f0cf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>fffba521-ef99-42d4-8962-d6c4bd303cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_OwneshipDetails_Prev']</value>
      <webElementGuid>2e35171a-c299-40d7-bc57-89fe74f5a048</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
