<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_Technical_Prev</name>
   <tag></tag>
   <elementGuidId>1c3ee8a0-22e9-4e95-ade4-0cb77b0b3184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Technical_Prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_Technical_Prev']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>165ee33b-0d32-4cd0-8fba-decf9ed84015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c5e96fc-cf0e-4e6f-a7af-3e1d0c737d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>7d054944-42d7-4786-8806-16878505132c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Technical_Prev</value>
      <webElementGuid>45b5525a-bd0a-4665-b1b2-042183d3f078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>58225daa-4931-4084-a5c3-254c08a3d605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Technical_Prev&quot;)</value>
      <webElementGuid>54cdf36d-c160-4e90-9f69-8393c2356693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_Technical_Prev']</value>
      <webElementGuid>d5aac8b7-803f-4b84-9ef5-d64ec129e446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TechnicalTab']/div/div/div[3]/input</value>
      <webElementGuid>0c33d301-c5ea-4d5c-a704-8cd2a58788cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div[3]/input</value>
      <webElementGuid>2453d1bb-e586-49ad-96e5-46f07d565256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_Technical_Prev']</value>
      <webElementGuid>8464ca53-1fc1-4e74-ad7d-cc3ba295f755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
