<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn_CompanyHierarchy_Prev1</name>
   <tag></tag>
   <elementGuidId>b0b359ac-2ed4-48aa-a4d3-df723ab20fec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_CompanyHierarchy_Prev']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_CompanyHierarchy_Prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e2f659a-554c-4674-80a7-775ec614c933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccdc1039-48f4-42ca-b702-3a1cfb2989d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrleft-1</value>
      <webElementGuid>90ef5ad4-3913-48c8-8061-0fee2a5dbdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_CompanyHierarchy_Prev</value>
      <webElementGuid>b69b8133-449c-4019-90c7-8a33d20dbe5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CompanyHierarchy_Prev();</value>
      <webElementGuid>fa3b54dd-243c-4df9-bd4f-667c52a0c0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>السابق</value>
      <webElementGuid>e37753a0-c492-4ed8-85aa-952002e0ce58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_CompanyHierarchy_Prev&quot;)</value>
      <webElementGuid>522bd6d2-d1eb-4127-a81b-ca18d2847255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_CompanyHierarchy_Prev']</value>
      <webElementGuid>a5473b6a-fbd3-40b4-b41c-be515dadf172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyHierarchy']/div/div/div/div[3]/div/div/input[2]</value>
      <webElementGuid>acb93de5-8389-46d9-b970-7f4e2b83b95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/input[2]</value>
      <webElementGuid>4084bf6a-54ee-4614-99be-4a8da41ba1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_CompanyHierarchy_Prev']</value>
      <webElementGuid>0431fa32-efa4-46ca-ad49-6a878107d668</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
