<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_20 (1)</name>
   <tag></tag>
   <elementGuidId>1157f381-26cb-4cff-8fe8-6c9777a19a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#390571d9-6920-453b-8f34-a021b72a62bb_cell_selected > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='390571d9-6920-453b-8f34-a021b72a62bb_cell_selected']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9fc6937-4082-469a-b855-5c6efbe1ad6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c89fcae8-a68d-436b-b1a5-1b345f9203b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>0f0a16f8-43a9-42f7-a1e4-aa6c90ea43ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7fdf8a03-4771-440c-8181-05f5152daf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2022/10/20</value>
      <webElementGuid>2600a83c-406f-4019-afe2-2ff3da64a720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sunday, November 20, 2022</value>
      <webElementGuid>f6ec7a4b-e9d8-4901-8d58-1d32ac717e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8012a337-5bd3-49fd-b78e-e4773f8fdb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;390571d9-6920-453b-8f34-a021b72a62bb_cell_selected&quot;)/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>5791d7e9-c639-4ac0-8a7f-28410eda7087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='390571d9-6920-453b-8f34-a021b72a62bb_cell_selected']/a</value>
      <webElementGuid>dc83f4a6-addb-49ed-ac14-ddca40706847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'20')])[11]</value>
      <webElementGuid>9ba1f9d6-f606-4772-aace-2f9aab004737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[4]/following::a[22]</value>
      <webElementGuid>24ae5ecd-754c-4f9a-9f23-7978bcbd2354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[4]/following::a[22]</value>
      <webElementGuid>819932e7-d6ca-4b3e-9e57-857e892fc0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- اختر نوع العملة -'])[7]/preceding::a[2]</value>
      <webElementGuid>71da214c-7865-4ef8-9f5c-5b1c752e778a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[6]/preceding::a[2]</value>
      <webElementGuid>3caeb95d-24a2-4539-9bf6-77fa0864d267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[256]</value>
      <webElementGuid>56402837-b1ce-4484-a424-4f6f3bfeece0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[115]/div/div/table/tbody/tr[4]/td/a</value>
      <webElementGuid>d03e34fe-cec6-48b5-888a-8e3c27fa2674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Sunday, November 20, 2022' and (text() = '20' or . = '20')]</value>
      <webElementGuid>b2fccb0b-7161-4d5a-9f44-77bc3e5c141f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
