<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4</name>
   <tag></tag>
   <elementGuidId>40bd8a05-e22e-4ae0-b42b-06c86eb9c791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-other-month.k-weekend.k-state-hover > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1bf9d8e8-48e4-4a8d-81b9-270f57765b2e']/table/tbody/tr[6]/td/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @title = 'Sunday, December 04, 2022' and (text() = '4' or . = '4')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f248f4cb-8276-4160-b067-c0d099a842a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>999b4731-6416-4167-a040-dc570775aa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>c239319f-2ded-4b9e-af12-9afcbd485d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>29902cd4-39fb-4e73-a9fe-2bcca676a965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2022/11/4</value>
      <webElementGuid>9b3cfb60-1e38-4166-a7ca-a1ddaeb2d66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sunday, December 04, 2022</value>
      <webElementGuid>de0ec010-f212-486a-ab62-ee418ef887ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>462873dc-6623-4e55-8665-3b758240dc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1bf9d8e8-48e4-4a8d-81b9-270f57765b2e&quot;)/table[@class=&quot;k-content k-month&quot;]/tbody[1]/tr[6]/td[@class=&quot;k-other-month k-weekend k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>6f67b6bb-d0b0-4576-9159-bb20f7380239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1bf9d8e8-48e4-4a8d-81b9-270f57765b2e']/table/tbody/tr[6]/td/a</value>
      <webElementGuid>7604eb6f-60d2-4d62-ba09-7937702530c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'4')])[23]</value>
      <webElementGuid>77018a49-b3e8-42e3-a6ea-11aeed6163f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[6]/following::a[36]</value>
      <webElementGuid>ce5e2cef-9919-4012-bf55-7df85ee97a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[6]/following::a[36]</value>
      <webElementGuid>940bc089-404f-4819-818b-aa5343d1c9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[302]</value>
      <webElementGuid>b8ecc8d4-dc75-40b5-8124-2f4104e03a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[119]/div/div/table/tbody/tr[6]/td/a</value>
      <webElementGuid>525afc67-f208-466c-bca0-b91b8dec2115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Sunday, December 04, 2022' and (text() = '4' or . = '4')]</value>
      <webElementGuid>e9bddda8-93b3-414f-aea0-7a8114cd059b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
