<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__childitem.AnswerAr</name>
   <tag></tag>
   <elementGuidId>1291c179-eed3-4883-8aa8-fdb5c6dab0dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93fb2a5b-79e4-4c20-ae38-ccf7a3345ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c63c2ca7-aa70-4437-9c93-0584486c53b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAnswer</value>
      <webElementGuid>910fae75-0b42-4277-908a-b98bbe7615e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>childitem.AnswerAr</value>
      <webElementGuid>384bdb0e-4920-4073-bf4f-8d6ebbae2254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13df14e6-af1f-4e9e-994f-f1c1886c6f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdControls_160&quot;)/input[@id=&quot;txtAnswer&quot;]</value>
      <webElementGuid>33641ad9-9f2b-46d2-b20a-4016b3e370f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3690b922-8711-4e10-ac4a-bfe8f1532c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>afc14d5d-6a97-47d3-809d-4890f0685f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAnswer</value>
      <webElementGuid>9e6d6fad-4551-40ee-b306-85c066ae192b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>childitem.AnswerAr</value>
      <webElementGuid>9ec632bb-173f-4790-a1dd-f63e7fa285bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa1a6f75-c107-49fe-91b8-8b6297ce8280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdControls_154&quot;)/input[@id=&quot;txtAnswer&quot;]</value>
      <webElementGuid>6e489da0-1d96-4bf2-8201-d01a72762707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAnswer']</value>
      <webElementGuid>f4a71ce2-5dfe-497d-b8df-fc5a9ffb4ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_160']/input</value>
      <webElementGuid>91f0ccf0-08b4-40b2-b2e8-bb13a5b8b332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>878fcfeb-b594-4a5b-9487-9a2d3544e705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtAnswer' and @name = 'childitem.AnswerAr' and @type = 'text']</value>
      <webElementGuid>9daa4b24-7fad-4964-bfe0-6958249dd7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='txtAnswer'])[3]</value>
      <webElementGuid>80294282-e2b7-4455-a939-41caa8b30d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_154']/input</value>
      <webElementGuid>0a444529-9277-4ea4-b28a-9a2fdfeb1eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>bf04c87a-3995-45fc-8acd-7c1a0f154a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
