<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fdUpload-138</name>
   <tag></tag>
   <elementGuidId>16b41ae4-05e7-4862-87ec-ec2e904a212e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fdUpload-138</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fdUpload-138']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fddd610-8c62-42c9-98e6-a04aa675c5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fdUpload-138</value>
      <webElementGuid>304a1d0a-0122-48c8-b629-fdc549013d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fdUpload-138</value>
      <webElementGuid>ac103b4c-99ad-4aa5-845b-8c3c84405baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>507f6ab5-3394-4788-adbe-95ad5564a5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>62391098-96ca-47f0-a8c1-bff72a50b447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>00123ad0-63f3-482a-973a-87c3b263fe64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>845d696f-3292-434f-80cd-09ccc2a36224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdUpload-138&quot;)</value>
      <webElementGuid>2f72a85b-fc61-46b9-b47f-3b783a484dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fdUpload-138']</value>
      <webElementGuid>bbc84afc-d6de-4b98-9d3e-ff8643dc8f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='tdControls_138']/div/div/input</value>
      <webElementGuid>e713019f-ef94-40bd-abfb-208bdb94b6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/input</value>
      <webElementGuid>5e240087-fc9c-4701-80aa-8dd1779207a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fdUpload-138' and @name = 'fdUpload-138' and @type = 'file']</value>
      <webElementGuid>024d0c2b-4427-487d-a7ab-56224a6409b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
