<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Disclaimervalue</name>
   <tag></tag>
   <elementGuidId>4788470e-a889-4634-a768-85b42078c4d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chkDisclaimer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chkDisclaimer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1306faa0-b16c-48bd-989d-5af53f852b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a2a116a7-ddbe-41a0-a02b-4d3b2e29aeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Disclaimervalue</value>
      <webElementGuid>5e61e423-3d86-489d-a6b4-e1d82a8b6c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chkDisclaimer</value>
      <webElementGuid>064e1545-7e1f-49f6-a654-fbc53b71f32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chkDisclaimer&quot;)</value>
      <webElementGuid>2b8029aa-ae42-4732-8363-6fd6a320672f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chkDisclaimer']</value>
      <webElementGuid>d6819723-6df3-4b35-b5ab-95c142129605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divchkDisclaimer']/input</value>
      <webElementGuid>72f2129b-41ad-4c3a-b441-0d3612db7493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>47b33a3e-20dd-4cbe-ac5a-cbe82d3c98a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Disclaimervalue' and @id = 'chkDisclaimer']</value>
      <webElementGuid>684e3282-7959-433a-8f1f-894924f6a2f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
