<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>45e2e55d-6ddb-4591-8888-8486866c6eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='87a6cd17-1eec-495b-a2da-ee24fb358517_cell_selected']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#87a6cd17-1eec-495b-a2da-ee24fb358517_cell_selected > a.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85848354-28bc-4cff-a1c4-c23be52f3d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>57c7eecf-1908-48ff-9bb8-d9491b4e3494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>942aac2d-c542-44fd-9cb7-3f731dd03fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>812b3282-0bad-478c-bfc8-03c46ff258d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2022/11/5</value>
      <webElementGuid>ba928345-b1c5-4c34-bc6d-4f95b44fe5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Monday, December 05, 2022</value>
      <webElementGuid>5d6ce037-0f4c-4e0d-a159-c6584180317f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bdf243fd-80d6-4d3d-a5e9-567bb1b2ba27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;87a6cd17-1eec-495b-a2da-ee24fb358517_cell_selected&quot;)/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>c52c746b-a188-4929-9695-6409b25dc59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='87a6cd17-1eec-495b-a2da-ee24fb358517_cell_selected']/a</value>
      <webElementGuid>19a76a0c-3a26-489c-9a47-eebaaebc3a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'5')])[7]</value>
      <webElementGuid>290def65-ab72-4637-ad87-2ff5527ca503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::a[9]</value>
      <webElementGuid>782f3954-a75b-4934-b507-7ec755cce825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::a[9]</value>
      <webElementGuid>2aaf94c7-01fb-4f35-981f-d9bedec2ed55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[35]</value>
      <webElementGuid>f8868708-e2aa-4582-a08c-1c52e151cf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[35]</value>
      <webElementGuid>2dae9c60-6301-4c0c-9d77-83a159f2677d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[111]</value>
      <webElementGuid>815f3dc6-2fcf-40ba-8460-6743d49608c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>824b3eab-dd05-4175-a95f-fd1049530b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Monday, December 05, 2022' and (text() = '5' or . = '5')]</value>
      <webElementGuid>6cb95602-3bd5-497a-82e7-1564ef8a8c82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
