<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attach Tab</name>
   <tag></tag>
   <elementGuidId>cb7a05ae-8813-45c6-8e5a-0529c17c0e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAttachmentTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAttachmentTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a91b1193-e9fc-49e3-8ccb-be08dc6de813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAttachmentTab</value>
      <webElementGuid>72289630-4d8a-4cfa-b1d9-e635ab44b1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subtab</name>
      <type>Main</type>
      <value>5B</value>
      <webElementGuid>511a30aa-7221-4144-a9f4-b861a5fa5943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setTabClassActive(event, '2', '5B', '', true, true);</value>
      <webElementGuid>62a5886d-7e16-42ca-8f79-ac772cb37cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subcircle classification_sub2 smetablinks subcirclevisited</value>
      <webElementGuid>e5a2473c-958e-4ed3-b77f-c754e6b2ff9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2المرفق</value>
      <webElementGuid>93f05f0d-b507-4add-901b-ac3ba7551cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAttachmentTab&quot;)</value>
      <webElementGuid>bf9e8929-1315-48a3-a06c-9209e2a648f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAttachmentTab']</value>
      <webElementGuid>aa0065aa-14f2-43b0-92af-88a91a0a54ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tb_Main_Classification']/div[3]/button</value>
      <webElementGuid>26b452dc-8a50-4be6-b257-895e30849db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[2]/following::button[1]</value>
      <webElementGuid>da742d1a-0caa-442d-8d98-2fa6f54570d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف'])[1]/following::button[2]</value>
      <webElementGuid>900d1a04-bd75-408a-8dc7-f954882fcd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التقني'])[1]/preceding::button[1]</value>
      <webElementGuid>1ef2bc4f-efe4-4a4e-8360-a95eb8ef6cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>081c9c48-959e-41a2-8d34-0ecd9edf8e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAttachmentTab' and (text() = '2المرفق' or . = '2المرفق')]</value>
      <webElementGuid>a0310314-da1d-4c03-8ed3-40502936cf6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
