<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calender Read</name>
   <tag></tag>
   <elementGuidId>3c00849a-7c1d-40d3-9a70-b437ac42ae69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;expdatepicker&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/span[@class=&quot;k-widget k-datepicker k-header expdatepicker&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-focused&quot;]/input[@class=&quot;expdatepicker k-input&quot;][count(. | //input[@type = 'text' and @class = 'expdatepicker k-input' and @onkeydown = 'javascript:return false;' and @name = 'expdatepicker' and @data-role = 'datepicker' and @role = 'combobox' and @aria-expanded = 'false' and @aria-disabled = 'false']) = count(//input[@type = 'text' and @class = 'expdatepicker k-input' and @onkeydown = 'javascript:return false;' and @name = 'expdatepicker' and @data-role = 'datepicker' and @role = 'combobox' and @aria-expanded = 'false' and @aria-disabled = 'false'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='expdatepicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b32fdc7a-708e-4341-b962-d2b528259328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33d2d850-7ec5-4d3d-bdb7-bc6528bf6e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expdatepicker k-input</value>
      <webElementGuid>1b5151ad-2910-49fa-8ae9-5b697fae12ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>javascript:return false;</value>
      <webElementGuid>76536fe6-f3ed-4e79-96b9-06da0c10e66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expdatepicker</value>
      <webElementGuid>8abd8384-7c53-4436-87a8-46be7e234ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>ac973aab-1339-4383-983c-96823c3956ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>54c37a2b-7486-44af-bb88-e9da732856c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a72c2245-c215-4457-920a-1586d7cf3646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ae2a851-28ca-4efa-a4b0-fe0021348036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/span[@class=&quot;k-widget k-datepicker k-header expdatepicker&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-focused&quot;]/input[@class=&quot;expdatepicker k-input&quot;]</value>
      <webElementGuid>511cc340-735b-4f55-87c8-369b1f9ee428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='expdatepicker']</value>
      <webElementGuid>95c0eeda-076c-46ca-9475-82be848bf68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']/div/span/span/input</value>
      <webElementGuid>afb43e38-3bb0-492b-b6dc-afdea74b5583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/span/span/input</value>
      <webElementGuid>c7bbc0f9-df97-4e73-8826-fb4b903e8b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'expdatepicker']</value>
      <webElementGuid>f8d42f53-4408-4118-89b2-6a81fef211b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
