<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calender Read</name>
   <tag></tag>
   <elementGuidId>3c00849a-7c1d-40d3-9a70-b437ac42ae69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;expdatepicker&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/span[@class=&quot;k-widget k-datepicker k-header expdatepicker&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-focused&quot;]/input[@class=&quot;expdatepicker k-input&quot;][count(. | //input[@type = 'text' and @class = 'expdatepicker k-input' and @onkeydown = 'javascript:return false;' and @name = 'expdatepicker' and @data-role = 'datepicker' and @role = 'combobox' and @aria-expanded = 'false' and @aria-disabled = 'false']) = count(//input[@type = 'text' and @class = 'expdatepicker k-input' and @onkeydown = 'javascript:return false;' and @name = 'expdatepicker' and @data-role = 'datepicker' and @role = 'combobox' and @aria-expanded = 'false' and @aria-disabled = 'false'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='expdatepicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0dbf714-e422-4018-92e0-78557c8e590d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>52cd8c43-82f3-4a7d-831a-8cddddaf6bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expdatepicker k-input</value>
      <webElementGuid>3e22b8a2-911b-4a12-a38e-f5c7a3a74a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>javascript:return false;</value>
      <webElementGuid>336eb21c-4d66-44f6-802c-8b1719c97f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expdatepicker</value>
      <webElementGuid>7a13cca5-2522-4b3c-b761-62e5d7b93674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>7d9b174a-6703-42b7-8e1a-5148398890bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>57f1627a-b58a-4510-baaf-37bb0a024dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccbda68c-7e1a-4310-aef1-cbe1dbff127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a0d2cb9-0bd8-434a-8544-d9c768daae35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)/div[@class=&quot;pull-left mr-10 br-less&quot;]/span[@class=&quot;k-widget k-datepicker k-header expdatepicker&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-focused&quot;]/input[@class=&quot;expdatepicker k-input&quot;]</value>
      <webElementGuid>3ee143b4-ed47-489b-ae26-81e7d6bbdfa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='expdatepicker']</value>
      <webElementGuid>db208029-5175-444f-81d1-437892874114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']/div/span/span/input</value>
      <webElementGuid>9ed0869c-9ee2-4dad-8abc-b8a4b8efa1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/span/span/input</value>
      <webElementGuid>0072de62-1b63-49ee-b730-ec2f53335ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'expdatepicker']</value>
      <webElementGuid>b36e7025-65b9-4fd8-8bd4-d30211558f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
