<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit</name>
   <tag></tag>
   <elementGuidId>a906403a-7a69-4530-a836-99a2ecb6ee48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick='EditOwnershipDetailsRecord(this);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4b803d6a-5eca-4c46-b231-9b2fcfbcdedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-database-edit2 grdViewIcon grdCursorStyle</value>
      <webElementGuid>18d2dc0b-9e0f-4718-8695-815d34e45d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>تحرير السجل</value>
      <webElementGuid>57c43fdd-c769-42fd-bdea-8240c8316642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EditOwnershipDetailsRecord(this);</value>
      <webElementGuid>b9f43433-c7f7-4ac2-959e-10ac89806c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OwnershipGrid&quot;)/div[@class=&quot;k-grid-content k-auto-scrollable&quot;]/table[1]/tbody[1]/tr[1]/td[13]/i[@class=&quot;icon-database-edit2 grdViewIcon grdCursorStyle&quot;]</value>
      <webElementGuid>f8f23d14-c84d-49f3-9112-a560424d9801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='EditOwnershipDetailsRecord(this);']</value>
      <webElementGuid>656efbb3-2c6b-4590-ac76-6704714a8534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OwnershipGrid']/div[2]/table/tbody/tr/td[13]/i</value>
      <webElementGuid>91a88cb0-c2e6-4862-a0b5-3696c9b1ec52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/i</value>
      <webElementGuid>372faabd-b2b7-490e-b8da-0418a2950680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'تحرير السجل']</value>
      <webElementGuid>b94da30d-5f40-4d49-aa05-0c3173e8119e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
