<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grid icon</name>
   <tag></tag>
   <elementGuidId>f3113b81-1438-4fba-966e-9f88deb95d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdSMEClassificationAgentActivity_active_cell > label.k-checkbox-label.k-no-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d4254011-82f5-43af-ae92-8e775249f0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox-label k-no-text</value>
      <webElementGuid>2513be5c-ef04-4037-9b6c-e3cb046069d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>grdSMEClassificationAgentActivity4f56a5e6-3fe7-4417-a67b-c255446f96e6</value>
      <webElementGuid>0f224cdb-2180-40d0-9123-371b867e8ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>6c784b60-8898-4842-aa66-5d2dcd82260f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)/label[@class=&quot;k-checkbox-label k-no-text&quot;]</value>
      <webElementGuid>f34e7a06-7519-42af-85f9-d4a2cab61c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='grdSMEClassificationAgentActivity_active_cell']/label</value>
      <webElementGuid>0dce1858-80a0-4970-bc61-3753c279bd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ابحث باسم النشاط أو كود النشاط'])[2]/following::label[1]</value>
      <webElementGuid>2b093aca-da12-43a2-aab7-ebb7d8b8d19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[2]/following::label[2]</value>
      <webElementGuid>8c37c872-9cac-4f1f-a0f2-4d6035019907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SME Activity ID'])[2]/preceding::label[1]</value>
      <webElementGuid>b3e84623-e548-4628-91f5-9f9e4d4db2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز النشاط'])[2]/preceding::label[1]</value>
      <webElementGuid>08e75247-9351-4d27-8e2c-bea98f4633e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/table/thead/tr/th/label</value>
      <webElementGuid>9ffe41fe-20e2-4f93-b301-d256fe1616f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '​' or . = '​')]</value>
      <webElementGuid>ee9003a4-f057-4d5a-a199-e8bd575a6ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
