<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__StreetAddress</name>
   <tag></tag>
   <elementGuidId>0abb8ae1-b434-4315-ab22-69e576b84bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtStreetAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtStreetAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be44eeae-02fc-4c3e-89dc-4537bfa7aaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3a035e2-722c-4745-a076-ef659d6aa861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36ed5259-9973-46d6-b962-2f6a239a1c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص إنجليزي صحيح</value>
      <webElementGuid>3ebce367-3835-4fca-8b3a-dc4905925daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9 ]+$</value>
      <webElementGuid>d6067845-fda0-42c8-b5e5-3136000d6a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم الشارع باللغة الإنجليزية مطلوب</value>
      <webElementGuid>2465882d-1cbb-4cd9-9e22-37e3907a1197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtStreetAddress</value>
      <webElementGuid>20f21cad-c495-4c15-ad98-939bda4b9822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>0d18ca9d-c5c4-41eb-9473-2ef296050348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StreetAddress</value>
      <webElementGuid>da7fe058-bfed-4f0a-88f3-6e0b371bbe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الشارع باللغة الإنجليزية</value>
      <webElementGuid>a7ec849a-6ce9-493b-ad00-7a3ce0c6a46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9e33fe2-6bc0-443a-ae27-fa7eace76998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtStreetAddress&quot;)</value>
      <webElementGuid>c928a767-e4ea-4341-99c1-8a8ca3e237c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtStreetAddress']</value>
      <webElementGuid>74349f30-f944-4c35-a421-a49c3e0f737c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header2Div']/div[4]/div[2]/input</value>
      <webElementGuid>8063ac50-23d6-456d-94ba-570a3857c524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>9abe1ef0-93d7-442c-ad8d-f44b4b4e099b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtStreetAddress' and @name = 'StreetAddress' and @placeholder = 'اسم الشارع باللغة الإنجليزية' and @type = 'text']</value>
      <webElementGuid>6343641c-cdbe-4e37-930b-bcda1405d92e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
