<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BrandNameAr</name>
   <tag></tag>
   <elementGuidId>312f3c62-0b38-482a-ba81-ebfca5f1c69d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBrandNameAr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBrandNameAr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b7906d4-0d2c-4b15-bfb3-92f81cd4c7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31347796-4dd9-4252-a63a-3e44d4f6687d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e41fc9ec-ab6d-440d-ac90-cc6cc479d6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص عربي صحيح</value>
      <webElementGuid>13715faf-f2ac-49e9-b57b-0baab3a9fbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[\u0621-\u064A 0-9]+$</value>
      <webElementGuid>3b8248ee-74df-413a-9d5d-c48d84579e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBrandNameAr</value>
      <webElementGuid>65629a3a-74b4-44ad-8ca4-9ed87453ddb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2c8cded2-b6d5-4bca-bdc7-9f8ed96f4297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BrandNameAr</value>
      <webElementGuid>94515d46-f1b0-4ab6-93c9-4903204068c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الاسم التجاري للمنشآة باللغة العربية</value>
      <webElementGuid>9189e941-aa63-4124-9bdd-8e5e06086593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e340afb9-df8f-438a-b437-9b292ad0c9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBrandNameAr&quot;)</value>
      <webElementGuid>03c79111-6674-4a0b-8e62-cb696a6e6558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBrandNameAr']</value>
      <webElementGuid>86700726-24ea-44e0-8cbc-b255c4d87add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header1Div']/div[2]/div[2]/input</value>
      <webElementGuid>a5411c94-5268-4f2f-8b75-bbdd6e7c8296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>226ed34a-9db9-438f-968d-e180f931d4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtBrandNameAr' and @name = 'BrandNameAr' and @placeholder = 'الاسم التجاري للمنشآة باللغة العربية' and @type = 'text']</value>
      <webElementGuid>2651f501-8d83-48a0-a528-2de9a9d0201e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
