<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CompanyHierarchy_ParentCompanyName</name>
   <tag></tag>
   <elementGuidId>74a34917-1321-4daf-84e4-30db9323bf3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCompanyHierarchy_ParentCompanyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCompanyHierarchy_ParentCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dcb5c8c-5461-42d1-822f-992bd9e191a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>51c77106-3e12-4d72-bd69-ba6fc9aa51c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCompanyHierarchy_ParentCompanyName</value>
      <webElementGuid>bbea8c2d-6fe6-41d2-bd0a-cedc39f9457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9f5b2d61-c6ce-48c1-a014-58fadf19915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyHierarchy_ParentCompanyName</value>
      <webElementGuid>158723e3-d1a5-44f3-96f8-dd1560f31742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الشركة الام</value>
      <webElementGuid>657dfaab-0245-495b-a5ca-023710cc96e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dd3b13d1-18f6-493a-83db-511c9e43843c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de64c23f-5423-410c-9621-98c5f12db280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCompanyHierarchy_ParentCompanyName&quot;)</value>
      <webElementGuid>3b2085b2-c926-4dc5-931d-9cb7d8d0f32b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCompanyHierarchy_ParentCompanyName']</value>
      <webElementGuid>63715a5f-18f4-4e1c-b25b-78471b9de975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCompanyHierarchyDetails']/div/div/div/input</value>
      <webElementGuid>d8944235-9eac-41e1-aad5-cf0ef668c216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>8b4fafcc-1277-4b9b-8d18-2c1ac3caf0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCompanyHierarchy_ParentCompanyName' and @name = 'CompanyHierarchy_ParentCompanyName' and @placeholder = 'اسم الشركة الام' and @type = 'text']</value>
      <webElementGuid>810cac59-a86f-4498-9664-3e10dc36ccbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
