<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GeoLocation</name>
   <tag></tag>
   <elementGuidId>927f05cf-25c8-4b9b-ab02-7eeabbfb87f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtGeoLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtGeoLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcd08b35-885c-4cc6-a2ef-56b0972417a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cfbc3686-1e84-465e-89a2-a80315256d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e4ceeec-dd13-4dda-b8e1-38ec119b0d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>يرجى إدخال عنوان URL صحيح</value>
      <webElementGuid>07f91281-ab6a-498d-a24c-9453e869cb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&amp;'\(\)\*\+,;=.]+$</value>
      <webElementGuid>8cde3f3d-5de9-47db-8ec3-5b4efbcc9f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل الرابط الجغرافي لمقر المنشأة مطلوب</value>
      <webElementGuid>460c249d-0393-4f48-bbeb-f29b0ac04f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtGeoLocation</value>
      <webElementGuid>4cfb3017-1bcf-4964-ab7b-c31f1dc2da14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GeoLocation</value>
      <webElementGuid>5722440c-b1f0-4914-827e-5377e83ab76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الرابط الجغرافي لمقر المنشأة</value>
      <webElementGuid>7727c1cd-8b8b-4474-967e-afd62bbb14cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c750f8a5-5449-43d8-87a5-bea2370df429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtGeoLocation&quot;)</value>
      <webElementGuid>c3cc8cdf-942c-4cf5-b229-5d9c744c8b53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtGeoLocation']</value>
      <webElementGuid>e7f3ec5e-2e77-45e2-bdd5-a760719076a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header2Div']/div[6]/div[2]/input</value>
      <webElementGuid>61285f04-c109-4e5c-8ce0-c925564bed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>3252a8ef-9959-49fa-9e41-b53fddf9c990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtGeoLocation' and @name = 'GeoLocation' and @placeholder = 'الرابط الجغرافي لمقر المنشأة' and @type = 'text']</value>
      <webElementGuid>ab39be23-f4af-419b-9526-ba960ef5faa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
