<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CompanyName</name>
   <tag></tag>
   <elementGuidId>a5ab8f6d-f558-40a6-bd8c-2e70f353e0f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCompanyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f274800-7d78-4a07-9c6f-4e9a6646941a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f3bdf3ed-bf15-4a5a-9dde-9b17862b9086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30e1193b-8f74-405a-81e3-839ce2d99409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص إنجليزي صحيح</value>
      <webElementGuid>a7fea8d9-75de-40f0-b2bc-e47cccd3907d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9 ]+$</value>
      <webElementGuid>77bb4b15-6876-4246-b8e2-5cab6ed3441c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم الشركة باللغة الإنجليزية مطلوب</value>
      <webElementGuid>d492c579-a540-4c71-a7e1-6c910b66147a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCompanyName</value>
      <webElementGuid>73a2f372-72ba-40dd-9288-8d3a2bc90519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>abadb824-e911-4cda-8ecb-f4dbf49cf8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyName</value>
      <webElementGuid>0a96a81a-2d1c-4fef-8907-42de135b9c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الشركة باللغة الإنجليزية</value>
      <webElementGuid>b5f3f4a5-a8cd-4ae2-91f9-ba70bfba7ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae6b9256-39eb-4dcb-b3a5-b8504177d56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCompanyName&quot;)</value>
      <webElementGuid>5e6c482a-8783-455a-b80c-48464af6d65c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCompanyName']</value>
      <webElementGuid>22d02fef-0719-4445-9487-fc212e1dc59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header1Div']/div/div/input</value>
      <webElementGuid>b6a12b4e-231b-4ec3-a5a2-541b1bb29634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>b6f297ed-d11a-4102-9baf-29d522d7edcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtCompanyName' and @name = 'CompanyName' and @placeholder = 'اسم الشركة باللغة الإنجليزية' and @type = 'text']</value>
      <webElementGuid>916b2dbd-e784-48b0-920e-1fa46f688265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
