<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__StreetAddressAr</name>
   <tag></tag>
   <elementGuidId>b30dcc68-8d14-40ab-8528-2665bf575ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtStreetAddressAr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtStreetAddressAr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27c817e9-cd1f-4c7e-87d7-c4452eedc4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c7d6f11-36b8-4ba4-a91f-60e7461876c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d5bbe16-8b4d-4be1-a44f-153f7c46f169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>الرجاء إدخال نص عربي صحيح</value>
      <webElementGuid>eb28478c-1f56-4c9d-a437-4d467231f2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[\u0621-\u064A 0-9]+$</value>
      <webElementGuid>5dc6c17e-18e2-4ccb-8dd7-c300dbe0b78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل اسم الشارع باللغة العربية مطلوب</value>
      <webElementGuid>4b142d7f-dba2-44c0-9a15-6c6c9521df02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtStreetAddressAr</value>
      <webElementGuid>dff029f0-8987-421f-b6f3-9baff72eaf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>c93af6ad-e569-4d9b-8b5f-5427559786ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StreetAddressAr</value>
      <webElementGuid>cbbc9c63-2554-442a-a8ae-d80cfeed5ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>اسم الشارع باللغة العربية</value>
      <webElementGuid>14f1be65-3e21-4370-a604-85702dbb08ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19b545bb-5cf2-40d3-9645-345ff58ba7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtStreetAddressAr&quot;)</value>
      <webElementGuid>29050408-b9b1-4762-86e6-b23a1424dd30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtStreetAddressAr']</value>
      <webElementGuid>ea2aa235-c696-4d1a-9519-bdaafa8b2f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header2Div']/div[5]/div/input</value>
      <webElementGuid>b3c80703-4802-4a1a-a2d8-37417aabcca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>23653874-4426-480c-99ac-6cc43f083283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtStreetAddressAr' and @name = 'StreetAddressAr' and @placeholder = 'اسم الشارع باللغة العربية' and @type = 'text']</value>
      <webElementGuid>d916b3e6-8889-491c-8d1f-b3dd8c2f55c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
