<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BuildingNumber</name>
   <tag></tag>
   <elementGuidId>ac976de9-9267-4c4e-8a1f-f4fb0a1e7481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBuildingNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBuildingNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e91d0873-c7d3-4c43-af7c-78446548487f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a29d31c0-0996-40ea-978a-4d16d9a50356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9cf322d-d990-4cb8-96b6-374453d6bacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل رقم المبنى مطلوب</value>
      <webElementGuid>805b8dca-7bee-4e42-a52e-b48fa7cf469b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBuildingNumber</value>
      <webElementGuid>ce88c721-6ba8-4e68-b74f-a4ad1b3ac068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>e8390c6d-4416-4827-81ff-d1696e9d82e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BuildingNumber</value>
      <webElementGuid>9b10f483-ba20-4700-a156-ea0891970e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم المبنى</value>
      <webElementGuid>5c18a7fb-d7d8-4bc6-8cef-e800edaa1250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e9d33ea-2d32-4e46-92bb-fb8fe1796f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4599</value>
      <webElementGuid>d5bbbcf7-9750-4c14-988d-83fe363f1a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBuildingNumber&quot;)</value>
      <webElementGuid>128dbaad-ae3d-4892-8b11-aca092e8630d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBuildingNumber']</value>
      <webElementGuid>c54a4ee6-1673-46c7-a3c0-02368c4904b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header2Div']/div[4]/div/input</value>
      <webElementGuid>c49e4b03-c1e9-46a4-9028-6fcb73c94d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>480c9105-4cb2-40d0-8af9-480dfd01ed8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtBuildingNumber' and @name = 'BuildingNumber' and @placeholder = 'رقم المبنى' and @type = 'text']</value>
      <webElementGuid>d23c15c6-a66b-421f-96e4-037cec5eef5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
