<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_focus</name>
   <tag></tag>
   <elementGuidId>80b34f6d-5942-4346-a897-cabc894d60a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.control-label.mandatory.pad-right-0.pad-left-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CompanyDetails_Header6Div']/div[3]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>99e06ff3-b3d3-48a3-8f65-197e47a781ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label mandatory pad-right-0 pad-left-0</value>
      <webElementGuid>ccc7d5c4-eed8-4252-afbe-4b9a9da03191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>هل منشآتك يوجد لها درجة في المحتوى المحلي؟</value>
      <webElementGuid>e55eced2-1e24-47d7-b214-72af572a751c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyDetails_Header6Div&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-6 col-lg-6 col-xs-12 col-sm-12 form-group&quot;]/label[@class=&quot;control-label mandatory pad-right-0 pad-left-0&quot;]</value>
      <webElementGuid>653575c4-aa6d-43ff-afe5-5fd07b523aff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header6Div']/div[3]/div/label</value>
      <webElementGuid>1327c90d-a388-401e-a6b0-74e77e1a6665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إجمالي عدد الموظفين'])[1]/following::label[1]</value>
      <webElementGuid>cb223ae3-4252-4eae-b9bc-81137de06f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الموظفين السعوديين بالمنشأة'])[1]/following::label[2]</value>
      <webElementGuid>926684cc-417d-4ded-83b1-2100e7f6a336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نعم فعلا'])[2]/preceding::label[1]</value>
      <webElementGuid>0bf02647-5a0a-45c1-93d6-21022ce56208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا'])[2]/preceding::label[2]</value>
      <webElementGuid>499426c6-b19b-4551-a660-e557446a2b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='هل منشآتك يوجد لها درجة في المحتوى المحلي؟']/parent::*</value>
      <webElementGuid>a52f134b-842f-46d5-b3ad-f19d6a3cad59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/form/div/div[3]/div/label</value>
      <webElementGuid>1039985f-b98b-4532-989d-d2355a4b42da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'هل منشآتك يوجد لها درجة في المحتوى المحلي؟' or . = 'هل منشآتك يوجد لها درجة في المحتوى المحلي؟')]</value>
      <webElementGuid>00ebf0e6-1260-421b-985e-2b6123748dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
