<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>b3cb7551-5569-44c8-99ba-76aca8e8e4a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.k-checkbox-label.k-no-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='grdSMEClassificationManufacturerActivity_active_cell']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bc301bb2-cc73-4118-8197-e88a545c629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox-label k-no-text</value>
      <webElementGuid>301a4b7c-0200-45d5-b61a-455d910b5d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>grdSMEClassificationManufacturerActivity4d617f90-f157-4456-b181-7626821caf29</value>
      <webElementGuid>d2421756-4590-4b09-9b35-2d53cc69d76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>e008c61f-2df9-4539-8e59-ba48cf97d2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationManufacturerActivity_active_cell&quot;)/label[@class=&quot;k-checkbox-label k-no-text&quot;]</value>
      <webElementGuid>adcfb73c-9a8a-4256-9991-190078d29d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='grdSMEClassificationManufacturerActivity_active_cell']/label</value>
      <webElementGuid>96dd5e5c-1827-48d2-bb34-4b203eeb8986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ابحث باسم النشاط أو كود النشاط'])[1]/following::label[1]</value>
      <webElementGuid>6a3de809-5fe2-4c2f-8b2b-f29d490abf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[1]/following::label[2]</value>
      <webElementGuid>0efa7e36-297e-40d1-b444-10e6932a6b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SME Activity ID'])[1]/preceding::label[1]</value>
      <webElementGuid>4642b668-994d-48a9-a2cf-31971aa5a755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز النشاط'])[1]/preceding::label[1]</value>
      <webElementGuid>ec59cc63-3a11-4a9d-b072-7393e4c4f509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='​']/parent::*</value>
      <webElementGuid>01ec4bab-257d-40e7-9180-f6fd9ad755d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/label</value>
      <webElementGuid>53746674-5d12-48a6-9763-615e39cca411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '​' or . = '​')]</value>
      <webElementGuid>53423adc-3532-43a9-9d79-ec11ea542ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
