<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_company4</name>
   <tag></tag>
   <elementGuidId>96da6ce6-9e93-4910-a23b-b9a1c12c40c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-12.col-lg-12.col-xs-12.col-sm-12.fl-right.radio-toolbar.no-padding-h.no-margin-h > label.padding10-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CompanyDetails_Header6Div']/div[3]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ffeb3333-0099-44ef-aab2-30925e49c1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rdIsOrganizationHaveContentscoreYes</value>
      <webElementGuid>90e6f5ba-2f14-45f1-84a8-7d3cf927ce41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding10-radio</value>
      <webElementGuid>97d91560-6082-4c94-ac1e-41a37f38604d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>نعم فعلا</value>
      <webElementGuid>33525436-536d-489e-85ce-82af26595c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyDetails_Header6Div&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-6 col-lg-6 col-xs-12 col-sm-12 form-group&quot;]/div[@class=&quot;col-md-12 col-lg-12 col-xs-12 col-sm-12 fl-right radio-toolbar no-padding-h no-margin-h&quot;]/label[@class=&quot;padding10-radio&quot;]</value>
      <webElementGuid>ba258f64-5c31-44e0-88a3-3a58f80d36b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyDetails_Header6Div']/div[3]/div/div/label</value>
      <webElementGuid>03d42464-e9bb-496e-b116-f67db65a615a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هل منشآتك يوجد لها درجة في المحتوى المحلي؟'])[1]/following::label[1]</value>
      <webElementGuid>1fcbc8da-d884-4ddf-a99d-dfe1e97992b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إجمالي عدد الموظفين'])[1]/following::label[2]</value>
      <webElementGuid>69fb652a-a6f4-4da6-af45-667136538307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا'])[2]/preceding::label[1]</value>
      <webElementGuid>b5026833-79f2-481a-b31e-8ba556d40a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='درجة المحتوى المحلي'])[1]/preceding::label[2]</value>
      <webElementGuid>f0c087af-afb3-4125-b3a5-5d8e16372289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>3365ed46-f7f7-4fde-850d-30f3134efb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'نعم فعلا' or . = 'نعم فعلا')]</value>
      <webElementGuid>ef96f8f9-24e0-4e9c-b58b-7be03a868336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
