<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_grid</name>
   <tag></tag>
   <elementGuidId>4b800bba-b579-4405-aba8-9205b72849ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;divAgent&quot;]/div[3]/div[3]//tbody/tr[1]/td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grdSMEClassificationAgentActivity_active_cell > label.k-checkbox-label.k-no-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dc999729-c8ea-43a7-b595-807b6dadc70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>04f8830f-5435-4b70-b506-7c6fc9ceea40</value>
      <webElementGuid>64503660-69ea-4681-9f00-8f5435801d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-checkbox-label k-no-text</value>
      <webElementGuid>01623ce5-f54c-4028-be9f-98e1a8b5b69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>c4da9f8f-5115-4d64-a0df-1976d6a2c675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)/label[@class=&quot;k-checkbox-label k-no-text&quot;]</value>
      <webElementGuid>e9687738-653f-4fa5-b368-dbe7fd089c8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grdSMEClassificationAgentActivity_active_cell']/label</value>
      <webElementGuid>490f6b3d-d458-4928-a26d-6f6d019afc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم النشاط'])[2]/following::label[1]</value>
      <webElementGuid>597323cf-19d4-47cb-8f80-0d3bfce623cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز النشاط'])[2]/following::label[1]</value>
      <webElementGuid>24a97317-3273-4eb5-ba88-6debc7f1e5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انتاج أنواع لحوم الدواجن والأرانب والطيور الطازجة'])[1]/preceding::label[1]</value>
      <webElementGuid>ef1cc87b-8265-436b-af75-bf1c3b2c59e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/preceding::label[1]</value>
      <webElementGuid>a366e86d-d629-46f5-bd45-b57e768798c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label</value>
      <webElementGuid>b112371e-a4f5-4c9a-9fbc-776d0d1ff31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '​' or . = '​')]</value>
      <webElementGuid>1f7a7b7c-1fca-417a-ad1d-dc143f927423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
