<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_(61)</name>
   <tag></tag>
   <elementGuidId>68c8bf07-4918-48e1-9ea3-68f327aba9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ddlCountryOwnershipMgmnt_PhCode_listbox']/li[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f943499e-d450-48ca-a167-11c48e4e7eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d4bf1b2a-b279-49ab-9d9f-a6ce0e158ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fe673700-5d19-4510-9ff1-32cc1761fcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>94e8b556-6618-41f9-8f54-e9939fa113c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>4316bcaf-c4a2-408d-907f-a33975e3911b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e64f1fe6-5ae8-41e1-91c7-e6b4a50f5cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>c4faf190-3a3e-457a-abe4-594dc9f53fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>أستراليا (+61)</value>
      <webElementGuid>67554bfd-ee1b-4f1b-bbee-b684cc786171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlCountryOwnershipMgmnt_PhCode_listbox&quot;)/li[@class=&quot;k-item&quot;]</value>
      <webElementGuid>01f9ac9e-9037-4355-bb53-c1391165b64d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ddlCountryOwnershipMgmnt_PhCode_listbox']/li[18]</value>
      <webElementGuid>d8c4bdad-da1a-476a-82b8-9e5f4cefaf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أروبا (+297)'])[1]/following::li[1]</value>
      <webElementGuid>a277e6b0-78e5-43aa-88d8-9ac46eca8f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أرمينيا (+374)'])[1]/following::li[2]</value>
      <webElementGuid>f4c541c2-2d0f-41e0-ad01-e1ef0fcdea2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='النمسا (+43)'])[1]/preceding::li[1]</value>
      <webElementGuid>a7133531-9905-4c4d-ba11-85db18a3abb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أذربيجان (+994)'])[1]/preceding::li[2]</value>
      <webElementGuid>84f50c82-19fe-4a7a-b12c-ff0c02b1be9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='أستراليا (+61)']/parent::*</value>
      <webElementGuid>a08b8e0a-3c76-42bf-9bca-601b515cd4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[3]/ul/li[18]</value>
      <webElementGuid>2265396d-c1dc-4cd8-8429-14e17bfcf5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'أستراليا (+61)' or . = 'أستراليا (+61)')]</value>
      <webElementGuid>7d1993f6-5f82-4226-9088-9f9c56352631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
