<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>next2</name>
   <tag></tag>
   <elementGuidId>bb31427c-05b8-49d0-b541-846ffb29d301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Address_Save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_Address_Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a8bcaa9-4ce8-41f1-9202-e035e57a311a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d9b9c26-e762-4727-9f66-0243c9f79089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>2183000f-a262-41af-88ee-110d6e0142a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Address_Save</value>
      <webElementGuid>508e8101-c21d-49d7-b1fd-36b8bf89d3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>a62935c9-ee37-4873-af31-03ad31ec07ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Address_Save&quot;)</value>
      <webElementGuid>e014a9e8-0abb-4660-9963-2d73a1f573ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_Address_Save']</value>
      <webElementGuid>dd953255-6697-4a26-9300-98650838462f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SaveCompanyDetails_Address_form']/div[3]/div/input[2]</value>
      <webElementGuid>2b04a48a-ad62-4edf-8103-bbb225078ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/input[2]</value>
      <webElementGuid>a24f1b1d-ac7c-41b3-aea1-75b398e8f775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn_Address_Save']</value>
      <webElementGuid>912bc592-f6b6-4a41-bfa4-5e627c8675ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
