<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ownership_Mobile</name>
   <tag></tag>
   <elementGuidId>30be1b32-f088-401f-923b-a864cb4ea748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnership_Mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnership_Mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54c855c0-c70c-4a93-a5a9-7f17c0ea9dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mob</value>
      <webElementGuid>681410af-df30-4341-8cb8-52d44f149f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>919e5b17-288c-4bd1-b8ae-ebb25e76db94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل رقم الجوال مطلوب</value>
      <webElementGuid>5a77c415-15f9-46ab-b6ce-d81dacdd77c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnership_Mobile</value>
      <webElementGuid>599ad4cc-9f98-46e6-9893-bd7721ce7c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>57c6343a-2065-4bd1-9b23-35594f2f3d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ownership_Mobile</value>
      <webElementGuid>7dcaab80-ec23-4e89-9924-80d0689d3c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم الجوال</value>
      <webElementGuid>ae8a7d80-1bf0-4209-9a54-a574cb08f037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a785c873-e230-476c-9b96-728f5a76b90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d49d9c6-4454-498f-9667-50d05f39c6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>303041696</value>
      <webElementGuid>a020a3f6-d808-43a5-9532-8477159b27f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnership_Mobile&quot;)</value>
      <webElementGuid>514b6c68-4115-4d64-b15e-b9e62c77dbe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnership_Mobile']</value>
      <webElementGuid>8030069b-2cb1-45ca-baf0-09caaafb0cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditOwnershipDetailsForm']/div/div[5]/div[2]/input</value>
      <webElementGuid>ad6c475a-be3c-4696-8349-f1c39914c84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div[5]/div[2]/input</value>
      <webElementGuid>821b103b-3ee5-4c6a-b278-8309eeb1cff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnership_Mobile' and @name = 'Ownership_Mobile' and @placeholder = 'رقم الجوال' and @type = 'text']</value>
      <webElementGuid>50b3353d-d6af-40d8-a666-f0ede91f0d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
