<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ownership_Email</name>
   <tag></tag>
   <elementGuidId>8c2b66ce-4798-4459-82ad-b03469fe9877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnership_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnership_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77637405-7f3d-4005-9e5c-d5f8ef4dfb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b706a8d6-e9cf-4501-af57-1bf854c3f714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cce57f66-8f72-403a-9944-05678929db23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Email must be a string with a maximum length of 255.</value>
      <webElementGuid>8421c515-f9b0-4cfd-a37b-15979a1f1084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>390cfdcc-265c-4c08-bbc8-391a7e3d2a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>من فضلك أدخل بريد أليكترونى صحيح</value>
      <webElementGuid>07cbdafc-da7f-474b-9b92-c5e8385f181a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z]{2,17})$</value>
      <webElementGuid>e1d9de44-e2b0-43bd-82cf-996695fe3056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل البريد الالكتروني مطلوب</value>
      <webElementGuid>a4380286-e71c-47cb-87af-0ca7176b6899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnership_Email</value>
      <webElementGuid>cbb5e9b9-f35a-4dac-aa30-adad9a749636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8b4cd459-38be-4697-98cf-f72ad9f08cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ownership_Email</value>
      <webElementGuid>715aa9c4-1df3-48dc-917d-00290e576544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>البريد الالكتروني</value>
      <webElementGuid>5636cee1-1907-49e1-b5aa-c6db342cbbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>158c7da2-4002-430a-9098-f8965d2879de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>959b2faf-73a9-46be-aca3-321f545396fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>s@gmail.com</value>
      <webElementGuid>ba6937f3-74ab-4609-a9b6-fdac7fe672aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnership_Email&quot;)</value>
      <webElementGuid>dbcac694-383e-46a1-90c0-15c26fa99f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnership_Email']</value>
      <webElementGuid>fa2ed2d2-dca5-4122-ace5-8095a1c80e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditOwnershipDetailsForm']/div/div[3]/div[2]/input</value>
      <webElementGuid>23f89559-d956-4ddf-a72d-6735195057b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div[3]/div[2]/input</value>
      <webElementGuid>fc42e6d6-ba6c-4158-9d6e-c60ddbeb7df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnership_Email' and @name = 'Ownership_Email' and @placeholder = 'البريد الالكتروني' and @type = 'text']</value>
      <webElementGuid>7d891eaf-2271-400a-9169-e976c8441302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
