<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ownership_Phone</name>
   <tag></tag>
   <elementGuidId>a9c6a658-83ff-434e-b2ad-0d598120888e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOwnership_Phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOwnership_Phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad6e8210-0ade-4dcd-89a9-79351dc1648a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mob</value>
      <webElementGuid>17c070a2-0bd3-4459-969a-c7b061f9172b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>643fe5bf-2705-41ad-8b90-a01816b2723e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>الحقل رقم الهاتف مطلوب</value>
      <webElementGuid>72d70129-a552-4b9f-ba5c-b93172e10c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOwnership_Phone</value>
      <webElementGuid>2e791c1b-846f-4835-bcdc-f5a5a82ed193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4623aa6f-4da0-4393-bc56-736d41aaec31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ownership_Phone</value>
      <webElementGuid>836ec11c-4019-4c49-bf36-a2f3692f297f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم الهاتف</value>
      <webElementGuid>53627de2-8d87-4024-bc3b-1210ad0075d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c3c84d61-b5d7-43a4-83bb-0039d4acedf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a047bce2-5b28-4cf9-ad9c-b03cfcd4beb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>330041696</value>
      <webElementGuid>82852d6c-25f0-4fd3-b31e-be87878a04fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOwnership_Phone&quot;)</value>
      <webElementGuid>ee851078-26bd-4941-bcf3-780faf3ac580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOwnership_Phone']</value>
      <webElementGuid>4144e5d3-2818-416e-b943-d7dd52fc0837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditOwnershipDetailsForm']/div/div[4]/div[2]/input</value>
      <webElementGuid>d27484f3-6bd5-4e51-8a59-d1903c968d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/form/div/div[4]/div[2]/input</value>
      <webElementGuid>4155d620-77b2-496c-ada7-dc485ab074b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtOwnership_Phone' and @name = 'Ownership_Phone' and @placeholder = 'رقم الهاتف' and @type = 'text']</value>
      <webElementGuid>682aaef4-16b8-41af-a2b6-c264e60d61b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
