<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save9</name>
   <tag></tag>
   <elementGuidId>4c382ec4-d77e-4150-8e33-6cfa792a960c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnClassificationSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnClassificationSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09f592b4-2952-4344-9135-72a24d4a8549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4b20a6f-ed16-4694-a281-da170830d91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnarrright</value>
      <webElementGuid>601cdf85-5816-4f25-be86-fd877e68efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClassificationSave</value>
      <webElementGuid>25d3edab-4736-42d3-ba3b-4db29dbdd5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ و التالي</value>
      <webElementGuid>d4fa5d9a-64f5-484a-be3c-e01d1b291ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClassificationSave&quot;)</value>
      <webElementGuid>419b94f0-b4bc-4638-b384-d6347ad2d439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnClassificationSave']</value>
      <webElementGuid>28852a53-13f3-4ee7-95e5-774488ed9431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SMEProfile']/div/div/div/div/div[5]/input[2]</value>
      <webElementGuid>9687e235-598f-4971-b7f6-0ee35122044c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>70475082-5f25-4f1a-9138-2001b64a43a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnClassificationSave']</value>
      <webElementGuid>9a608b06-3264-4e73-bb66-08b2fea938c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
