<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search for nashat</name>
   <tag></tag>
   <elementGuidId>28d521f1-6c9d-4fcc-9e9c-eddcdce4ec24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtfilterManufacturer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtfilterManufacturer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90c5b7b9-f3e1-462f-acb7-00d403b6d919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfilterManufacturer</value>
      <webElementGuid>6e129aac-bd34-4b6c-8d83-d835a2e6a2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner k-input k-textbox k-input-solid k-input-md k-rounded-md</value>
      <webElementGuid>27631ad3-1183-4c74-8fbf-5f8a312bdc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>ed4bdadc-d36e-441d-afd8-30cd24a20db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfilterManufacturer&quot;)</value>
      <webElementGuid>8614a1c2-1885-4798-92e3-4c19dc3689d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtfilterManufacturer']</value>
      <webElementGuid>72ee5139-a816-461f-8ca1-8aef0b5f163f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divManufacture']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>a2be6bd6-ab70-48f5-b302-c74de2ecb6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>0d490c3c-09bb-4123-95db-f4a3092201cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtfilterManufacturer']</value>
      <webElementGuid>7895cdbd-80d9-4e32-a37f-3f1c5f3e5ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
