<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select4</name>
   <tag></tag>
   <elementGuidId>903d24ea-9754-43da-9815-aa1c290982bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-hover.k-state-focused > span.k-select > span.k-icon.k-i-arrow-60-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CompanyHierarchyDiv']/div/div[2]/div/div/span[2]/span/span[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;CompanyHierarchyDiv&quot;)/div[@class=&quot;bg-box-shadow&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 col-lg-12 form-group&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12 fl-right pad-right-0 pad-left-0 pad-left-mob-0 pad-right-mob-0&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f0718b0d-c065-4ed7-8133-36f372ce736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>a0d70b10-760f-42dc-a50f-e3691510eed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyHierarchyDiv&quot;)/div[@class=&quot;bg-box-shadow&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 col-lg-12 form-group&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12 fl-right pad-right-0 pad-left-0 pad-left-mob-0 pad-right-mob-0&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>43cb308f-99e3-4944-bbb4-f1d66056cc85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyHierarchyDiv']/div/div[2]/div/div/span[2]/span/span[2]/span</value>
      <webElementGuid>8869efae-96fd-41a2-91ee-99b92fa4f7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]/span/span[2]/span</value>
      <webElementGuid>a299a768-fb4e-450f-9b4e-e9e93cc05d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
