<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2</name>
   <tag></tag>
   <elementGuidId>ed764de2-887b-4579-8184-48f41364850f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-focused > span.k-select > span.k-icon.k-i-arrow-60-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='EditOwnershipDetailsForm']/div/div[5]/div/span/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6dfb762f-d234-4422-92ac-ae7975657e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>93adf82a-401c-4c97-9edf-eac341840c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditOwnershipDetailsForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12 fl-right&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>b4b2d052-cce6-425e-91c5-2ed0a0a29338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditOwnershipDetailsForm']/div/div[5]/div/span/span/span[2]/span</value>
      <webElementGuid>93b94e73-f06d-4333-8f85-c7729956e106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/span/span[2]/span</value>
      <webElementGuid>19a9d5c1-f4f3-4de7-be04-b1cebfabd25c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
