<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select 1</name>
   <tag></tag>
   <elementGuidId>e005c142-de0f-41d2-9fde-4b64d1888e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-hover.k-state-focused > span.k-select > span.k-icon.k-i-arrow-60-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='EditOwnershipDetailsForm']/div/div[4]/div/span/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22379773-1425-443b-9e6a-70c39cfe8426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>d8cf57c9-b5dc-4b94-bfa3-992bafc0c4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditOwnershipDetailsForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12 fl-right&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>249eb70b-6c88-4f11-8f1a-a1c1f54243b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EditOwnershipDetailsForm']/div/div[4]/div/span/span/span[2]/span</value>
      <webElementGuid>85e0e1f8-5b12-4cd4-bbfa-bdd12a6a8186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span[2]/span</value>
      <webElementGuid>bef35d0c-343f-4ce1-9605-0ce71a08250e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
