<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select company</name>
   <tag></tag>
   <elementGuidId>5f87d4b0-f2cd-4f21-a059-18bf0af95028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdCR_active_cell > div.grid_nav</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@onclick='TakeAction(this);'])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>900014df-96c4-4dc1-9280-413e6cc72731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid_nav</value>
      <webElementGuid>a5971353-ecee-443a-a12b-52caabb3c1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TakeAction(this);</value>
      <webElementGuid>d619b4a2-0ec5-4751-a405-fa0c380c5d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      <webElementGuid>c388f76e-8137-44c0-9236-9a9da21045e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@onclick='TakeAction(this);'])[18]</value>
      <webElementGuid>10ba41f2-b49b-43e6-a150-c12338dfd947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grdCR_active_cell']/div</value>
      <webElementGuid>ad4c6e88-da4e-4246-b731-e6b52b1f64c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[7]/div</value>
      <webElementGuid>f525ffb1-2e28-4972-8dab-d1d659981422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
