<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select company</name>
   <tag></tag>
   <elementGuidId>5f87d4b0-f2cd-4f21-a059-18bf0af95028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdCR_active_cell > div.grid_nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@onclick='TakeAction(this);'])[20]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1837670b-22e4-40d3-97c9-80610179dcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid_nav</value>
      <webElementGuid>4a77fd48-57f8-47c0-8b1c-ddb7398046c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TakeAction(this);</value>
      <webElementGuid>abf7537c-8e29-429b-aea7-f7f9bfd8b37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      <webElementGuid>f691a070-012c-4084-9152-2d7982cddfcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@onclick='TakeAction(this);'])[18]</value>
      <webElementGuid>659b0aa3-3009-4aa6-8a11-1e5a80d435db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grdCR_active_cell']/div</value>
      <webElementGuid>423436a7-0d65-4518-b111-e3ddf89a48a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[7]/div</value>
      <webElementGuid>5d61a166-8884-43e3-83c9-36497eaf4adf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
