<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select company</name>
   <tag></tag>
   <elementGuidId>5f87d4b0-f2cd-4f21-a059-18bf0af95028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdCR_active_cell > div.grid_nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@onclick='TakeAction(this);'])[18]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbbf0a0f-13de-47d2-8825-631a81df12d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid_nav</value>
      <webElementGuid>ebc12804-d0b3-4b2d-a279-ca84d16edab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TakeAction(this);</value>
      <webElementGuid>601fe6f6-79e2-4612-80c5-caa12f3292f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      <webElementGuid>3351e72a-941b-4edf-a6eb-1db956b71f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@onclick='TakeAction(this);'])[18]</value>
      <webElementGuid>df9e8943-15f5-4b62-9765-694a869d9e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grdCR_active_cell']/div</value>
      <webElementGuid>0c745521-a00d-495b-9a8f-2c40ce0009b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[7]/div</value>
      <webElementGuid>97345254-7961-4101-9827-5ab31f08143c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
