<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slect4in</name>
   <tag></tag>
   <elementGuidId>45fd73a4-1082-45f2-8b0f-80c6be15721e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlCompanyPresence_listbox > li.k-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ddlCompanyPresence_listbox']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b754a8cf-16dc-4cd1-a9cb-bc08178ccd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d3e48a08-39d7-4ec8-91d7-761431c8af39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>305eacb7-fe67-4afe-aa23-4953d5fb301b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d55f5308-5a5a-4c8d-9bdd-008b964f7a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>a147082d-c624-4c48-b305-35c397308024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8fd8b66-9ec5-411d-a37e-b0ffeaa80c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54d42144-035e-4bbb-83b2-a3a2981b00e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>عالمية</value>
      <webElementGuid>524006f6-1e08-4d82-b9ea-3df1912010b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlCompanyPresence_listbox&quot;)/li[@class=&quot;k-item&quot;]</value>
      <webElementGuid>b9c41228-4ccd-4de6-a09d-23781dd0876c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ddlCompanyPresence_listbox']/li</value>
      <webElementGuid>d57601e7-c803-4d9f-a9f5-4763c67edb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--اختيار وجود الشركة--'])[2]/following::li[1]</value>
      <webElementGuid>135b49ac-04a2-4b13-84ec-d90bab97cd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[4]/following::li[1]</value>
      <webElementGuid>4e89608b-fa48-49a0-8601-80a127b1ee66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='محلية'])[1]/preceding::li[1]</value>
      <webElementGuid>1bd14f13-b5f7-4201-9ce6-8c96de3b0561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[5]/preceding::li[2]</value>
      <webElementGuid>89a4b3a9-9fbb-4b29-b466-6b8aafe5db56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='عالمية']/parent::*</value>
      <webElementGuid>7dae6037-bf95-4765-bb23-1324b2518fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[3]/ul/li</value>
      <webElementGuid>ec60a3f3-4d41-4cfd-ac72-90e309db6aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'عالمية' or . = 'عالمية')]</value>
      <webElementGuid>ae4a074c-807a-4871-abd2-3babb4a79c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
