<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_</name>
   <tag></tag>
   <elementGuidId>bdc8b4fe-8dbf-40d2-b668-a359953688d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdSMEClassificationAgentActivity_active_cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='grdSMEClassificationAgentActivity_active_cell']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'grdSMEClassificationAgentActivity_active_cell' and (text() = '​' or . = '​')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>877d2e38-2929-4fe7-858b-0640ca4268e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>a6fb09a1-07ff-4405-8c1a-a1a262aa170f</value>
      <webElementGuid>b97e47eb-3ef3-4bc6-8944-bf99594e1346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f0adf69c-1db8-4369-b2b0-dd0a344ecc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdSMEClassificationAgentActivity_active_cell</value>
      <webElementGuid>7805fe19-9bba-4ccc-bcce-2a9b7bd43cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-state-focused</value>
      <webElementGuid>ad6eb3e0-7435-4941-acb6-b85a45830ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>20be9f45-c4d1-4436-b7e2-8faec0df0863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdSMEClassificationAgentActivity_active_cell&quot;)</value>
      <webElementGuid>63fcde24-f7c0-4637-9ccf-c6ac693c4826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='grdSMEClassificationAgentActivity_active_cell']</value>
      <webElementGuid>f9424857-07a0-4666-b7d5-20d651c4a10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdSMEClassificationAgentActivity']/div[2]/table/tbody/tr/td</value>
      <webElementGuid>1664c5dd-340c-4310-a96c-a4ec89b9b36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم النشاط'])[2]/following::td[1]</value>
      <webElementGuid>d1f5f8e7-cc8e-4395-aed7-099223e68c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رمز النشاط'])[2]/following::td[1]</value>
      <webElementGuid>5086a0b0-d2eb-47ca-a125-8edbd8de5106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انتاج أنواع لحوم الدواجن والأرانب والطيور الطازجة'])[1]/preceding::td[3]</value>
      <webElementGuid>f671b478-dc36-48bc-b120-d7d9db1599e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/table/tbody/tr/td</value>
      <webElementGuid>73d9ad95-e5b1-4dc9-89c1-1509c928b45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'grdSMEClassificationAgentActivity_active_cell' and (text() = '​' or . = '​')]</value>
      <webElementGuid>9c7fd115-b422-4a5b-901a-38e3499e3b4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
