<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5in</name>
   <tag></tag>
   <elementGuidId>9ae96cb6-9bc9-4e34-8a46-bb709855b1d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='txtCompanyHierarchy_InCorporationCountry_listbox']/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cddb88b5-3249-47a2-9538-b774162d068b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9728df72-c7ee-4e1d-85e4-9e06068cd41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ee28ede3-bde7-4fd9-9c90-364de83cc65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f9eade24-c9ba-4ead-a225-b2763730e674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>6eb9ffd6-c460-402c-9e53-c7de26c1b24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>932a565e-0c22-4829-b56c-5718360d3198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b13095c2-465b-4592-8d77-1f2a186b9fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الجزائر</value>
      <webElementGuid>2bb9c34c-e08d-4694-9fd8-ed40f90407b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCompanyHierarchy_InCorporationCountry_listbox&quot;)/li[@class=&quot;k-item&quot;]</value>
      <webElementGuid>4b7e01ca-4728-4e7b-b49c-28ccbd763d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='txtCompanyHierarchy_InCorporationCountry_listbox']/li[4]</value>
      <webElementGuid>bfe97802-77a7-4ab5-8544-94706e0ab06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ألبانيا'])[1]/following::li[1]</value>
      <webElementGuid>82c108dc-bbfd-4e0a-a34b-104e9305b037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جزر آلاند'])[1]/following::li[2]</value>
      <webElementGuid>6d6a9956-276c-4456-9350-19835e1a6bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أندورا'])[1]/preceding::li[1]</value>
      <webElementGuid>8f10e3d7-80a4-4857-833f-619711b47e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أنجولا'])[1]/preceding::li[2]</value>
      <webElementGuid>35f30f8d-d3c8-40bd-8814-330943d3d4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الجزائر']/parent::*</value>
      <webElementGuid>c7986a08-ed14-4291-b783-cd8881761be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[3]/ul/li[4]</value>
      <webElementGuid>b90da523-319e-4b82-ae67-dbe79a8ba543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'الجزائر' or . = 'الجزائر')]</value>
      <webElementGuid>cfa00627-74fd-4213-9daf-113834d4b779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
