<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add new wakel</name>
   <tag></tag>
   <elementGuidId>65b91d36-b3d5-484d-ba31-af03383ee160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_ShowAgentPopup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_ShowAgentPopup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>511f1886-8b6a-4a5e-9e8a-a752348df5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_ShowAgentPopup</value>
      <webElementGuid>64f6b64c-ce56-4425-bd96-3cd33770cd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59ecc33b-8a98-4b2a-b8e1-770990a8e07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-xs pull-right btnadd</value>
      <webElementGuid>2dd279a1-8b42-4b0f-810c-a08b19d3ab69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowAgentPopup('id6+z2Jyqx8BYnXmKl0xrA==','اضافة شركة (الوكيل)')</value>
      <webElementGuid>075f74f5-0b67-4c9e-9ed3-a741ea700b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            اضافة شركة (الوكيل)
                                                        </value>
      <webElementGuid>67770a5b-f985-4d8c-b633-75657143f7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_ShowAgentPopup&quot;)</value>
      <webElementGuid>9fa8560d-5177-495c-9746-3add52b4d4f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_ShowAgentPopup']</value>
      <webElementGuid>41009ae5-c77a-47eb-a8a4-6d4504da86ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAgent']/div/div/button</value>
      <webElementGuid>1ea87f9e-b8be-435b-8b30-871550f585ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شركات الوكيل'])[1]/following::button[1]</value>
      <webElementGuid>f10bca32-9ee9-472e-b5dd-6c9da9d1cff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الشركة باللغة الانجليزية (الوكيل)'])[1]/preceding::button[1]</value>
      <webElementGuid>91e4ed19-0130-4c0c-a74a-dd2266df637b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الشركة باللغة العربية (الوكيل)'])[1]/preceding::button[1]</value>
      <webElementGuid>41b9d9ff-061e-461b-a268-48a3064eb315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اضافة شركة (الوكيل)']/parent::*</value>
      <webElementGuid>83236b46-698e-4b61-9aee-67f4789e8ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/button</value>
      <webElementGuid>de8f1a5d-dad1-41f1-9c52-8daa8b0efcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_ShowAgentPopup' and @type = 'button' and (text() = '
                                                            اضافة شركة (الوكيل)
                                                        ' or . = '
                                                            اضافة شركة (الوكيل)
                                                        ')]</value>
      <webElementGuid>42a48623-676f-4089-b632-fa9e8d914376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
