<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>784fe452-4f2c-4580-bf97-dd5020db01a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnInsuranceSave_Popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnInsuranceSave_Popup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7930bbf-8931-4ef0-953e-26c943cbce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe55579b-0410-4c8d-bc39-43b0780d3cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnInsuranceSave_Popup</value>
      <webElementGuid>35238346-d422-47a3-994c-3ee8e0ca00a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnadd</value>
      <webElementGuid>546b543c-1a84-4093-98e8-cad83d6942ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إضافة التأمين</value>
      <webElementGuid>dcf3c759-6fb8-43a8-8d6b-10d8a8a0042a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnInsuranceSave_Popup&quot;)</value>
      <webElementGuid>8d2be413-83cc-4e1a-90ef-821cbe709962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnInsuranceSave_Popup']</value>
      <webElementGuid>b6ad3a60-5971-48a5-9efa-a0e4a697bef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormInsurance']/div[5]/button</value>
      <webElementGuid>c6c04680-553c-4d5b-8f3c-ad56383910d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر ملف ...'])[5]/following::button[1]</value>
      <webElementGuid>10cc9a4f-dc52-4b17-b396-46cecb5f79c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إرفاق نسخة من شهادة التأمين'])[1]/following::button[1]</value>
      <webElementGuid>2f84ff2d-7ddb-4abb-b28a-a5c209faa9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إغلاق'])[1]/preceding::button[1]</value>
      <webElementGuid>1278e1f7-1388-4b01-a8ed-12d3df57fd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::button[6]</value>
      <webElementGuid>7a5f04cd-cb1f-4455-a53e-491485d034e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة التأمين']/parent::*</value>
      <webElementGuid>654b8cdf-6ad8-426b-b307-99a767fdf15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/button</value>
      <webElementGuid>4dc47515-b4ae-4e69-923a-291931ce07cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnInsuranceSave_Popup' and (text() = 'إضافة التأمين' or . = 'إضافة التأمين')]</value>
      <webElementGuid>4f1c52e4-8c1f-4eef-bf8a-fea11ae3f636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
