<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calender right</name>
   <tag></tag>
   <elementGuidId>e48b60b3-5ea4-436f-a294-32a67a537c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@aria-label='Next']//span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.k-link.k-nav-next.k-state-hover > span.k-icon.k-i-arrow-60-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef187d47-5b9f-4625-8bcd-9c153e9cbfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-right</value>
      <webElementGuid>38402a90-f897-4f42-88b7-4226398734e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e220e1f0-fdd8-4591-8f6d-54a0695f60ed&quot;)/div[@class=&quot;k-header&quot;]/a[@class=&quot;k-link k-nav-next k-state-hover&quot;]/span[@class=&quot;k-icon k-i-arrow-60-right&quot;]</value>
      <webElementGuid>f73527aa-066b-4217-b80a-ce9dab75ce83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e220e1f0-fdd8-4591-8f6d-54a0695f60ed']/div/a[3]/span</value>
      <webElementGuid>403d0e34-1c2a-4d87-8230-e8d4118664a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/div/div/a[3]/span</value>
      <webElementGuid>10c34c88-2620-4b9f-9e4d-d8d5b9ed4b62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
