<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_mother yes</name>
   <tag></tag>
   <elementGuidId>be6828fc-c84c-4551-9c9c-6d502274c8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.fl-right.radio-toolbar.pad-right-0.pad-left-0.pad-left-mob-0.pad-right-mob-0 > label.padding10-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CompanyHierarchyDiv']/div/div[3]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>33c00f15-27e2-4d9a-ad97-0843fe2f5e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rdTech_Orgz_ParentCompanyYes</value>
      <webElementGuid>6abc2ec1-552f-4128-8031-b64bbb5b9f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding10-radio</value>
      <webElementGuid>293885f9-752b-4f6e-bdec-8d90376bce21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>نعم</value>
      <webElementGuid>996013ac-23ff-4a14-92de-5fa3647fcf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyHierarchyDiv&quot;)/div[@class=&quot;bg-box-shadow&quot;]/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-sm-6 fl-right radio-toolbar pad-right-0 pad-left-0 pad-left-mob-0 pad-right-mob-0&quot;]/label[@class=&quot;padding10-radio&quot;]</value>
      <webElementGuid>4401887d-5732-42b7-85c6-7a16032039f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CompanyHierarchyDiv']/div/div[3]/div[2]/label</value>
      <webElementGuid>84caf2af-f9ad-4689-9ac2-b8f9256af887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هل لدى منشآتك شركة أم؟'])[1]/following::label[1]</value>
      <webElementGuid>6b8a7d4a-3804-4af6-a1a5-d5dbbfdcbec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حقل وجود الشركة مطلوب'])[1]/following::label[2]</value>
      <webElementGuid>71d37777-c5e3-4f15-a6cc-e39eea1d36ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا'])[3]/preceding::label[1]</value>
      <webElementGuid>6cafa055-c935-4b4a-bde2-b04bb8bd34c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اسم الشركة الام'])[1]/preceding::label[2]</value>
      <webElementGuid>182da65a-42c2-4e5e-93d3-c0c97fe0881f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='نعم']/parent::*</value>
      <webElementGuid>afb842f4-064d-43e0-8656-4e0f49cb2414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div[2]/label</value>
      <webElementGuid>5116f424-ac93-43dc-9be8-4d79b1a1024c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'نعم' or . = 'نعم')]</value>
      <webElementGuid>c1a49317-02da-4f93-99b1-fa977c84ac6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
