<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>open wakel</name>
   <tag></tag>
   <elementGuidId>4400d2c3-8a39-4ded-98c2-611e8f3b1938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCollapse2 > span.glyphicon.glyphicon-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnCollapse2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>70b57a13-9ff9-44c4-a68f-e0136c733189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-plus</value>
      <webElementGuid>eda3d324-39fa-49bd-941b-c66e65fa5fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCollapse2&quot;)/span[@class=&quot;glyphicon glyphicon-plus&quot;]</value>
      <webElementGuid>ff182d95-56b9-430f-b79d-378f784221aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnCollapse2']/span</value>
      <webElementGuid>180f1739-fbd0-46cd-a4eb-31ee131448b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h5/div/span</value>
      <webElementGuid>c49d90c2-936c-463c-ba0d-a7a15ef1cae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
