<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select nashat</name>
   <tag></tag>
   <elementGuidId>68235661-3503-42b3-915e-9ee387b7fd4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k-multiselect-wrap.k-floatwrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvClassification']/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c36df1dc-a329-400a-a8e8-aea53120a617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-multiselect-wrap k-floatwrap</value>
      <webElementGuid>3afec244-f197-45ab-b853-09e6cb12db3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1dc081a4-eab1-4d3d-bc6b-318a6edc47b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClassificationTab&quot;)/div[@id=&quot;dvClassification&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-xs-12 col-sm-12&quot;]/div[@class=&quot;k-widget k-multiselect k-multiselect-clearable k-state-focused k-state-border-down&quot;]/div[@class=&quot;k-multiselect-wrap k-floatwrap&quot;]</value>
      <webElementGuid>bedf3a35-16ff-413d-b41b-39b06ef4fa84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvClassification']/div[2]/div[2]/div/div</value>
      <webElementGuid>a03e75a7-39f2-4b1b-a403-adb1974e3123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تصنيف المنشآة'])[1]/following::div[3]</value>
      <webElementGuid>d4ac4d57-bff0-4551-a210-0685b9d98c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حجم المنشآة'])[1]/following::div[6]</value>
      <webElementGuid>4871fba6-006f-4475-b1bb-4155b18b3941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قائمة الأنشطة'])[1]/preceding::div[5]</value>
      <webElementGuid>12ff8b62-a440-47eb-b9ca-2ece204c05f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>889edd4b-31ee-4849-ac79-9ce387845051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
