<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-    -_k-icon k-i-arrow-60-down</name>
   <tag></tag>
   <elementGuidId>a5945895-6fdd-4f47-a7d5-6615becf07c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-hover.k-state-focused > span.k-select > span.k-icon.k-i-arrow-60-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='FormInsurance']/div[3]/div/span/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5b16072f-9a6f-470f-8c88-285e8013cd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>c3d70cd2-3766-4b5f-9809-1f4041d477f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormInsurance&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-md-6 col-lg-6&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>05d011bc-8881-4152-957a-786dea2bd4b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FormInsurance']/div[3]/div/span/span/span[2]/span</value>
      <webElementGuid>c5033243-a28b-4cb3-8195-ecc1bd540d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/span/span/span[2]/span</value>
      <webElementGuid>28bfaac0-2f1b-4ceb-9642-363d7c4ac323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
