<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__AttachmentDetailsgrid_active_cell</name>
   <tag></tag>
   <elementGuidId>8ff616cb-8047-46df-872f-d78ff5f6d654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AttachmentDetailsgrid_active_cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='AttachmentDetailsgrid_active_cell']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b75de649-cac4-4a47-aafe-78ea39217d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-state-focused</value>
      <webElementGuid>e201ad56-eef1-4f57-a956-6626dbb01535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>5a95ccdb-d7e7-4af4-9303-f0cac3aa97ec</value>
      <webElementGuid>ee4b1881-055a-4816-a446-a4231fdbb4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>2ed6e43f-66e3-4dcd-a958-5923a327f733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AttachmentDetailsgrid_active_cell</value>
      <webElementGuid>767f6ebc-7161-490c-9f23-865b4b43a34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)</value>
      <webElementGuid>127fdf4f-0203-4db3-850c-f64478eeca6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']</value>
      <webElementGuid>a8cc9c37-a8c7-4ab5-9159-b1f4a784dea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AttachmentDetailsgrid']/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>24a1b729-1d5c-48a9-af8b-22d1e2f7fd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شهادة اثبات وكالة'])[1]/following::td[3]</value>
      <webElementGuid>ccb4669c-9125-49e1-8c0b-e9d4c8bd106e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::td[5]</value>
      <webElementGuid>2a29d78d-f898-4db1-b20f-191d42f66097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select files...'])[1]/preceding::td[1]</value>
      <webElementGuid>ee707690-3d87-4682-8355-861111a38e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شهادة من الهيئة الملكية للجبيل وينبع'])[1]/preceding::td[10]</value>
      <webElementGuid>31edbde7-c3f1-472f-abab-ffb828996a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>50247dc9-bc79-402e-af3a-af282f53b9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'AttachmentDetailsgrid_active_cell']</value>
      <webElementGuid>5173e599-7496-4a25-a176-8ebf2cdfb4b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
