<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__AttachmentDetailsgrid_active_cell</name>
   <tag></tag>
   <elementGuidId>8ff616cb-8047-46df-872f-d78ff5f6d654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AttachmentDetailsgrid_active_cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='AttachmentDetailsgrid_active_cell']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5a1c2873-0bc6-499e-8e7e-ec715c6e9212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-state-focused</value>
      <webElementGuid>5c65f964-1506-4adc-bb34-6758478f5daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>5a95ccdb-d7e7-4af4-9303-f0cac3aa97ec</value>
      <webElementGuid>444a8340-9fef-44e2-97c2-df03535b3b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>e3f8015f-c75f-483a-94bc-5b873c377153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AttachmentDetailsgrid_active_cell</value>
      <webElementGuid>6b90c28b-db40-40bc-b28e-4a167acc2355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachmentDetailsgrid_active_cell&quot;)</value>
      <webElementGuid>2cdb45ab-a4d3-421c-b7df-ffdcf87690d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='AttachmentDetailsgrid_active_cell']</value>
      <webElementGuid>b30f915f-dfc2-46a8-b906-e2e838f7a3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AttachmentDetailsgrid']/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>93ab51d5-7923-448d-84e0-650c8a8f511e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شهادة اثبات وكالة'])[1]/following::td[3]</value>
      <webElementGuid>e7c28fdd-40b4-40b8-b94e-f41f2602dc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::td[5]</value>
      <webElementGuid>8f7d9a6f-f570-4a8d-a4b7-b3e68adbc426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select files...'])[1]/preceding::td[1]</value>
      <webElementGuid>c6aa589f-95b4-4f85-b8f1-74df759618f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شهادة من الهيئة الملكية للجبيل وينبع'])[1]/preceding::td[10]</value>
      <webElementGuid>ad6b2d45-5a90-431d-8393-648b904a630a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>33da5d19-ba6f-4ef5-b527-c3c7e818743d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'AttachmentDetailsgrid_active_cell']</value>
      <webElementGuid>f0222523-f8dd-4055-a27f-ee1b631c88c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
