<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select</name>
   <tag></tag>
   <elementGuidId>5f87d4b0-f2cd-4f21-a059-18bf0af95028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grdCR_active_cell > div.grid_nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@onclick='TakeAction(this);'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8020bc2e-9f0e-4456-82cc-034d425c89a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid_nav</value>
      <webElementGuid>141325dd-984d-40e6-8959-b3439282b93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TakeAction(this);</value>
      <webElementGuid>1905dc4f-9209-401b-91e0-396309858aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdCR_active_cell&quot;)/div[@class=&quot;grid_nav&quot;]</value>
      <webElementGuid>d863560f-bd9f-466c-a0db-5d492541877a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@onclick='TakeAction(this);'])[18]</value>
      <webElementGuid>698b6ca5-afd7-462d-9497-18b581e01787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grdCR_active_cell']/div</value>
      <webElementGuid>848aeb0c-d43a-42bd-822f-1bf7a0f51700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[7]/div</value>
      <webElementGuid>562a3868-4cb7-4154-9115-4ce2cf39d1e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
